const fs = require('fs');
const file = './src/lib/i18n.ts';
let content = fs.readFileSync(file, 'utf8');

const baseTranslations = {
    en: {
        'collections.autoRouteDesc': 'Automatically build an optimal route holding the collections you select.',
        'collections.collectionPublished': 'Collection published successfully!',
        'collections.curatedBy': 'Curated by',
        'collections.generateAutoRoute': 'Generate AutoRoute',
        'collections.planTrip': 'Plan Trip',
        'collections.publishCollection': 'Publish Collection',
        'collections.share': 'Share',
        'collections.shareSuccess': 'Link copied to clipboard!',
        'feedback.error': 'Error submitting feedback. Please try again.',
        'feedback.placeholder': 'Tell us what you think...',
        'feedback.send': 'Send Feedback',
        'feedback.sending': 'Sending...',
        'feedback.subtitle': 'Help us improve by sharing your feedback.',
        'feedback.success': 'Thank you! Your feedback has been received.',
        'feedback.title': 'Send Feedback',
        'nav.feedback': 'Feedback',
        'plans.confirmEndTrip': 'Are you sure you want to end this trip?',
        'plans.confirmSave': 'Confirm & Save Plan',
        'plans.dragReorder': 'Drag to reorder → tap to place',
        'plans.endTrip': 'End Trip',
        'plans.est': 'Est.',
        'plans.generating': 'Generating route...',
        'plans.noRouteData': 'No route data available.',
        'plans.noStops': 'No stops in this plan.',
        'plans.reviewAutoRoute': 'Review AutoRoute',
        'plans.reviewAutoRouteDesc': "We've sorted your selected museums geographically. Give your plan a name and date.",
        'plans.routeItinerary': 'Route Itinerary',
        'plans.saveButton': 'Save',
        'plans.saving': 'Saving...',
        'plans.startingDate': 'Starting Date',
        'plans.startTripButton': 'Start Trip',
        'plans.tripEnded': 'Trip has ended.',
        'plans.tripTitle': 'Trip Title',
        'plans.tripTitlePlaceholder': 'e.g. My Paris Art Tour',
        'review.exceedLimit': 'You can only upload up to 3 images.',
        'review.lines': 'lines',
        'review.placeholder': 'Write your 3-line review here...',
        'review.submit': 'Submit Review',
        'review.submitting': 'Submitting...',
        'review.subtitle': 'Share your experience in just 3 lines.',
        'review.threeLineReview': 'Your 3-line review',
        'review.title': 'Write a Review',
    },
    ko: {
        'collections.autoRouteDesc': '선택한 컬렉션들을 기반으로 최적화된 경로를 자동 생성합니다.',
        'collections.collectionPublished': '컬렉션이 성공적으로 발행되었습니다!',
        'collections.curatedBy': '큐레이터',
        'collections.generateAutoRoute': '최적 경로 생성',
        'collections.planTrip': '여행 계획하기',
        'collections.publishCollection': '컬렉션 발행하기',
        'collections.share': '공유하기',
        'collections.shareSuccess': '링크가 클립보드에 복사되었습니다!',
        'feedback.error': '의견 전송에 실패했습니다. 다시 시도해주세요.',
        'feedback.placeholder': '여기에 의견을 적어주세요...',
        'feedback.send': '의견 보내기',
        'feedback.sending': '전송 중...',
        'feedback.subtitle': '서비스 개선을 위해 여러분의 소중한 의견을 들려주세요.',
        'feedback.success': '감사합니다! 의견이 성공적으로 접수되었습니다.',
        'feedback.title': '의견 보내기',
        'nav.feedback': '의견 보내기',
        'plans.confirmEndTrip': '이 여행을 종료하시겠습니까?',
        'plans.confirmSave': '저장 및 설정 완료',
        'plans.dragReorder': '드래그하여 순서 변경',
        'plans.endTrip': '여행 종료',
        'plans.est': '예상 소요 시간',
        'plans.generating': '경로 생성 중...',
        'plans.noRouteData': '경로 정보가 없습니다',
        'plans.noStops': '이 계획에 추가된 장소가 없습니다.',
        'plans.reviewAutoRoute': '자동 경로 확인',
        'plans.reviewAutoRouteDesc': '선택한 미술관들을 지리적으로 정렬했습니다. 여행 이름과 시작일을 설정하세요.',
        'plans.routeItinerary': '여행 일정',
        'plans.saveButton': '저장하기',
        'plans.saving': '저장 중...',
        'plans.startingDate': '시작일',
        'plans.startTripButton': '여행 시작하기',
        'plans.tripEnded': '여행이 종료되었습니다.',
        'plans.tripTitle': '여행 이름',
        'plans.tripTitlePlaceholder': '예: 파리 3일 미술관 투어',
        'review.exceedLimit': '사진은 최대 3장까지 첨부 가능합니다.',
        'review.lines': '줄',
        'review.placeholder': '3줄 평을 작성해보세요...',
        'review.submit': '리뷰 등록',
        'review.submitting': '등록 중...',
        'review.subtitle': '나의 경험을 가장 잘 나타내는 세 줄.',
        'review.threeLineReview': '나의 3줄 평',
        'review.title': '리뷰 작성',
    },
    ja: {
        'collections.autoRouteDesc': '選択したコレクションから最適なルートを構築します。',
        'collections.collectionPublished': 'コレクションが公開されました！',
        'collections.curatedBy': '作成者',
        'collections.generateAutoRoute': 'オートルートを生成',
        'collections.planTrip': '旅行を計画',
        'collections.publishCollection': 'コレクションを公開',
        'collections.share': 'シェア',
        'collections.shareSuccess': 'リンクをコピーしました！',
        'feedback.error': 'エラーが発生しました。もう一度お試しください。',
        'feedback.placeholder': 'ご意見をお聞かせください...',
        'feedback.send': 'フィードバックを送信',
        'feedback.sending': '送信中...',
        'feedback.subtitle': 'フィードバックを共有して改善にご協力ください。',
        'feedback.success': 'ありがとうございます！',
        'feedback.title': 'フィードバックを送信',
        'nav.feedback': 'フィードバック',
        'plans.confirmEndTrip': '旅行を終了しますか？',
        'plans.confirmSave': '保存',
        'plans.dragReorder': 'ドラッグして並べ替え',
        'plans.endTrip': '旅行を終了',
        'plans.est': '予想',
        'plans.generating': 'ルートを作成中...',
        'plans.noRouteData': 'ルート情報がありません',
        'plans.noStops': '場所がありません。',
        'plans.reviewAutoRoute': 'ルートを確認',
        'plans.reviewAutoRouteDesc': '美術館を地理的に並び替えました。',
        'plans.routeItinerary': '旅程',
        'plans.saveButton': '保存',
        'plans.saving': '保存中...',
        'plans.startingDate': '出発日',
        'plans.startTripButton': '旅行を開始',
        'plans.tripEnded': '旅行は終了しました。',
        'plans.tripTitle': 'タイトル',
        'plans.tripTitlePlaceholder': '例: パリ美術ツアー',
        'review.exceedLimit': '最大3枚までです。',
        'review.lines': '行',
        'review.placeholder': '3行レビューを書いてください...',
        'review.submit': '投稿する',
        'review.submitting': '投稿中...',
        'review.subtitle': '3行で経験を共有。',
        'review.threeLineReview': 'あなたの3行レビュー',
        'review.title': 'レビューを書く',
    },
    de: {
        'collections.autoRouteDesc': 'Erstellen Sie automatisch eine optimale Route.',
        'collections.collectionPublished': 'Sammlung veröffentlicht!',
        'collections.curatedBy': 'Kuratiert von',
        'collections.generateAutoRoute': 'AutoRoute generieren',
        'collections.planTrip': 'Reise planen',
        'collections.publishCollection': 'Veröffentlichen',
        'collections.share': 'Teilen',
        'collections.shareSuccess': 'Link kopiert!',
        'feedback.error': 'Fehler beim Senden. Bitte versuchen Sie es erneut.',
        'feedback.placeholder': 'Sagen Sie uns Ihre Meinung...',
        'feedback.send': 'Feedback senden',
        'feedback.sending': 'Senden...',
        'feedback.subtitle': 'Helfen Sie uns, uns zu verbessern.',
        'feedback.success': 'Danke! Ihr Feedback wurde empfangen.',
        'feedback.title': 'Feedback senden',
        'nav.feedback': 'Feedback',
        'plans.confirmEndTrip': 'Möchten Sie diese Reise beenden?',
        'plans.confirmSave': 'Speichern',
        'plans.dragReorder': 'Ziehen zum Neuordnen',
        'plans.endTrip': 'Reise beenden',
        'plans.est': 'Vorauss.',
        'plans.generating': 'Generiere...',
        'plans.noRouteData': 'Keine Route verfügbar',
        'plans.noStops': 'Keine Stopps.',
        'plans.reviewAutoRoute': 'Route überprüfen',
        'plans.reviewAutoRouteDesc': 'Museen sortiert. Name und Datum eingeben.',
        'plans.routeItinerary': 'Reiseroute',
        'plans.saveButton': 'Speichern',
        'plans.saving': 'Speichern...',
        'plans.startingDate': 'Startdatum',
        'plans.startTripButton': 'Reise starten',
        'plans.tripEnded': 'Reise beendet.',
        'plans.tripTitle': 'Titel',
        'plans.tripTitlePlaceholder': 'z.B. Paris Kunsttour',
        'review.exceedLimit': 'Maximal 3 Bilder.',
        'review.lines': 'Zeilen',
        'review.placeholder': '3-Zeilen-Bewertung...',
        'review.submit': 'Bewertung senden',
        'review.submitting': 'Senden...',
        'review.subtitle': 'Ihre Erfahrung in 3 Zeilen.',
        'review.threeLineReview': 'Ihre Bewertung',
        'review.title': 'Bewertung',
    },
    fr: {
        'collections.autoRouteDesc': 'Créer automatiquement un itinéraire.',
        'collections.collectionPublished': 'Collection publiée !',
        'collections.curatedBy': 'Créé par',
        'collections.generateAutoRoute': 'Générer AutoRoute',
        'collections.planTrip': 'Planifier le voyage',
        'collections.publishCollection': 'Publier la collection',
        'collections.share': 'Partager',
        'collections.shareSuccess': 'Lien copié !',
        'feedback.error': 'Erreur. Veuillez réessayer.',
        'feedback.placeholder': 'Dites-nous ce que vous pensez...',
        'feedback.send': 'Envoyer',
        'feedback.sending': 'Envoi...',
        'feedback.subtitle': 'Aidez-nous à nous améliorer.',
        'feedback.success': 'Merci!',
        'feedback.title': 'Envoyer des commentaires',
        'nav.feedback': 'Commentaires',
        'plans.confirmEndTrip': 'Voulez-vous vraiment terminer ce voyage ?',
        'plans.confirmSave': 'Confirmer & Sauvegarder',
        'plans.dragReorder': 'Glissez pour réorganiser',
        'plans.endTrip': 'Terminer le voyage',
        'plans.est': 'Est.',
        'plans.generating': 'Génération...',
        'plans.noRouteData': 'Aucun itinéraire',
        'plans.noStops': 'Aucun arrêt.',
        'plans.reviewAutoRoute': 'Aperçu AutoRoute',
        'plans.reviewAutoRouteDesc': 'Musées triés géographiquement. Entrez nom et date.',
        'plans.routeItinerary': 'Itinéraire',
        'plans.saveButton': 'Sauvegarder',
        'plans.saving': 'Sauvegarde...',
        'plans.startingDate': 'Date de départ',
        'plans.startTripButton': 'Commencer',
        'plans.tripEnded': 'Le voyage est terminé.',
        'plans.tripTitle': 'Titre',
        'plans.tripTitlePlaceholder': 'ex: Visite d\'art à Paris',
        'review.exceedLimit': 'Maximum 3 images.',
        'review.lines': 'lignes',
        'review.placeholder': 'Critique en 3 lignes...',
        'review.submit': 'Soumettre',
        'review.submitting': 'Soumission...',
        'review.subtitle': 'Partagez votre expérience.',
        'review.threeLineReview': 'Votre critique',
        'review.title': 'Écrire une critique',
    },
    es: {
        'collections.autoRouteDesc': 'Crear ruta óptima automáticamente.',
        'collections.collectionPublished': '¡Colección publicada!',
        'collections.curatedBy': 'Por',
        'collections.generateAutoRoute': 'Generar AutoRuta',
        'collections.planTrip': 'Planear Viaje',
        'collections.publishCollection': 'Publicar Colección',
        'collections.share': 'Compartir',
        'collections.shareSuccess': '¡Enlace copiado!',
        'feedback.error': 'Error de envío.',
        'feedback.placeholder': 'Dinos qué piensas...',
        'feedback.send': 'Enviar',
        'feedback.sending': 'Enviando...',
        'feedback.subtitle': 'Ayúdanos a mejorar.',
        'feedback.success': '¡Gracias!',
        'feedback.title': 'Enviar Comentarios',
        'nav.feedback': 'Comentarios',
        'plans.confirmEndTrip': '¿Finalizar viaje?',
        'plans.confirmSave': 'Guardar',
        'plans.dragReorder': 'Arrastrar para reordenar',
        'plans.endTrip': 'Finalizar Viaje',
        'plans.est': 'Est.',
        'plans.generating': 'Generando...',
        'plans.noRouteData': 'Sin datos de ruta',
        'plans.noStops': 'Sin paradas.',
        'plans.reviewAutoRoute': 'Revisar AutoRuta',
        'plans.reviewAutoRouteDesc': 'Museos ordenados. Introduce título y fecha.',
        'plans.routeItinerary': 'Itinerario',
        'plans.saveButton': 'Guardar',
        'plans.saving': 'Guardando...',
        'plans.startingDate': 'Fecha de inicio',
        'plans.startTripButton': 'Iniciar Viaje',
        'plans.tripEnded': 'El viaje ha terminado.',
        'plans.tripTitle': 'Título',
        'plans.tripTitlePlaceholder': 'ej. Tour París',
        'review.exceedLimit': 'Máximo 3 imágenes.',
        'review.lines': 'líneas',
        'review.placeholder': 'Escribe tu reseña...',
        'review.submit': 'Enviar reseña',
        'review.submitting': 'Enviando...',
        'review.subtitle': 'Comparte en 3 líneas.',
        'review.threeLineReview': 'Tu reseña de 3 líneas',
        'review.title': 'Escribir una reseña',
    },
    pt: {
        'collections.autoRouteDesc': 'Criar rota ideal automaticamente.',
        'collections.collectionPublished': 'Coleção publicada!',
        'collections.curatedBy': 'Curadoria de',
        'collections.generateAutoRoute': 'Gerar AutoRota',
        'collections.planTrip': 'Planejar Viagem',
        'collections.publishCollection': 'Publicar Coleção',
        'collections.share': 'Compartilhar',
        'collections.shareSuccess': 'Link copiado!',
        'feedback.error': 'Erro ao enviar.',
        'feedback.placeholder': 'O que você achou...',
        'feedback.send': 'Enviar',
        'feedback.sending': 'Enviando...',
        'feedback.subtitle': 'Ajude-nos a melhorar.',
        'feedback.success': 'Obrigado!',
        'feedback.title': 'Enviar Feedback',
        'nav.feedback': 'Feedback',
        'plans.confirmEndTrip': 'Encerrar esta viagem?',
        'plans.confirmSave': 'Salvar Plano',
        'plans.dragReorder': 'Arraste para reordenar',
        'plans.endTrip': 'Encerrar Viagem',
        'plans.est': 'Est.',
        'plans.generating': 'Gerando...',
        'plans.noRouteData': 'Sem dados de rota',
        'plans.noStops': 'Sem paradas.',
        'plans.reviewAutoRoute': 'Revisar AutoRota',
        'plans.reviewAutoRouteDesc': 'Museus ordenados. Insira título e data.',
        'plans.routeItinerary': 'Itinerário',
        'plans.saveButton': 'Salvar',
        'plans.saving': 'Salvando...',
        'plans.startingDate': 'Data de início',
        'plans.startTripButton': 'Iniciar Viagem',
        'plans.tripEnded': 'Viagem terminou.',
        'plans.tripTitle': 'Título',
        'plans.tripTitlePlaceholder': 'ex. Tour Paris',
        'review.exceedLimit': 'Máximo de 3 imagens.',
        'review.lines': 'linhas',
        'review.placeholder': 'Escreva sua avaliação...',
        'review.submit': 'Enviar Avaliação',
        'review.submitting': 'Enviando...',
        'review.subtitle': 'Compartilhe sua experiência.',
        'review.threeLineReview': 'Sua avaliação',
        'review.title': 'Escrever Avaliação',
    },
    'zh-CN': {
        'collections.autoRouteDesc': '根据所选收藏自动生成最佳路线。',
        'collections.collectionPublished': '收藏夹已发布！',
        'collections.curatedBy': '创建者',
        'collections.generateAutoRoute': '生成自动路线',
        'collections.planTrip': '计划旅行',
        'collections.publishCollection': '发布收藏夹',
        'collections.share': '分享',
        'collections.shareSuccess': '链接已复制！',
        'feedback.error': '提交反馈出错。请重试。',
        'feedback.placeholder': '告诉我们您的想法...',
        'feedback.send': '发送反馈',
        'feedback.sending': '发送中...',
        'feedback.subtitle': '分享您的反馈以帮助我们改进。',
        'feedback.success': '谢谢！已收到反馈。',
        'feedback.title': '发送反馈',
        'nav.feedback': '意见反馈',
        'plans.confirmEndTrip': '结束此次旅行吗？',
        'plans.confirmSave': '保存计划',
        'plans.dragReorder': '拖动以重新排序',
        'plans.endTrip': '结束旅行',
        'plans.est': '预计',
        'plans.generating': '路线生成中...',
        'plans.noRouteData': '无路线数据',
        'plans.noStops': '无站点',
        'plans.reviewAutoRoute': '查看自动路线',
        'plans.reviewAutoRouteDesc': '请设定路线名称和日期。',
        'plans.routeItinerary': '行程',
        'plans.saveButton': '保存',
        'plans.saving': '保存中...',
        'plans.startingDate': '出发日期',
        'plans.startTripButton': '开始旅行',
        'plans.tripEnded': '旅行已结束。',
        'plans.tripTitle': '旅行标题',
        'plans.tripTitlePlaceholder': '例：巴黎艺术游',
        'review.exceedLimit': '最多上传3张图片。',
        'review.lines': '行',
        'review.placeholder': '在此写下你的三行评论...',
        'review.submit': '提交评论',
        'review.submitting': '提交中...',
        'review.subtitle': '用三行文字分享你的体验。',
        'review.threeLineReview': '你的三行评论',
        'review.title': '写评论',
    },
    'zh-TW': {
        'collections.autoRouteDesc': '根據所選收藏自動生成最佳路線。',
        'collections.collectionPublished': '收藏夾已發佈！',
        'collections.curatedBy': '建立者',
        'collections.generateAutoRoute': '生成自動路線',
        'collections.planTrip': '計畫旅行',
        'collections.publishCollection': '發佈收藏夾',
        'collections.share': '分享',
        'collections.shareSuccess': '連結已複製！',
        'feedback.error': '提交反饋出錯。請重試。',
        'feedback.placeholder': '告訴我們您的想法...',
        'feedback.send': '發送反饋',
        'feedback.sending': '發送中...',
        'feedback.subtitle': '分享您的反饋以幫助我們改進。',
        'feedback.success': '謝謝！已收到反饋。',
        'feedback.title': '發送反饋',
        'nav.feedback': '意見反饋',
        'plans.confirmEndTrip': '結束此次旅行嗎？',
        'plans.confirmSave': '儲存計劃',
        'plans.dragReorder': '拖曳以重新排序',
        'plans.endTrip': '結束旅行',
        'plans.est': '預計',
        'plans.generating': '路線生成中...',
        'plans.noRouteData': '無路線資料',
        'plans.noStops': '無站點',
        'plans.reviewAutoRoute': '查看自動路線',
        'plans.reviewAutoRouteDesc': '請設定路線名稱和日期。',
        'plans.routeItinerary': '行程',
        'plans.saveButton': '儲存',
        'plans.saving': '儲存中...',
        'plans.startingDate': '出發日期',
        'plans.startTripButton': '開始旅行',
        'plans.tripEnded': '旅行已結束。',
        'plans.tripTitle': '旅行標題',
        'plans.tripTitlePlaceholder': '例：巴黎藝術遊',
        'review.exceedLimit': '最多上傳3張圖片。',
        'review.lines': '行',
        'review.placeholder': '在此寫下你的三行評論...',
        'review.submit': '提交評論',
        'review.submitting': '提交中...',
        'review.subtitle': '用三行文字分享你的體驗。',
        'review.threeLineReview': '你的三行評論',
        'review.title': '寫評論',
    }
};

const keysToReplace = Object.keys(baseTranslations.en);

for (const lang of Object.keys(baseTranslations)) {
    const langKey = lang.includes('-') ? `'${lang}'` : lang;
    const langRegex = new RegExp(`^\\s*${langKey}:\\s*{`, 'm');
    const startIdx = content.search(langRegex);
    if (startIdx === -1) {
        console.error("Could not find lang block " + lang);
        continue;
    }

    let endIdx = -1;
    let braceCount = 0;
    for (let i = startIdx; i < content.length; i++) {
        if (content[i] === '{') braceCount++;
        if (content[i] === '}') {
            braceCount--;
            if (braceCount === 0) {
                endIdx = i;
                break;
            }
        }
    }

    if (endIdx !== -1) {
        let block = content.substring(startIdx, endIdx + 1);

        const translations = baseTranslations[lang];
        for (const [k, v] of Object.entries(translations)) {
            const keyRegex = new RegExp(`'${k}':\\s*'(?:${k}|)'`, 'g');
            block = block.replace(keyRegex, `'${k}': '${v.replace(/'/g, "\\'")}'`);
        }

        content = content.substring(0, startIdx) + block + content.substring(endIdx + 1);
    }
}

fs.writeFileSync(file, content, 'utf8');
console.log('Successfully fully translated all missing keys.');
