const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

// Map museum name → visitor info. Names must match exactly.
const infoByName = {
    '"Alda Levi" Roman amphitheatre park and Antiquarium': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '야외 공원, 항시 개방' }, { icon: '📍', label: '위치', value: 'Via De Amicis, Milan, Italy' }, { icon: '🚇', label: '교통', value: '메트로 M2 Sant\'Ambrogio역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    '"Dr. Julio Marc" Provincial Historical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-18:00, 토~일 14:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parque de la Independencia, Rosario, Argentina' }, { icon: '🚇', label: '교통', value: '로사리오 독립공원 내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    '100th Bomb Group Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '5~9월 토·일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Common Road, Dickleburgh, Norfolk, UK' }, { icon: '🚇', label: '교통', value: '노리치에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '21st Century Museum of Contemporary Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 1,200엔~)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (금·토 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: '1-2-1 Hirosaka, Kanazawa, Japan' }, { icon: '🚇', label: '교통', value: '가나자와역 버스 20분 / 히로사카 정류장' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }], website: 'https://www.kanazawa21.jp' },
    '21st Century Museum of Contemporary Art, Kanazawa': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 1,200엔~)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (금·토 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: '1-2-1 Hirosaka, Kanazawa, Japan' }, { icon: '🚇', label: '교통', value: '가나자와역 버스 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    '1st Infantry Division Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-16:00, 토·일 12:00-16:00' }, { icon: '📍', label: '위치', value: 'Fort Riley, Kansas, USA' }, { icon: '🚇', label: '교통', value: '캔자스시티에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '45th Infantry Division Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-16:15, 토 10:00-16:15, 일 13:00-16:15. 월 휴관' }, { icon: '📍', label: '위치', value: '2145 NE 36th St, Oklahoma City, OK, USA' }, { icon: '🚇', label: '교통', value: '오클라호마시티에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }], website: 'https://www.45thdivisionmuseum.com/' },
    '493rd Bomb Group Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '5~9월 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Debach Airfield, East Suffolk, UK' }, { icon: '🚇', label: '교통', value: '이프스위치에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '6th Cavalry Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00 또는 예약제' }, { icon: '📍', label: '위치', value: 'Fort Oglethorpe, GA, USA' }, { icon: '🚇', label: '교통', value: '채터누가에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '82nd Airborne Division War Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:30' }, { icon: '📍', label: '위치', value: 'Fort Liberty, NC, USA' }, { icon: '🚇', label: '교통', value: '페이어트빌에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    '8Q SAM': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-19:00 (금 ~21:00)' }, { icon: '📍', label: '위치', value: '8 Queen Street, Singapore 188535' }, { icon: '🚇', label: '교통', value: 'MRT Bras Basah역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    '9.18 Historical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (신분증 필수)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: '46 Wanghua South St, Dadong, Shenyang, China' }, { icon: '🚇', label: '교통', value: '선양 지하철 9호선 9·18역' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Abbazia di Pomposa': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€, 할인 2.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Pomposa Centro 12, Codigoro, Italy' }, { icon: '🚇', label: '교통', value: '페라라에서 차량 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Abbey of Monte Cassino': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '매일 08:45-12:30, 15:30-17:00' }, { icon: '📍', label: '위치', value: 'Via Montecassino, Cassino, Italy' }, { icon: '🚇', label: '교통', value: '카시노역에서 셔틀 20분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Abbey of the Holy Spirit at Monte Morrone': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-19:00' }, { icon: '📍', label: '위치', value: 'Badia Morronese, Sulmona, Italy' }, { icon: '🚇', label: '교통', value: '술모나역 택시 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Abegg foundation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 20 CHF (~$22)' }, { icon: '🕐', label: '운영시간', value: '4~11월 화~일 14:00-17:30. 동절기 휴관' }, { icon: '📍', label: '위치', value: 'Riggisberg, Switzerland' }, { icon: '🚇', label: '교통', value: '베른에서 버스 160번 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Abteiberg Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€, 할인 4.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Abteistraße 27, Mönchengladbach, Germany' }, { icon: '🚇', label: '교통', value: 'Hbf 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Academy of San Carlos': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Academia 22, Centro, Mexico City' }, { icon: '🚇', label: '교통', value: '메트로 Zócalo역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Accademia Carrara': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 할인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Carrara 82, Bergamo, Italy' }, { icon: '🚇', label: '교통', value: '베르가모역 버스 1번' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Accademia di San Luca': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-19:00' }, { icon: '📍', label: '위치', value: 'Piazza dell\'Accademia di San Luca 77, Rome' }, { icon: '🚇', label: '교통', value: 'Barberini역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'ADBC Museum, Education & Research Center': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $5' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00 예약제' }, { icon: '📍', label: '위치', value: 'Wellsburg, WV, USA' }, { icon: '🚇', label: '교통', value: '피츠버그에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Admont Abbey': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13.50€, 학생 8€' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Kirchplatz 1, Admont, Austria' }, { icon: '🚇', label: '교통', value: '그라츠에서 기차+버스 2시간' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Adrien Dubouché National Museum (Limoges)': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-12:30, 14:00-17:45. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place Winston Churchill, Limoges, France' }, { icon: '🚇', label: '교통', value: '리모주역 버스 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Aeroseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 150 SEK (~$14)' }, { icon: '🕐', label: '운영시간', value: '토~일 11:00-16:00' }, { icon: '📍', label: '위치', value: 'Säve flygplats, Gothenburg, Sweden' }, { icon: '🚇', label: '교통', value: '예테보리 중앙역 버스 32분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'African American Civil War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:30, 일 12:00-18:30' }, { icon: '📍', label: '위치', value: '1925 Vermont Ave NW, Washington, D.C.' }, { icon: '🚇', label: '교통', value: 'Green Line U St역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'African American Military History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $5' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00' }, { icon: '📍', label: '위치', value: '305 E 6th St, Hattiesburg, MS' }, { icon: '🚇', label: '교통', value: '해티스버그 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Agung Rai Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '80,000 IDR (~$5)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Jl. Raya Pengosekan, Ubud, Bali' }, { icon: '🚇', label: '교통', value: '우붓 중심가 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Aichi-Nagoya War Archives': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:30' }, { icon: '📍', label: '위치', value: 'Marunouchi, Nagoya, Aichi, Japan' }, { icon: '🚇', label: '교통', value: '나고야 지하철 Marunouchi역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Aihui History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-16:30' }, { icon: '📍', label: '위치', value: 'Aihui District, Heihe, Heilongjiang, China' }, { icon: '🚇', label: '교통', value: '허이허 시내 버스' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Air Force Museum of New Zealand': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '45 Harvard Ave, Wigram, Christchurch, NZ' }, { icon: '🚇', label: '교통', value: '크라이스트처치 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Airborne & Special Operations Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 12:00-17:00' }, { icon: '📍', label: '위치', value: '100 Bragg Blvd, Fayetteville, NC' }, { icon: '🚇', label: '교통', value: '페이어트빌 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Airborne Assault': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £7' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'IWM Duxford, Cambridgeshire, UK' }, { icon: '🚇', label: '교통', value: '케임브리지 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Akademisches Kunstmuseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~금 15:00-17:00, 일 11:00-18:00' }, { icon: '📍', label: '위치', value: 'Am Hofgarten 21, Bonn, Germany' }, { icon: '🚇', label: '교통', value: '본 중앙역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Al Ain National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 금 15:00-19:30' }, { icon: '📍', label: '위치', value: 'Sultan Bin Zayed Fort, Al Ain, UAE' }, { icon: '🚇', label: '교통', value: '두바이에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Al Mahatta Fort': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토~목 08:00-20:00, 금 16:00-20:00' }, { icon: '📍', label: '위치', value: 'Al Estiqlal Square, Sharjah, UAE' }, { icon: '🚇', label: '교통', value: '두바이에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Alabama Veterans Museum and Archives': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-15:00' }, { icon: '📍', label: '위치', value: '100 W Pryor St, Athens, AL' }, { icon: '🚇', label: '교통', value: '아테네 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Albertina': { vi: [{ icon: '🎫', label: '입장료', value: '성인 18.90€, 학생 13.90€. 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (수·금 ~21:00)' }, { icon: '📍', label: '위치', value: 'Albertinaplatz 1, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U2/U4 Karlsplatz역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Albertina Modern': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16.90€. 콤비티켓 22.90€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (수 ~21:00)' }, { icon: '📍', label: '위치', value: 'Karlsplatz 5, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U2/U4 Karlsplatz역 직결' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    "Albrecht Dürer's House": { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€, 할인 1.50€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토~일 ~18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Albrecht-Dürer-Straße 39, Nuremberg, Germany' }, { icon: '🚇', label: '교통', value: '뉘른베르크 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Aldershot Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5.50, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Queens Avenue, Aldershot, UK' }, { icon: '🚇', label: '교통', value: '올더숏역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Altare della Patria': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (전망대 7€)' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-19:30' }, { icon: '📍', label: '위치', value: 'Piazza Venezia, Rome, Italy' }, { icon: '🚇', label: '교통', value: 'Bus Piazza Venezia / 메트로 B Colosseo 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Alte Pinakothek': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 일요일 1€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (화 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Barer Straße 27, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Theresienstraße역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Altes Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€. Museum Island 콤비 19€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Am Lustgarten, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Hackescher Markt역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Amos Rex': { vi: [{ icon: '🎫', label: '입장료', value: '성인 18€, 학생 8€' }, { icon: '🕐', label: '운영시간', value: '월·금 11:00-18:00, 수·목 ~20:00, 토~일 ~17:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Mannerheimintie 22-24, Helsinki' }, { icon: '🚇', label: '교통', value: '헬싱키 중앙역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-2시간' }], website: 'https://amosrex.fi/en/' },
    'Amon Carter Museum of American Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00 (목 ~20:00), 일 12:00-17:00' }, { icon: '📍', label: '위치', value: '3501 Camp Bowie Blvd, Fort Worth, TX' }, { icon: '🚇', label: '교통', value: '시내 차량 10분. 무료 주차' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Amiternum (archeological site)': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외)' }, { icon: '📍', label: '위치', value: 'San Vittorino, L\'Aquila, Italy' }, { icon: '🚇', label: '교통', value: '라퀼라에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'American Memorial Park': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰' }, { icon: '📍', label: '위치', value: 'Beach Road, Garapan, Saipan' }, { icon: '🚇', label: '교통', value: '가라판 중심부' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ancient Aeclanum archaeological park': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외)' }, { icon: '📍', label: '위치', value: 'Mirabella Eclano, Avellino, Italy' }, { icon: '🚇', label: '교통', value: '아벨리노 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ancient Roman architecture in Trieste': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Via del Teatro Romano, Trieste, Italy' }, { icon: '🚇', label: '교통', value: '트리에스테 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Ancient Roman basilica': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€ (Santa Giulia 콤비)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Musei, Brescia, Italy' }, { icon: '🚇', label: '교통', value: '브레시아역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ancient Roman Theatre of Teano': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰' }, { icon: '📍', label: '위치', value: 'Teano, Caserta, Italy' }, { icon: '🚇', label: '교통', value: '나폴리에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Andrew Jackson Cottage and US Rangers Museum': { vi: [{ icon: '🎫', label: '입장료', value: '£5' }, { icon: '🕐', label: '운영시간', value: '6~9월 화~토 11:00-16:00' }, { icon: '📍', label: '위치', value: 'Boneybefore, Carrickfergus, UK' }, { icon: '🚇', label: '교통', value: '벨파스트 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Anglo-Boer War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R40 (~$2)' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-16:30, 토 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Monument Rd, Bloemfontein, South Africa' }, { icon: '🚇', label: '교통', value: '블룸폰테인 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Anıtkabir': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Anıt Cad., Tandoğan, Ankara, Turkey' }, { icon: '🚇', label: '교통', value: '메트로 Tandoğan역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Ankara Aviation Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Etimesgut, Ankara, Turkey' }, { icon: '🚇', label: '교통', value: '앙카라 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Ankara Painting and Sculpture Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Opera Meydanı, Ulus, Ankara, Turkey' }, { icon: '🚇', label: '교통', value: '메트로 Ulus역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Annan Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Bank Street, Annan, UK' }, { icon: '🚇', label: '교통', value: '에난역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Antalya Museum': { vi: [{ icon: '🎫', label: '입장료', value: '120 TL (~$4). Museum Pass 사용 가능' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-19:00' }, { icon: '📍', label: '위치', value: 'Konyaaltı Cad. 88, Antalya, Turkey' }, { icon: '🚇', label: '교통', value: '트램 Müze 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Antiquarian Hall': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수·금 09:00-17:00, 토 09:00-15:00' }, { icon: '📍', label: '위치', value: '185 Salisbury St, Worcester, MA' }, { icon: '🚇', label: '교통', value: '우스터 유니온역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Antiquarium di Boscoreale': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€. 폼페이 콤비 22€' }, { icon: '🕐', label: '운영시간', value: '수~월 08:30-19:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Via Settetermini, Boscoreale, Italy' }, { icon: '🚇', label: '교통', value: 'Circumvesuviana Boscoreale역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Antiquarium di Cannae': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Canne della Battaglia, Barletta, Italy' }, { icon: '🚇', label: '교통', value: '바를레타역 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Antiquarium Lucrezia Romana': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마 시내 버스' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Antiquarium Pyrgense': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30' }, { icon: '📍', label: '위치', value: 'Castello di Santa Severa, Santa Marinella, Italy' }, { icon: '🚇', label: '교통', value: '로마에서 기차 Santa Severa역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Antiquarium Statale di Numana': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30' }, { icon: '📍', label: '위치', value: 'Via La Fenice, Numana, Italy' }, { icon: '🚇', label: '교통', value: '안코나 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Antiquarium Turritano': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-20:00' }, { icon: '📍', label: '위치', value: 'Via Ponte Romano 99, Porto Torres, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '포르토 토레스 항구 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Apsley House': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £12.50' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00' }, { icon: '📍', label: '위치', value: '149 Piccadilly, London, UK' }, { icon: '🚇', label: '교통', value: 'Hyde Park Corner역 직결' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Arbeia South Shields Roman Fort': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Baring Street, South Shields, UK' }, { icon: '🚇', label: '교통', value: '메트로 South Shields역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Arch of Malborghetto': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토~일 09:00-13:00 또는 예약' }, { icon: '📍', label: '위치', value: 'Via Flaminia, Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마 북부 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Archaeological Area of Concordia Sagittaria': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외)' }, { icon: '📍', label: '위치', value: 'Concordia Sagittaria, Venice, Italy' }, { icon: '🚇', label: '교통', value: '베네치아에서 기차+버스 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};

async function run() {
    let ok = 0, fail = 0;
    for (const [name, d] of Object.entries(infoByName)) {
        const vi = JSON.stringify(d.vi);
        let r;
        if (d.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, d.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    // Count remaining
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 이름 불일치, 남은 미입력: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
