const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'LACMA': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (2024~ 상설전 무료)' }, { icon: '🕐', label: '운영시간', value: '월·화·목 11:00-18:00, 금 11:00-20:00, 토·일 10:00-19:00. 수 휴관' }, { icon: '📍', label: '위치', value: '5905 Wilshire Blvd, Los Angeles, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro D Wilshire/Fairfax역. 피터 줌토어 신관 건설 중' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'MACBA Barcelona': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€. 토 16시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '월·수~금 11:00-20:00, 토 10:00-20:00, 일 10:00-15:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Plaça dels Àngels 1, Barcelona, Spain' }, { icon: '🚇', label: '교통', value: '메트로 L1/L2 Universitat역 도보 5분. 리처드 마이어 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MALBA': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2,400 ARS (~$2.70). 수 할인' }, { icon: '🕐', label: '운영시간', value: '목~월 12:00-20:00 (금 ~21:00). 화·수 휴관' }, { icon: '📍', label: '위치', value: 'Av. Figueroa Alcorta 3415, Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: '지하철 D Scalabrini Ortiz역. 라틴아메리카 미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MASP': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R$50 (~$10). 화 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목·금 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Paulista 1578, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 Trianon-MASP역 도보 1분. 리나 보 바르디 건축 + 유리 이젤' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'M+': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 유료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (금 ~22:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'West Kowloon Cultural District, Hong Kong' }, { icon: '🚇', label: '교통', value: 'MTR Airport Express 구롱역 도보 5분. 헤르조그 & 드뫼롱 건축' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'M HKA': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Leuvenstraat 32, Antwerp, Belgium' }, { icon: '🚇', label: '교통', value: '앤트워프 트램 8 Het Zuid. 벨기에 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Leeum Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '서울 용산구 이태원로55길 60-16' }, { icon: '🚇', label: '교통', value: '지하철 6호선 한강진역 1번 출구 도보 5분. 마리오 보타+장 누벨+OMA 건축' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Lenbachhaus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Luisenstr. 33, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Königsplatz역 도보 3분. 칸딘스키·청기사파 세계 최대' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Lee Kong Chian Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 SGD 21 (~$15)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'NUS, 2 Conservatory Drive, Singapore' }, { icon: '🚇', label: '교통', value: 'MRT Kent Ridge역 도보 10분. 동남아 자연사' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Legion of Honor': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15. 매월 첫 화 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:15. 월 휴관' }, { icon: '📍', label: '위치', value: '100 34th Ave, Lincoln Park, San Francisco, CA, USA' }, { icon: '🚇', label: '교통', value: 'Muni 38 Lincoln Park. 금문교 전망 + 로댕' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Mass MoCA': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '1040 Mass MoCA Way, North Adams, MA, USA' }, { icon: '🚇', label: '교통', value: '보스턴에서 차량 3시간. 미국 최대 현대미술 센터' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'MAM São Paulo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parque do Ibirapuera, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 AACD-Servidor역. 오스카 니마이어 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MAM Rio': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R$20 (~$4)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Av. Infante Dom Henrique 85, Flamengo, Rio de Janeiro, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 Cinelândia역. 아폰소 레이디 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Mathaf: Arab Museum of Modern Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토~목 09:00-19:00. 금 휴관' }, { icon: '📍', label: '위치', value: 'Education City, Doha, Qatar' }, { icon: '🚇', label: '교통', value: '도하 메트로 Green Line Education City역. 아랍 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MAK – Museum of Applied Arts': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€. 화 18시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00, 화 10:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Stubenring 5, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U3 Stubentor역 도보 1분. 구스타프 클림트 프리즈' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Liebieghaus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Schaumainkai 71, Frankfurt, Germany' }, { icon: '🚇', label: '교통', value: 'U1/U2/U3 Schweizer Platz역. 5,000년 조각사' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Lázaro Galdiano Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€. 수 15:30 이후 무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:30, 일 10:00-15:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Calle de Serrano 122, Madrid, Spain' }, { icon: '🚇', label: '교통', value: '메트로 5 Rubén Darío역. 고야·엘 그레코' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Lehmbruck Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~금 12:00-17:00, 토·일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Düsseldorfer Str. 51, Duisburg, Germany' }, { icon: '🚇', label: '교통', value: '두이스부르크역 도보 10분. 독일 조각 미술관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Latvian Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Krišjāņa Barona iela 4, Riga, Latvia' }, { icon: '🚇', label: '교통', value: '리가 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Long Museum West Bund': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 CNY (~$14)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: '3398 Longteng Avenue, Shanghai, China' }, { icon: '🚇', label: '교통', value: '지하철 7/11호선 Yunjin Road역 도보 10분. 웨스트번드 예술구' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Ludwig Forum für Internationale Kunst': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jülicher Str. 97-109, Aachen, Germany' }, { icon: '🚇', label: '교통', value: '아헨역 버스. 팝아트·현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Malmö Konsthall': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-17:00 (수 ~20:00)' }, { icon: '📍', label: '위치', value: 'S:t Johannesgatan 7, Malmö, Sweden' }, { icon: '🚇', label: '교통', value: '말뫼 C역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Manchester Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'University of Manchester, Oxford Road, Manchester, UK' }, { icon: '🚇', label: '교통', value: '트램 Oxford Road역. 2023 리뉴얼' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'MARCO Monterrey': { vi: [{ icon: '🎫', label: '입장료', value: '100 MXN (~$5.50). 수 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Zuazua y Jardón, Monterrey, Mexico' }, { icon: '🚇', label: '교통', value: '메트로 Zaragoza역 도보 5분. 라틴아메리카 미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Manial Palace and Museum': { vi: [{ icon: '🎫', label: '입장료', value: '200 EGP (~$6.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Manial, Cairo, Egypt' }, { icon: '🚇', label: '교통', value: '메트로 Mar Girgis역에서 택시. 왕족 궁전' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Lapworth Museum of Geology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-17:00, 토·일 13:00-17:00' }, { icon: '📍', label: '위치', value: 'University of Birmingham, Edgbaston, UK' }, { icon: '🚇', label: '교통', value: '기차 University역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Laing Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 14:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'New Bridge St, Newcastle upon Tyne, UK' }, { icon: '🚇', label: '교통', value: 'Metro Monument역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Las Vegas Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $12' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:00' }, { icon: '📍', label: '위치', value: '900 N Las Vegas Blvd, Las Vegas, NV, USA' }, { icon: '🚇', label: '교통', value: '라스베이거스 다운타운' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'LaM (Lille Métropole musée d\'art moderne, d\'art contemporain et d\'art brut)': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1 Allée du Musée, Villeneuve-d\'Ascq, France' }, { icon: '🚇', label: '교통', value: '메트로 1 Pont de Bois역. 더뷔페·모딜리아니·아르 브뤼' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Łódź Art Center': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10 PLN (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Tymienieckiego 3, Łódź, Poland' }, { icon: '🚇', label: '교통', value: '우치 Fabryczna역 도보 15분. 방직공장 리모델링' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Laguna Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7. 매월 첫 목 무료' }, { icon: '🕐', label: '운영시간', value: '목~화 11:00-17:00. 수 휴관' }, { icon: '📍', label: '위치', value: '307 Cliff Dr, Laguna Beach, CA, USA' }, { icon: '🚇', label: '교통', value: '라구나 비치 해안가. 캘리포니아 미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Manggha': { vi: [{ icon: '🎫', label: '입장료', value: '성인 24 PLN (~$6)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'ul. Marii Konopnickiej 26, Kraków, Poland' }, { icon: '🚇', label: '교통', value: '크라쿠프 바벨성 맞은편. 일본 미술·기술 센터' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Magasin III': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '목~일 12:00-17:00. 월~수 휴관' }, { icon: '📍', label: '위치', value: 'Frihamnen 28, Stockholm, Sweden' }, { icon: '🚇', label: '교통', value: '스톡홀름 프리함넨. 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Madame Tussauds London': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £33 (온라인 £23)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Marylebone Road, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube Baker Street역 도보 2분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Martin Gusinde Anthropological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-13:00, 14:30-18:00, 토·일 14:30-18:30' }, { icon: '📍', label: '위치', value: 'Puerto Williams, Chile' }, { icon: '🚇', label: '교통', value: '세계 최남단 도시. 야간 원주민 문화' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Marine Museum Alexandria': { vi: [{ icon: '🎫', label: '입장료', value: '100 EGP (~$3.25)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Alexandria, Egypt' }, { icon: '🚇', label: '교통', value: '알렉산드리아 해안가' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
