const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Small entries first
    'Broelmuseum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Broelkaai 6, Kortrijk, Belgium' }, { icon: '🚇', label: '교통', value: '코르트레이크역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bublacowie Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD$8' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Bublacowie, South Australia' }, { icon: '🚇', label: '교통', value: '애들레이드에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Buffs Regimental Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Canterbury, Kent, UK' }, { icon: '🚇', label: '교통', value: '캔터베리 웨스트역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Calabar Old Residency Museum': { vi: [{ icon: '🎫', label: '입장료', value: '500 NGN (~$0.50)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Calabar, Cross River State, Nigeria' }, { icon: '🚇', label: '교통', value: '칼라바르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa de la Arquitectura': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-14:00, 17:00-20:00' }, { icon: '📍', label: '위치', value: 'Plaza de España 3, Madrid, Spain' }, { icon: '🚇', label: '교통', value: '메트로 Plaza de España역' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    "Casemate d'Esch": { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '6~9월 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Hatten, Bas-Rhin, Alsace, France' }, { icon: '🚇', label: '교통', value: '스트라스부르에서 차량 45분 (마지노선)' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chelouche Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-18:00, 금 10:00-14:00. 토 휴관' }, { icon: '📍', label: '위치', value: 'Mazeh Street 6, Tel Aviv, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Major museums  
    'Classic Flyers': { vi: [{ icon: '🎫', label: '입장료', value: '성인 NZ$20, 어린이 $10' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Jean Batten Drive, Tauranga, New Zealand' }, { icon: '🚇', label: '교통', value: '타우랑가 공항 인근' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cobbaton Combat Collection': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8.50, 어린이 £4' }, { icon: '🕐', label: '운영시간', value: '4~10월 월~금 10:00-16:00, 일 10:00-16:00. 토 휴관' }, { icon: '📍', label: '위치', value: 'Chittlehampton, Umberleigh, Devon, UK' }, { icon: '🚇', label: '교통', value: '반스터플에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Cold Lake Air Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'CFB Cold Lake, AB, Canada' }, { icon: '🚇', label: '교통', value: '에드먼턴에서 차량 3시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dawson City Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $9 CAD' }, { icon: '🕐', label: '운영시간', value: '5~9월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: '5th Avenue, Dawson City, Yukon, Canada' }, { icon: '🚇', label: '교통', value: '화이트호스에서 차량 5시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Dayton Art Institute': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '수~토 11:00-17:00, 일 12:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '456 Belmonte Park N, Dayton, OH, USA' }, { icon: '🚇', label: '교통', value: '데이턴 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'DDR Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12.50€, 학생 8€. 온라인 예약 할인' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-21:00' }, { icon: '📍', label: '위치', value: 'Karl-Liebknecht-Str. 1, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Hackescher Markt역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Deal Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8, 어린이 £4.80' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Victoria Road, Deal, Kent, UK' }, { icon: '🚇', label: '교통', value: '딜역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Defence and Garrison Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 60 DKK (~$9)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kastellet, Aalborg, Denmark' }, { icon: '🚇', label: '교통', value: '올보르역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Delaware Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10, 어린이 $7' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-16:30. 월·화 휴관' }, { icon: '📍', label: '위치', value: '4840 Kennett Pike, Wilmington, DE, USA' }, { icon: '🚇', label: '교통', value: '필라델피아에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Delta Antico museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-13:00, 15:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Agatopisto, Comacchio, Ferrara, Italy' }, { icon: '🚇', label: '교통', value: '페라라에서 차량 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Denver Museum of Nature and Science': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $22.95, 어린이 $17.95' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '2001 Colorado Blvd, Denver, CO, USA' }, { icon: '🚇', label: '교통', value: 'RTD 버스 32번 / City Park 내. 무료 주차' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Derby Museum and Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 12:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'The Strand, Derby, UK' }, { icon: '🚇', label: '교통', value: '더비역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Design Museum Holon': { vi: [{ icon: '🎫', label: '입장료', value: '성인 35 ILS (~$10), 학생 25 ILS' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00, 금 10:00-14:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '8 Pinhas Eilon Street, Holon, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브에서 기차 Holon역' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Deutsches Historisches Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Unter den Linden 2, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Hackescher Markt역 도보 5분 / U Friedrichstraße역' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Deutsches Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€, 학생 8€. 6세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Museumsinsel 1, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Isartor역 도보 5분 / U Fraunhoferstraße역' }, { icon: '⏱️', label: '관람시간', value: '4-5시간' }] },
    'Dia Beacon': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20, 학생 $12. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '금~월 10:00-17:00. 화~목 휴관 (4~10월 목~월)' }, { icon: '📍', label: '위치', value: '3 Beekman Street, Beacon, NY, USA' }, { icon: '🚇', label: '교통', value: 'Metro-North Beacon역 도보 10분 (그랜드센트럴에서 1.5시간)' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Diocesan Museum of Milan': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Sant\'Eustorgio 3, Milan, Italy' }, { icon: '🚇', label: '교통', value: '메트로 M2 Porta Genova역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Documentation Center Nazi Party Rally Grounds': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€, 학생 1.50€' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-18:00, 토·일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Bayernstraße 110, Nuremberg, Germany' }, { icon: '🚇', label: '교통', value: '트램 8번 Doku-Zentrum 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Dokumentationszentrum Obersalzberg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (11~3월 화~일 10:00-15:00)' }, { icon: '📍', label: '위치', value: 'Salzbergstraße 41, Berchtesgaden, Germany' }, { icon: '🚇', label: '교통', value: '뮌헨에서 기차 2.5시간 / 잘츠부르크에서 버스 1시간' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Doge\'s Palace': { vi: [{ icon: '🎫', label: '입장료', value: '성인 25€ (San Marco 광장 콤비 30€). 6세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00 (동절기 ~18:00)' }, { icon: '📍', label: '위치', value: 'Piazza San Marco, Venice, Italy' }, { icon: '🚇', label: '교통', value: '바포레토 1/2번 San Zaccaria 정류장 / San Marco 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Domus Aurea': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€ (가이드 투어, 예약 필수)' }, { icon: '🕐', label: '운영시간', value: '토·일 09:15-16:15 (예약제, 시즌 한정)' }, { icon: '📍', label: '위치', value: 'Viale della Domus Aurea, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 B선 Colosseo역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간 (가이드 투어)' }] },
    'Douglas Hyde Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 11:00-18:00, 토 11:00-16:45. 일 휴관' }, { icon: '📍', label: '위치', value: 'Trinity College, Dublin 2, Ireland' }, { icon: '🚇', label: '교통', value: 'DART Pearse역 도보 5분 / Luas St Stephen\'s Green' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Dubai Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3 AED (~$0.80), 어린이 1 AED' }, { icon: '🕐', label: '운영시간', value: '토~목 08:30-20:30, 금 14:30-20:30' }, { icon: '📍', label: '위치', value: 'Al Fahidi Fort, Al Fahidi, Bur Dubai, UAE' }, { icon: '🚇', label: '교통', value: '메트로 Green Line Al Fahidi역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dublinia': { vi: [{ icon: '🎫', label: '입장료', value: '성인 €12, 학생 €10, 어린이 €7.50' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:30' }, { icon: '📍', label: '위치', value: 'St Michael\'s Hill, Christchurch, Dublin 8, Ireland' }, { icon: '🚇', label: '교통', value: 'Christchurch 대성당 옆. Luas Smithfield역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Dundurn Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $14 CAD, 어린이 $8' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: '610 York Blvd, Hamilton, ON, Canada' }, { icon: '🚇', label: '교통', value: '해밀턴 GO역에서 버스 / 토론토에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'East Side Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Mühlenstraße, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Ostbahnhof역 또는 U Warschauer Straße역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Eden Camp Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8, 어린이 £5' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Malton, North Yorkshire, UK' }, { icon: '🚇', label: '교통', value: '말턴역 도보 20분 / 요크에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Eastbourne Redoubt': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £6, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Royal Parade, Eastbourne, East Sussex, UK' }, { icon: '🚇', label: '교통', value: '이스트본역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Economy Museum – Royal Coin Cabinet': { vi: [{ icon: '🎫', label: '입장료', value: '성인 150 SEK (~$15)' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Slottsbacken 6, Stockholm, Sweden' }, { icon: '🚇', label: '교통', value: 'T-bana Gamla Stan역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'D21 Kunstraum Leipzig': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~토 14:00-19:00' }, { icon: '📍', label: '위치', value: 'Demmeringstraße 21, Leipzig, Germany' }, { icon: '🚇', label: '교통', value: '라이프치히 시내 트램' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Dinópolis': { vi: [{ icon: '🎫', label: '입장료', value: '성인 29€, 어린이 22€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-20:00 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Polígono Los Planos, Teruel, Spain' }, { icon: '🚇', label: '교통', value: '테루엘역에서 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Dinosaur Discovery Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '5608 10th Avenue, Kenosha, WI, USA' }, { icon: '🚇', label: '교통', value: '시카고에서 Metra 기차 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dinosaurland Fossil Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Coombe Street, Lyme Regis, Dorset, UK' }, { icon: '🚇', label: '교통', value: '본머스에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Don F. Pratt Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~토 09:30-16:15. 일·월·화 휴관' }, { icon: '📍', label: '위치', value: 'Fort Campbell, Kentucky, USA' }, { icon: '🚇', label: '교통', value: '내슈빌에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Drakelow Tunnels': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £15 (투어 예약 필수)' }, { icon: '🕐', label: '운영시간', value: '주말 가이드 투어 (예약제)' }, { icon: '📍', label: '위치', value: 'Near Kidderminster, Worcestershire, UK' }, { icon: '🚇', label: '교통', value: '버밍엄에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Duke of Wellington\'s Regiment Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Bankfield Museum, Halifax, UK' }, { icon: '🚇', label: '교통', value: '핼리팩스역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dymchurch Martello Tower': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £6, 어린이 £3.60' }, { icon: '🕐', label: '운영시간', value: '4~10월 토·일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'High Street, Dymchurch, Kent, UK' }, { icon: '🚇', label: '교통', value: '하이스에서 Romney, Hythe & Dymchurch Railway 소형 기차' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Collection Natural History Museum St.Gallen': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12 CHF (~$13)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Rorschacher Straße 263, St. Gallen, Switzerland' }, { icon: '🚇', label: '교통', value: '장크트갈렌역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Denis air-raid shelter': { vi: [{ icon: '🎫', label: '입장료', value: '성인 130 CZK (~$6)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Husova 12, Brno, Czech Republic' }, { icon: '🚇', label: '교통', value: '브르노 시내 중심 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Denis Diderot House Of Enlightenment': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-13:00, 14:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place Diderot, Langres, Haute-Marne, France' }, { icon: '🚇', label: '교통', value: '파리에서 TGV + 버스 3시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dinan 39-45 Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 14:00-18:00' }, { icon: '📍', label: '위치', value: 'Rue du Quai, Dinan, Côtes-d\'Armor, France' }, { icon: '🚇', label: '교통', value: '렌에서 기차 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dragonermuseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화·금 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Stadtplatz, Wels, Austria' }, { icon: '🚇', label: '교통', value: '벨스역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Colditz Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Schloßgasse 1, Colditz, Saxony, Germany' }, { icon: '🚇', label: '교통', value: '라이프치히에서 기차+버스 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Crimean War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Ontario, Canada' }, { icon: '🚇', label: '교통', value: '온타리오 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cygnaeus Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Kalliolinnantie 8, Helsinki, Finland' }, { icon: '🚇', label: '교통', value: '카이보푸이스토 공원 내. 트램 3번' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'D. Dal Lago civic museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 15:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazzetta Aldo Moro, Valdagno, VI, Italy' }, { icon: '🚇', label: '교통', value: '비첸차에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dahmeland Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Schlossplatz 1, Königs Wusterhausen, Germany' }, { icon: '🚇', label: '교통', value: '베를린 S-Bahn S46 Königs Wusterhausen역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dean Castle': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Dean Road, Kilmarnock, East Ayrshire, Scotland, UK' }, { icon: '🚇', label: '교통', value: '킬마녹역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Delhi Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-19:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Hauz Khas Village, New Delhi, India' }, { icon: '🚇', label: '교통', value: '델리 메트로 Yellow Line Hauz Khas역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Deutsche Guggenheim': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (영구 폐관 2013, 현재 다른 용도)' }, { icon: '🕐', label: '운영시간', value: '폐관' }, { icon: '📍', label: '위치', value: 'Unter den Linden 13-15, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U Französische Straße역' }, { icon: '⏱️', label: '관람시간', value: '-' }] },
    'Dharma Wiratama Museum': { vi: [{ icon: '🎫', label: '입장료', value: '5,000 IDR (~$0.30)' }, { icon: '🕐', label: '운영시간', value: '화~일 08:00-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jl. Jenderal Sudirman 75, Yogyakarta, Indonesia' }, { icon: '🚇', label: '교통', value: '족자카르타 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Documentation and Cultural Centre of German Sinti and Roma': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:30-16:30, 토·일 11:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Bremeneckgasse 2, Heidelberg, Germany' }, { icon: '🚇', label: '교통', value: '하이델베르크 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dolomythos': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Fund de Ríu 2, San Candido/Innichen, South Tyrol, Italy' }, { icon: '🚇', label: '교통', value: '리엔츠에서 기차 San Candido역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Duke of Lancaster\'s Own Yeomanry Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Stanley Street, Preston, Lancashire, UK' }, { icon: '🚇', label: '교통', value: '프레스턴역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Echigo-Matsunoyama Museum of Natural Science "Kyororo"': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔, 어린이 300엔' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Matsunoyama, Tōkamachi, Niigata, Japan' }, { icon: '🚇', label: '교통', value: '에치고유자와에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Eduardo Ribeiro House Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Rua José Clemente 322, Manaus, Amazonas, Brazil' }, { icon: '🚇', label: '교통', value: '마나우스 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Dreamland Gramado': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R$79 (~$16)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:30' }, { icon: '📍', label: '위치', value: 'Rua Arthur Reinheimer 40, Gramado, RS, Brazil' }, { icon: '🚇', label: '교통', value: '포르투 알레그리에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Diocesan Museum of Senigallia': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 15:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Senigallia, Ancona, Italy' }, { icon: '🚇', label: '교통', value: '세니갈리아역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Citta di Castello Communal Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:30-18:00' }, { icon: '📍', label: '위치', value: 'Città di Castello, Perugia, Italy' }, { icon: '🚇', label: '교통', value: '페루자에서 차량 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chilean Planetary': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4,500 CLP (~$5)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Estación Central, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Estación Central역 도보 10분. USACH 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Capas National Shrine': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-17:00' }, { icon: '📍', label: '위치', value: 'Capas, Tarlac, Philippines' }, { icon: '🚇', label: '교통', value: '마닐라에서 차량 2.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Caracas Museum of Natural Sciences': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-16:30, 토·일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Plaza de los Museos, Caracas, Venezuela' }, { icon: '🚇', label: '교통', value: '메트로 Bellas Artes역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'CCA Tel Aviv-Yafo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-19:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '5 Yaffo Street, Tel Aviv, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Coast Guard Museum Northwest': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월·수·금 09:00-15:00' }, { icon: '📍', label: '위치', value: '1519 Alaskan Way S, Seattle, WA, USA' }, { icon: '🚇', label: '교통', value: '시애틀 파이어니어 스퀘어 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Daniel-Pöppelmann-Haus': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Deichtorwall 2, Herford, Germany' }, { icon: '🚇', label: '교통', value: '헤르포르트역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Danish Bank and Savings museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-15:00' }, { icon: '📍', label: '위치', value: 'Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Dat ole Huus': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Bispingen, Lower Saxony, Germany' }, { icon: '🚇', label: '교통', value: '뤼네부르크 히스 내. 함부르크에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Ducal Palace Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:15-19:15. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Sordello 40, Mantua, Italy' }, { icon: '🚇', label: '교통', value: '만토바역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        let r;
        if (info.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, info.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
