const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'Van Gogh Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 20€ (온라인 예약 필수). 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00 (금 ~21:00)' }, { icon: '📍', label: '위치', value: 'Museumplein 6, Amsterdam, Netherlands' }, { icon: '🚇', label: '교통', value: '트램 2/5/12 Van Baerlestraat역. 세계 최대 반 고흐 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Vatican Museums': { vi: [{ icon: '🎫', label: '입장료', value: '성인 17€. 매월 마지막 일 무료 (09:00-14:00)' }, { icon: '🕐', label: '운영시간', value: '월~토 08:00-19:00 (입장 ~17:00). 일 휴관' }, { icon: '📍', label: '위치', value: 'Viale Vaticano, Vatican City' }, { icon: '🚇', label: '교통', value: '메트로 A Ottaviano역 도보 10분. 시스티나 성당 미켈란젤로' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Victoria and Albert Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:45 (금 ~22:00)' }, { icon: '📍', label: '위치', value: 'Cromwell Rd, South Kensington, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube South Kensington역 도보 3분. 세계 최대 장식미술 박물관' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Whitney Museum of American Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25, 학생 $18. 금 19시 이후 자유기부' }, { icon: '🕐', label: '운영시간', value: '월·수·일 10:30-18:00, 목~토 10:30-22:00. 화 휴관' }, { icon: '📍', label: '위치', value: '99 Gansevoort Street, New York, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 A/C/E 14th St역. 렌초 피아노 건축 + 하이라인' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Walker Art Center': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $16. 매월 첫 토 무료. 목 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-17:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '725 Vineland Place, Minneapolis, MN, USA' }, { icon: '🚇', label: '교통', value: 'METRO Green/Blue Line Midtown역. 미니애폴리스 조각공원' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Wadsworth Atheneum Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15. 목 무료' }, { icon: '🕐', label: '운영시간', value: '수~금 11:00-17:00, 토·일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '600 Main St, Hartford, CT, USA' }, { icon: '🚇', label: '교통', value: '하트포드 시내. 미국 최초 공공미술관 (1842)' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Walters Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00 (목 ~21:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: '600 N Charles St, Baltimore, MD, USA' }, { icon: '🚇', label: '교통', value: 'Light Rail Centre St역 도보 5분. 고대~19세기 통사' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Thyssen-Bornemisza Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13€. 월 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-19:00 (토 ~21:00). 월 12:00-16:00' }, { icon: '📍', label: '위치', value: 'Paseo del Prado 8, Madrid, Spain' }, { icon: '🚇', label: '교통', value: '메트로 2 Banco de España역 도보 3분. 13~20세기 서양미술 통사' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'The Phillips Collection': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $16. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 12:00-17:00 (목 ~20:30). 월 휴관' }, { icon: '📍', label: '위치', value: '1600 21st St NW, Washington, D.C., USA' }, { icon: '🚇', label: '교통', value: 'Metro Red Line Dupont Circle역 도보 5분. 미국 최초 모던아트 미술관. 르누아르 보트파티' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'The New Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $18. 목 19시 이후 자유기부' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-18:00 (목 ~21:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: '235 Bowery, New York, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 J/Z Bowery역. SANAA 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Tretyakov Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500 RUB (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '화·수·일 10:00-18:00, 목~토 10:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lavrushinsky Lane 10, Moscow, Russia' }, { icon: '🚇', label: '교통', value: '메트로 Tretyakovskaya역 도보 5분. 러시아 미술 성지' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Unterlinden Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13€' }, { icon: '🕐', label: '운영시간', value: '수~월 09:00-18:00 (목 ~20:00). 화 휴관' }, { icon: '📍', label: '위치', value: 'Place Unterlinden, Colmar, France' }, { icon: '🚇', label: '교통', value: '콜마르역 도보 10분. 이젠하임 제단화 + 헤르조그 & 드뫼롱 신관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'UCCA Center for Contemporary Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 CNY (~$14)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '798 Art District, Chaoyang, Beijing, China' }, { icon: '🚇', label: '교통', value: '지하철 14호선 Jiangtai역. 798 예술구' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Van Abbemuseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-17:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Bilderdijklaan 10, Eindhoven, Netherlands' }, { icon: '🚇', label: '교통', value: '에인트호번역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Vancouver Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $29 CAD. 화 17시 이후 자유기부' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (화·목 ~21:00)' }, { icon: '📍', label: '위치', value: '750 Hornby Street, Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: 'SkyTrain Vancouver City Centre역 도보 5분. 에밀리 카 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Zentrum Paul Klee': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 20 (~$22)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Monument im Fruchtland 3, Bern, Switzerland' }, { icon: '🚇', label: '교통', value: '베른역 버스 12 Zentrum Paul Klee역. 렌초 피아노 건축' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Zachęta': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15 PLN (~$3.75)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Pl. Małachowskiego 3, Warsaw, Poland' }, { icon: '🚇', label: '교통', value: '메트로 Nowy Świat역 도보 5분. 폴란드 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Yad Vashem': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 09:00-17:00, 금 09:00-14:00. 토 휴관' }, { icon: '📍', label: '위치', value: 'Har Hazikaron, Jerusalem, Israel' }, { icon: '🚇', label: '교통', value: '트램 1 Yad Vashem역. 홀로코스트 추모관' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Topography of Terror': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-20:00' }, { icon: '📍', label: '위치', value: 'Niederkirchnerstr. 8, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U6 Kochstr역 / S1/S2 Potsdamer Platz역. 나치 SS/게슈타포 본부 터' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Whitechapel Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '77-82 Whitechapel High St, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube Aldgate East역 도보 1분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'White Rabbit Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '30 Balfour St, Chippendale, Sydney, Australia' }, { icon: '🚇', label: '교통', value: 'Central역 도보 10분. 중국 현대미술 전문' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'WIELS': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-18:00 (목 ~21:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Ave Van Volxem 354, Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '트램 82 WIELS역. 아르데코 맥주공장 리모델링' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Wexner Center for the Arts': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화·수·금~일 11:00-18:00, 목 11:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1871 N High St, Columbus, OH, USA' }, { icon: '🚇', label: '교통', value: '오하이오 주립대 캠퍼스. 피터 아이젠만 건축' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Wolfsonian-FIU': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $12. 금 18시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '월·목~일 10:00-18:00 (금 ~21:00). 화·수 휴관' }, { icon: '📍', label: '위치', value: '1001 Washington Ave, Miami Beach, FL, USA' }, { icon: '🚇', label: '교통', value: '마이애미 비치 아르데코 지구' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'The Mesdag Collection': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Laan van Meerdervoort 7F, The Hague, Netherlands' }, { icon: '🚇', label: '교통', value: '헤이그 시내. 파노라마 메스다흐 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Universalmuseum Joanneum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€ (24시간 통합)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Museumgasse 2, Graz, Austria' }, { icon: '🚇', label: '교통', value: '그라츠 중앙역 트램 1/6. 19개 박물관 통합' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Villa Stuck': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (1번째·3번째 금 ~22:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Prinzregentenstraße 60, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U4 Prinzregentenplatz역 도보 3분. 유겐트슈틸 아틀리에' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Villa Necchi Campiglio': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€ (FAI)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Via Mozart 14, Milan, Italy' }, { icon: '🚇', label: '교통', value: '메트로 M1 San Babila역 도보 5분. 아르데코 빌라' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Thiel Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 130 SEK (~$12)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sjötullsbacken 8, Djurgården, Stockholm, Sweden' }, { icon: '🚇', label: '교통', value: '버스 69 Thielska Galleriet. 뭉크·스트린드베리' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Trapholt': { vi: [{ icon: '🎫', label: '입장료', value: '성인 110 DKK (~$16)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Æblehaven 23, Kolding, Denmark' }, { icon: '🚇', label: '교통', value: '콜딩역 차량 10분. 덴마크 디자인·현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'The Factory Contemporary Arts Centre': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '15 Nguyen U Di, Thao Dien, Ho Chi Minh City, Vietnam' }, { icon: '🚇', label: '교통', value: '호찌민 2군 타오디엔. 베트남 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'The Living Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~금 12:00-18:00, 토·일 13:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Grandagarður 20, Reykjavík, Iceland' }, { icon: '🚇', label: '교통', value: '레이캬비크 올드하버 인근. 아이슬란드 현대미술' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'The Walt Disney Family Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '104 Montgomery St, Presidio, San Francisco, CA, USA' }, { icon: '🚇', label: '교통', value: '프레시디오 공원. Muni 28/30' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Trade Fair Palace': { vi: [{ icon: '🎫', label: '입장료', value: '성인 250 CZK (~$11)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Dukelských hrdinů 47, Prague 7, Czech Republic' }, { icon: '🚇', label: '교통', value: '트램 6/12/17 Veletržní palác역. 체코 국립갤러리 근현대관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Treasury of National Jewels': { vi: [{ icon: '🎫', label: '입장료', value: '150,000 IRR (~$3.60)' }, { icon: '🕐', label: '운영시간', value: '토~화 14:00-16:30. 수~금 휴관' }, { icon: '📍', label: '위치', value: 'Central Bank of Iran, Ferdowsi St, Tehran, Iran' }, { icon: '🚇', label: '교통', value: '테헤란 메트로 Ferdowsi역. 다리야이 누르 다이아 등' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'War Childhood Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10 KM (~$5.60)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Logavina 32, Sarajevo, Bosnia and Herzegovina' }, { icon: '🚇', label: '교통', value: '사라예보 구시가지. 보스니아 전쟁 어린이 기억' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Timken Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:30, 일 12:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: '1500 El Prado, Balboa Park, San Diego, CA, USA' }, { icon: '🚇', label: '교통', value: '발보아 파크 내. 렘브란트·푸생·루벤스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Villa Vauban': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 수 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (금 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '18 Avenue Emile Reuter, Luxembourg City, Luxembourg' }, { icon: '🚇', label: '교통', value: '룩셈부르크 시내 공원. 네덜란드 17세기 회화' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Vienna Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 유료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Karlsplatz 8, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U2/U4 Karlsplatz역. 2023 리뉴얼' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Salzburg Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mozartplatz 1, Salzburg, Austria' }, { icon: '🚇', label: '교통', value: '잘츠부르크역 도보 15분. 모차르트광장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Vorarlberg museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kornmarktplatz 1, Bregenz, Austria' }, { icon: '🚇', label: '교통', value: '브레겐츠역 도보 10분. 보덴호수변' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'The Peenemünde Historical Technical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00, 11~3월 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Im Kraftwerk, Peenemünde, Germany' }, { icon: '🚇', label: '교통', value: '우제돔 섬. V-2 로켓 개발지' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'University of Michigan Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00, 일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '525 S State St, Ann Arbor, MI, USA' }, { icon: '🚇', label: '교통', value: '미시간대 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Utah Museum of Fine Arts': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-17:00, 토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '410 Campus Center Dr, Salt Lake City, UT, USA' }, { icon: '🚇', label: '교통', value: '유타 대학교 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Royal Alberta Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $21 CAD' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (수 ~21:00)' }, { icon: '📍', label: '위치', value: '9810 103a Ave NW, Edmonton, AB, Canada' }, { icon: '🚇', label: '교통', value: '에드먼턴 LRT Churchill역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'The Rooms': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7.50 CAD' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '9 Bonaventure Ave, St. John\'s, NL, Canada' }, { icon: '🚇', label: '교통', value: '세인트존스 시내. 뉴펀들랜드 역사·미술·자연사' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Tosio Martinengo Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Moretto 4, Brescia, Italy' }, { icon: '🚇', label: '교통', value: '브레시아역 도보 15분. 라파엘로·로토' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
