const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const infoByName = {
    'Belgrade City Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300 RSD (~$3)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Zmaj Jovina 1, Belgrade, Serbia' }, { icon: '🚇', label: '교통', value: '베오그라드 리퍼블릭 광장 인근' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Belgrade Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300 RSD (~$3)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kalemegdan Fortress, Belgrade, Serbia' }, { icon: '🚇', label: '교통', value: '칼레메그단 요새 내' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Belogradchik History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5 BGN (~$3)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Belogradchik, Vidin Province, Bulgaria' }, { icon: '🚇', label: '교통', value: '소피아에서 차량 3시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Belvedere 21': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 학생 5.50€. 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Arsenalstraße 1, Vienna, Austria' }, { icon: '🚇', label: '교통', value: '트램 D, O, 18 / Hauptbahnhof 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'BELvue': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€, 학생 2€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Place des Palais 7, Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '메트로 Parc역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Bentwaters Cold War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £7, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '3~10월 일요일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Rendlesham, East Suffolk, UK' }, { icon: '🚇', label: '교통', value: '이프스위치에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Berardo Collection Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-19:00' }, { icon: '📍', label: '위치', value: 'Praça do Império, Belém, Lisbon, Portugal' }, { icon: '🚇', label: '교통', value: '트램 15E Belém / 기차 Belém역' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Berlinische Galerie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€, 할인 6€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Alte Jakobstraße 124-128, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U6 Kochstraße / U1 Hallesches Tor역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Beyeler Foundation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 25 CHF (~$28), 학생 12 CHF. 25세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (수 ~20:00)' }, { icon: '📍', label: '위치', value: 'Baselstrasse 101, Riehen, Switzerland' }, { icon: '🚇', label: '교통', value: '바젤 SBB역에서 트램 6번 Fondation Beyeler 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Big Pit National Coal Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00 (지하 투어 10:00-15:30)' }, { icon: '📍', label: '위치', value: 'Blaenavon, Torfaen, Wales, UK' }, { icon: '🚇', label: '교통', value: '카디프에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Biggin Hill Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8.50, 어린이 £4' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Main Road, Biggin Hill, London, UK' }, { icon: '🚇', label: '교통', value: '런던 시내에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Bilbao Fine Arts Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€. 수요일 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-20:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Museo Plaza 2, Bilbao, Spain' }, { icon: '🚇', label: '교통', value: '메트로 Moyua역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Bill Reid Gallery of Northwest Coast Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $13 CAD, 학생 $9' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '639 Hornby Street, Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: 'SkyTrain Burrard역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Birmingham Museum and Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Chamberlain Square, Birmingham, UK' }, { icon: '🚇', label: '교통', value: '버밍엄 뉴스트리트역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Bletchley Park': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £26, 어린이 £15.50. 온라인 예약 할인' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'The Mansion, Bletchley Park, Milton Keynes, UK' }, { icon: '🚇', label: '교통', value: 'Bletchley역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Bode Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€. Museum Island 콤비 19€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Am Kupfergraben, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Hackescher Markt역 도보 10분 / 트램 M1' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Bogotá Museum of Modern Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10,000 COP (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00, 일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Calle 24 #6-00, Bogotá, Colombia' }, { icon: '🚇', label: '교통', value: 'TransMilenio Las Aguas역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Boncompagni Ludovisi Decorative Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Boncompagni 18, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 A선 Barberini역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Borys Voznytskyi Lviv National Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 UAH (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Stefanyka St 3, Lviv, Ukraine' }, { icon: '🚇', label: '교통', value: '리비우 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Boston Athenæum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (1층). 상층 회원 전용' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '10½ Beacon Street, Boston, MA, USA' }, { icon: '🚇', label: '교통', value: 'Green/Red Line Park Street역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Borodino Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 350₽ (~$4)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Borodino, Moscow Oblast, Russia' }, { icon: '🚇', label: '교통', value: '모스크바에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Bornholms Forsvarsmuseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 60 DKK (~$9)' }, { icon: '🕐', label: '운영시간', value: '6~8월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Bornholm, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐에서 페리 / 비행기' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bansei Tokkō Peace Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Kayoichoubaru, Minamisatsuma, Japan' }, { icon: '🚇', label: '교통', value: '가고시마에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Baekje Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '충남 논산시 연무읍' }, { icon: '🚇', label: '교통', value: '논산역에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'BIASA ArtSpace': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-21:00' }, { icon: '📍', label: '위치', value: 'Jl. Raya Seminyak 34, Bali, Indonesia' }, { icon: '🚇', label: '교통', value: '스미냑 중심가' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Biblioteca e Complesso monumentale dei Girolamini': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 09:30-13:30' }, { icon: '📍', label: '위치', value: 'Via Duomo 142, Naples, Italy' }, { icon: '🚇', label: '교통', value: '나폴리 메트로 Cavour역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Biblioteca Museu Víctor Balaguer': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-14:00, 16:30-20:30. 일 10:00-14:00' }, { icon: '📍', label: '위치', value: 'Av. Víctor Balaguer, Vilanova i la Geltrú, Spain' }, { icon: '🚇', label: '교통', value: '바르셀로나에서 RENFE C2선 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Birmingham Proof House': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (가이드 투어 예약)' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Banbury Street, Birmingham, UK' }, { icon: '🚇', label: '교통', value: '버밍엄 뉴스트리트역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Birthplace of Gabriele D\'Annunzio Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Corso Manthonè, Pescara, Italy' }, { icon: '🚇', label: '교통', value: '페스카라역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Belgrade Post Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Majke Jevrosime 13, Belgrade, Serbia' }, { icon: '🚇', label: '교통', value: '베오그라드 시내 중심' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Border Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Imatra, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키에서 기차 이마트라역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bomb shelter 10-Z': { vi: [{ icon: '🎫', label: '입장료', value: '성인 130 CZK (~$6)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Husova 12, Brno, Czech Republic' }, { icon: '🚇', label: '교통', value: '브르노 시내 중심 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Boden Fortress': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 SEK (~$11)' }, { icon: '🕐', label: '운영시간', value: '6~8월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Boden, Norrbotten, Sweden' }, { icon: '🚇', label: '교통', value: '보든역에서 버스 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Borgia Apartment': { vi: [{ icon: '🎫', label: '입장료', value: '바티칸 미술관 입장료 포함 (성인 17€)' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-18:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Vatican Museums, Vatican City' }, { icon: '🚇', label: '교통', value: '메트로 A선 Cipro역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '바티칸 관람 일부 (30분)' }] },
    'Bernheim-Jeune': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (갤러리)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00' }, { icon: '📍', label: '위치', value: '83 Faubourg Saint-Honoré, Paris 8th, France' }, { icon: '🚇', label: '교통', value: '메트로 Miromesnil역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Bernheimer Fine Old Masters': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (예약제)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Munich, Germany' }, { icon: '🚇', label: '교통', value: '뮌헨 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'August 23 Artillery Battle Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-17:00' }, { icon: '📍', label: '위치', value: 'Jinhu Township, Kinmen, Taiwan' }, { icon: '🚇', label: '교통', value: '진먼섬 내 셔틀버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Beure Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Beure, Doubs, France' }, { icon: '🚇', label: '교통', value: '브장송에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Bible Museum Münster': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Pferdegasse 1, Münster, Germany' }, { icon: '🚇', label: '교통', value: '뮌스터 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bibliorama': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Büchsenstraße 37, Stuttgart, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Stadtmitte역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bibelgalerie Meersburg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Kirchstraße 4, Meersburg, Germany' }, { icon: '🚇', label: '교통', value: '콘스탄츠에서 페리 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bodenseekreis Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Meersburg, Baden-Württemberg, Germany' }, { icon: '🚇', label: '교통', value: '콘스탄츠에서 페리 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bjørn West Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '6~8월 주말' }, { icon: '📍', label: '위치', value: 'Masfjorden, Vestland, Norway' }, { icon: '🚇', label: '교통', value: '베르겐에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};

async function run() {
    let ok = 0, fail = 0;
    for (const [name, d] of Object.entries(infoByName)) {
        const vi = JSON.stringify(d.vi);
        let r;
        if (d.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, d.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 이름 불일치, 남은 미입력: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
