const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'National Portrait Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '매일 10:30-18:00 (금 ~21:00)' }, { icon: '📍', label: '위치', value: 'St Martin\'s Place, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube Charing Cross/Leicester Sq역 도보 1분. 2023 리뉴얼' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Natural History Museum, Vienna': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€, 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '목~월 09:00-18:30, 수 09:00-21:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Burgring 7, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U2 Museumsquartier역 도보 3분. 할슈타트 비너스 소장' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Natural History Museum of Los Angeles County': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15, 학생 $12. 매월 첫 화 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00' }, { icon: '📍', label: '위치', value: '900 W Exposition Blvd, Los Angeles, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro E Expo Park/USC역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Natural History Museum of Utah': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $19.95' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (수 ~21:00)' }, { icon: '📍', label: '위치', value: '301 Wakara Way, Salt Lake City, UT, USA' }, { icon: '🚇', label: '교통', value: '유타 대학교 캠퍼스. TRAX Red Line' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Norton Simon Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15, 학생 $12. 매월 첫 금 무료' }, { icon: '🕐', label: '운영시간', value: '월·수·목 12:00-17:00, 금·토 11:00-20:00, 일 11:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: '411 W Colorado Blvd, Pasadena, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro L Memorial Park역 도보 10분. 렘브란트·드가·인상파' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Norval Foundation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R180 (~$10)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '4 Steenberg Rd, Constantia, Cape Town, South Africa' }, { icon: '🚇', label: '교통', value: '케이프타운 콘스탄시아 지역. 남아프리카 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Ny Carlsberg Glyptotek': { vi: [{ icon: '🎫', label: '입장료', value: '성인 125 DKK (~$18). 화 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Dantes Plads 7, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: 'S-tog/Metro Rådhuspladsen 도보 5분. 고대 이집트+인상파' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Neue Pinakothek': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 일 1€ (현재 리노베이션 중)' }, { icon: '🕐', label: '운영시간', value: '리노베이션 중 - 2025~2029 예정. 일부 작품 알테·현대 피나코텍 전시' }, { icon: '📍', label: '위치', value: 'Barer Str. 29, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Theresienstraße역. 19세기 미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Neue Staatsgalerie': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Konrad-Adenauer-Str. 30-32, Stuttgart, Germany' }, { icon: '🚇', label: '교통', value: 'U5/U6/U7 Staatsgalerie역 도보 1분. 제임스 스털링 포스트모던 건축' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'New Mexico Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $12. 금 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '107 W Palace Ave, Santa Fe, NM, USA' }, { icon: '🚇', label: '교통', value: '산타페 플라자 도보. 푸에블로 리바이벌 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'New Mexico Museum of Natural History and Science': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '1801 Mountain Rd NW, Albuquerque, NM, USA' }, { icon: '🚇', label: '교통', value: '앨버커키 올드타운 인근' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Ogden Museum of Southern Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $13.50' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: '925 Camp St, New Orleans, LA, USA' }, { icon: '🚇', label: '교통', value: '스트리트카 Lee Circle역. 남부 미술 전문' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'North Carolina Museum of Natural Sciences': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (일 12:00-17:00)' }, { icon: '📍', label: '위치', value: '11 W Jones St, Raleigh, NC, USA' }, { icon: '🚇', label: '교통', value: '롤리 시내 다운타운' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    // ★★ Notable
    'Neue Galerie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Innere Stadt, Vienna, Austria' }, { icon: '🚇', label: '교통', value: '빈 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Natural History Museum of Bern': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 10' }, { icon: '🕐', label: '운영시간', value: '월 14:00-17:00, 화~금 09:00-17:00, 토·일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Bernastrasse 15, Bern, Switzerland' }, { icon: '🚇', label: '교통', value: '베른역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum of Crete': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-15:00, 토·일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Sofokli Venizelou Ave, Heraklion, Crete, Greece' }, { icon: '🚇', label: '교통', value: '이라클리오 해안가. 크레타 생태계' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum of Denmark': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 DKK (~$17)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Gothersgade 130, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: 'S-tog Nørreport역 도보 5분. 코펜하겐 식물원 내' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Natural History Museum of Geneva': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Route de Malagnou 1, Geneva, Switzerland' }, { icon: '🚇', label: '교통', value: '버스 1/8 Muséum역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum of Grenoble': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1 Rue Dolomieu, Grenoble, France' }, { icon: '🚇', label: '교통', value: '트램 A/B Verdun역. 알프스 자연사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Natural History Museum of the Lesvos Petrified Forest': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-16:30 (하계 ~19:00)' }, { icon: '📍', label: '위치', value: 'Sigri, Lesvos, Greece' }, { icon: '🚇', label: '교통', value: '미틸리니에서 차량 1.5시간. 2,000만년 화석숲 UNESCO' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum of Mozambique': { vi: [{ icon: '🎫', label: '입장료', value: '50 MZN (~$0.80)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Praça da Travessia do Zambeze, Maputo, Mozambique' }, { icon: '🚇', label: '교통', value: '마푸투 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Natural History Museum of Zimbabwe': { vi: [{ icon: '🎫', label: '입장료', value: '$5 USD' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Centenary Park, Bulawayo, Zimbabwe' }, { icon: '🚇', label: '교통', value: '불라와요 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '5,000 MNT (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Ulaanbaatar, Mongolia' }, { icon: '🚇', label: '교통', value: '울란바토르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Natural History Museum Abu Dhabi': { vi: [{ icon: '🎫', label: '입장료', value: '현재 건설 중 (2025 예정)' }, { icon: '🕐', label: '운영시간', value: '개관 예정' }, { icon: '📍', label: '위치', value: 'Saadiyat Island, Abu Dhabi, UAE' }, { icon: '🚇', label: '교통', value: '사디야트 아일랜드 문화지구' }, { icon: '⏱️', label: '관람시간', value: '2시간 (예상)' }] },
    'Natural History Museum at Tring': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00, 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Akeman Street, Tring, Hertfordshire, UK' }, { icon: '🚇', label: '교통', value: '트링역 도보 15분. 로스차일드 자연사 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum in Oslo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sars\' gate 1, Oslo, Norway' }, { icon: '🚇', label: '교통', value: 'T-bane Tøyen역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum Leipzig': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lortzingstraße 3, Leipzig, Germany' }, { icon: '🚇', label: '교통', value: '라이프치히 Hbf 트램 2/16' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural History Museum Aarhus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 110 DKK (~$16)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Wilhelm Meyers Allé 10, Aarhus, Denmark' }, { icon: '🚇', label: '교통', value: '오르후스 대학교 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'NaturBornholm': { vi: [{ icon: '🎫', label: '입장료', value: '성인 145 DKK (~$21)' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Grønningen 30, Aakirkeby, Bornholm, Denmark' }, { icon: '🚇', label: '교통', value: '뇌네역에서 버스. 보른홀름 지질학' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Naturama': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 DKK (~$17)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00 (수 ~20:00)' }, { icon: '📍', label: '위치', value: 'Dronningemaen 30, Svendborg, Denmark' }, { icon: '🚇', label: '교통', value: '스벤보르역 도보 10분. 푠 섬' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'National Museum of Natural History, Luxembourg': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '25 Rue Münster, Luxembourg City, Luxembourg' }, { icon: '🚇', label: '교통', value: '룩셈부르크 그룬트 지구' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'National Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500 LKR (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Republic Square, Colombo 07, Sri Lanka' }, { icon: '🚇', label: '교통', value: '콜롬보 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'National Natural History Museum of China': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (예약 필수)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '126 Tianqiao South Street, Beijing, China' }, { icon: '🚇', label: '교통', value: '지하철 8호선 Tianqiao역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'National Museum of Visual Arts': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Tomás Giribaldi 2283, Montevideo, Uruguay' }, { icon: '🚇', label: '교통', value: '몬테비데오 파르케 로도 공원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Niagara Falls History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $5 CAD' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '5810 Ferry St, Niagara Falls, ON, Canada' }, { icon: '🚇', label: '교통', value: '나이아가라 폭포 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Nova Scotia Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $6.75 CAD' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (수 ~20:00)' }, { icon: '📍', label: '위치', value: '1747 Summer St, Halifax, NS, Canada' }, { icon: '🚇', label: '교통', value: '핼리팩스 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'NTNU University Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 NOK (~$7.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Erling Skakkes gate 47a, Trondheim, Norway' }, { icon: '🚇', label: '교통', value: '트론헤임 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Natural Science Museum of Barcelona': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 매월 첫 일 무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-19:00, 일 10:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Plaça Leonardo da Vinci 4-5, Barcelona, Spain' }, { icon: '🚇', label: '교통', value: '메트로 4 El Maresme-Fòrum역. 헤르조그 & 드 뫼롱 건축' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Natur-Museum Luzern': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 8' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kasernenplatz 6, Lucerne, Switzerland' }, { icon: '🚇', label: '교통', value: '루체른역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
