const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'Kunsthistorisches Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 21€, 학생 18€. 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Maria-Theresien-Platz, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U2 Museumsquartier역 도보 3분. 합스부르크 세계적 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Kunsthaus Zürich': { vi: [{ icon: '🎫', label: '입장료', value: '성인 CHF 23 (~$26), 학생 CHF 18' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수·목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Heimplatz 1, Zürich, Switzerland' }, { icon: '🚇', label: '교통', value: '트램 3/5/8/9 Kunsthaus역. 치핀필드 신관 + 뷜레 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Kunstmuseum Basel': { vi: [{ icon: '🎫', label: '입장료', value: '성인 CHF 16 (~$18). 26세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'St. Alban-Graben 16, Basel, Switzerland' }, { icon: '🚇', label: '교통', value: '트램 2 Kunstmuseum역. 세계 최초 공공 미술관 (1661년)' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Kunsthal Rotterdam': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Museumpark, Westzeedijk 341, Rotterdam, Netherlands' }, { icon: '🚇', label: '교통', value: '메트로 D/E Eendrachtsplein역 도보 5분. OMA/렘 쿨하스 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunsthaus Graz': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lendkai 1, Graz, Austria' }, { icon: '🚇', label: '교통', value: '그라츠 중앙역에서 트램 1/3/6/7. 피터 쿡 블롭 건축' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'KunstHausWien': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€, 학생 11€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Untere Weißgerberstraße 13, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U4 Schwedenplatz에서 도보 10분. 훈데르트바서 설계' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunsthalle Mannheim': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€, 학생 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Friedrichsplatz 4, Mannheim, Germany' }, { icon: '🚇', label: '교통', value: '만하임 Hbf 트램 1/5 Kunsthalle역. 독일 현대미술' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Kunsthalle Praha': { vi: [{ icon: '🎫', label: '입장료', value: '성인 350 CZK (~$15)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-19:00 (수~금 ~21:00)' }, { icon: '📍', label: '위치', value: 'Klárov, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 A Malostranská역 도보 3분. 2022 개관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'KW Institute for Contemporary Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '수~월 11:00-19:00 (목 ~21:00). 화 휴관' }, { icon: '📍', label: '위치', value: 'Auguststraße 69, Berlin-Mitte, Germany' }, { icon: '🚇', label: '교통', value: 'U8 Rosenthaler Platz역 도보 5분. 베를린 비엔날레 본부' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kreeger Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-16:00 (사전 예약), 토 10:00-16:00' }, { icon: '📍', label: '위치', value: '2401 Foxhall Rd NW, Washington, D.C., USA' }, { icon: '🚇', label: '교통', value: '조지타운 인근 차량. 필립 존슨 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kiran Nadar Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:30-18:30. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Saket, New Delhi, India' }, { icon: '🚇', label: '교통', value: '델리 메트로 Yellow Line Saket역. 인도 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kirchner Museum Davos': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 12 (~$13.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (동절기 14:00-18:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Promenade 82, Davos, Switzerland' }, { icon: '🚇', label: '교통', value: '다보스역 도보 10분. 키르히너 표현주의' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'King John\'s Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 €13' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:30 (하계 ~18:00)' }, { icon: '📍', label: '위치', value: 'Nicholas Street, Limerick, Ireland' }, { icon: '🚇', label: '교통', value: '리머릭 시내 도보. 13세기 노르만 성' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunsten Museum of Modern Art Aalborg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 DKK (~$17)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kong Christians Allé 50, Aalborg, Denmark' }, { icon: '🚇', label: '교통', value: '올보르역 도보 15분. 알바 알토 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunstmuseum Bonn': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 수 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Helmut-Kohl-Allee 2, Bonn, Germany' }, { icon: '🚇', label: '교통', value: 'U16/63/66 Heussallee역. 뮤지엄마일' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunstmuseum Liechtenstein': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 15' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Städtle 32, Vaduz, Liechtenstein' }, { icon: '🚇', label: '교통', value: '파두츠 시내. 리히텐슈타인 국립 현대미술관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kunstmuseum Luzern': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 15' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~18:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Europaplatz 1, KKL, Lucerne, Switzerland' }, { icon: '🚇', label: '교통', value: '루체른역 도보 5분. 장 누벨 KKL 건물 내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunstmuseum Stuttgart': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€, 학생 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (금 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kleiner Schloßplatz 1, Stuttgart, Germany' }, { icon: '🚇', label: '교통', value: 'U5/U6/U7/U12 Schlossplatz역. 유리 큐브 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunstmuseum Wolfsburg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Hollerplatz 1, Wolfsburg, Germany' }, { icon: '🚇', label: '교통', value: '볼프스부르크역 도보 10분. VW 본사 인근' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunsthalle Bielefeld': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-18:00, 수 ~21:00, 토·일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Artur-Ladebeck-Str. 5, Bielefeld, Germany' }, { icon: '🚇', label: '교통', value: '빌레펠트역 트램 1번. 필립 존슨 건축' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kunsthalle Kiel': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Düsternbrooker Weg 1, Kiel, Germany' }, { icon: '🚇', label: '교통', value: '킬역 도보 15분. 킬 피오르드 해변' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunsthalle Krems': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Franz-Zeller-Platz 3, Krems, Austria' }, { icon: '🚇', label: '교통', value: '빈에서 기차 1시간. 바하우 계곡' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kunsthalle Würth': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Lange Str. 35, Schwäbisch Hall, Germany' }, { icon: '🚇', label: '교통', value: '슈베비쉬 할역 도보 15분. 뷔르트 기업 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kunsthalle Helsinki': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Nervanderinkatu 3, Helsinki, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키 중앙역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kunstnernes Hus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 60 NOK (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-17:00, 토·일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Wergelandsveien 17, Oslo, Norway' }, { icon: '🚇', label: '교통', value: 'T-bane Nationaltheatret역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'Kunst im Tunnel': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mannesmannufer 1b, Düsseldorf, Germany' }, { icon: '🚇', label: '교통', value: 'U70/U74 Tonhalle역 도보 3분. 라인강변 터널 갤러리' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Kunsthaus Baselland': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 9' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-18:00, 토·일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'St. Jakob-Str. 170, Muttenz, Switzerland' }, { icon: '🚇', label: '교통', value: '바젤 SBB에서 트램 14 Muttenz역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kurpfälzisches Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€. 일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Hauptstraße 97, Heidelberg, Germany' }, { icon: '🚇', label: '교통', value: '하이델베르크 구시가지 도보. 팔츠 역사·틸만 리멘슈나이더' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Käthe Kollwitz Museum Köln': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Neumarkt 18-24, Cologne, Germany' }, { icon: '🚇', label: '교통', value: 'U1/3/4/7/9 Neumarkt역 도보 1분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Others
    'Kitakyushu Museum of Natural History & Human History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 600엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '2-4-1 Higashida, Yahatahigashi-ku, Kitakyushu, Japan' }, { icon: '🚇', label: '교통', value: 'JR 스페이스월드역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Kitale Museum': { vi: [{ icon: '🎫', label: '입장료', value: '500 KES (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-18:00' }, { icon: '📍', label: '위치', value: 'Kitale, Trans-Nzoia County, Kenya' }, { icon: '🚇', label: '교통', value: '키탈레 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kansas City Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '3218 Gladstone Blvd, Kansas City, MO, USA' }, { icon: '🚇', label: '교통', value: '캔자스시티 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kendal Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '목~토 12:00-17:00' }, { icon: '📍', label: '위치', value: 'Station Road, Kendal, Cumbria, UK' }, { icon: '🚇', label: '교통', value: '켄달역 도보 10분. 레이크 디스트릭트 입구' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Istanbul Zoology Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Istanbul University, Fatih, Istanbul, Turkey' }, { icon: '🚇', label: '교통', value: '트램 T1 Beyazıt역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Jaggar Museum': { vi: [{ icon: '🎫', label: '입장료', value: '하와이 볼케이노스 국립공원 입장 $30/차량 포함' }, { icon: '🕐', label: '운영시간', value: '현재 지진 피해로 폐쇄' }, { icon: '📍', label: '위치', value: 'Hawaii Volcanoes National Park, HI, USA' }, { icon: '🚇', label: '교통', value: '힐로에서 차량 45분. 킬라우에아 화산' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Kharkiv museum of nature': { vi: [{ icon: '🎫', label: '입장료', value: '100 UAH (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Trinkler Street 8, Kharkiv, Ukraine' }, { icon: '🚇', label: '교통', value: '하르키우 메트로 Universytet역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kurashiki Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 150엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:15. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kurashiki, Okayama, Japan' }, { icon: '🚇', label: '교통', value: '쿠라시키역 도보 15분. 미관지구 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Jogja Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jl. Pekapalan 7, Yogyakarta, Indonesia' }, { icon: '🚇', label: '교통', value: '욕야카르타 크라톤 인근' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Kórnik Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 20 PLN (~$5)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kórnik, Greater Poland, Poland' }, { icon: '🚇', label: '교통', value: '포즈난에서 차량 20분. 네오고딕 성' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kortrijk 1302': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Begijnhofpark, Kortrijk, Belgium' }, { icon: '🚇', label: '교통', value: '코르트레이크역 도보 10분. 1302년 황금 박차 전투' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kunstmuseum Ravensburg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (목 ~19:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Burgstr. 9, Ravensburg, Germany' }, { icon: '🚇', label: '교통', value: '라벤스부르크역 도보 10분. 지속가능 건축상' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Jurassica Museum (institution)': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 9' }, { icon: '🕐', label: '운영시간', value: '화~일 14:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Route de Fontenais 21, Porrentruy, Switzerland' }, { icon: '🚇', label: '교통', value: '바젤에서 기차 Porrentruy역. 쥐라기 화석' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Keswick Museum and Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5.50' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Station Road, Keswick, Cumbria, UK' }, { icon: '🚇', label: '교통', value: '케직 시내. 레이크 디스트릭트' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kastrupgård Collection': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kastrupvej 399, Kastrup, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐 공항역에서 버스 5분' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
