const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Major museums
    'Field Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $30, 어린이 $21. 일리노이 주민 할인' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '1400 S DuSable Lake Shore Drive, Chicago, IL, USA' }, { icon: '🚇', label: '교통', value: 'CTA 버스 146 / Roosevelt역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '3-5시간' }] },
    'Fernbank Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25, 어린이 $18' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '767 Clifton Road NE, Atlanta, GA, USA' }, { icon: '🚇', label: '교통', value: 'MARTA Decatur역에서 버스' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Florida Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00, 일 13:00-17:00' }, { icon: '📍', label: '위치', value: '3215 Hull Road, Gainesville, FL, USA' }, { icon: '🚇', label: '교통', value: '게인즈빌 UF 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fabergé Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 18€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Sophienstraße 30, Baden-Baden, Germany' }, { icon: '🚇', label: '교통', value: '바덴바덴역에서 버스 201번' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Evita Museum - Eva Perón National Institute of Historical Research': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2,000 ARS (~$2)' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lafinur 2988, Palermo, Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: 'Subte D Plaza Italia역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Figge Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10, 학생 $6. 목 17-21시 무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00 (목 ~21:00), 일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '225 W 2nd St, Davenport, IA, USA' }, { icon: '🚇', label: '교통', value: '데이븐포트 다운타운' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Felix Nussbaum Haus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lotter Str. 2, Osnabrück, Germany' }, { icon: '🚇', label: '교통', value: '오스나브뤼크역 도보 15분. 다니엘 리베스킨트 설계' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Feodosia National Gallery I. K. Aivazovsky': { vi: [{ icon: '🎫', label: '입장료', value: '200 UAH (~$5)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Galereinaya 2, Feodosia, Crimea' }, { icon: '🚇', label: '교통', value: '페오도시아 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fernand Léger National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Chemin du Val de Pome, Biot, Alpes-Maritimes, France' }, { icon: '🚇', label: '교통', value: '앙티브에서 버스 10번. 니스에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fairbanks Museum and Planetarium': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $12, 어린이 $8' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00, 일 13:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1302 Main St, St. Johnsbury, VT, USA' }, { icon: '🚇', label: '교통', value: '버몬트 북동부. 보스턴에서 차량 3시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Finnish Air Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '6~8월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Tikkakoskentie 125, Jyväskylä, Finland' }, { icon: '🚇', label: '교통', value: '위바스킬라에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Finnish Forest Museum Lusto': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lustontie 1, Punkaharju, Finland' }, { icon: '🚇', label: '교통', value: '사본린나에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Firing Line: Cardiff Castle Museum of the Welsh Soldier': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (카디프 성 입장 별도 £14)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Cardiff Castle, Castle Street, Cardiff, Wales, UK' }, { icon: '🚇', label: '교통', value: '카디프 센트럴역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fleet Air Arm Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'HMAS Albatross, Nowra, NSW, Australia' }, { icon: '🚇', label: '교통', value: '시드니에서 차량 2.5시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Flore submarine, Submarine Discovery Centre': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€, 어린이 6€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:30 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Lorient, Morbihan, France' }, { icon: '🚇', label: '교통', value: '로리앙역에서 버스. 잠수함 기지 K-III 인근' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Explosion Museum of Naval Firepower': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £12, 어린이 £6' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Heritage Way, Gosport, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '포츠머스에서 페리 Gosport 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Estonian Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€, 학생 3€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Lai 29A, Tallinn, Estonia' }, { icon: '🚇', label: '교통', value: '탈린 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Forchtenstein Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Melinda-Esterházy-Platz 1, Forchtenstein, Austria' }, { icon: '🚇', label: '교통', value: '비엔나에서 차량 1시간. 에스터하지 가문 성' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Fort series (major ones)
    'Fort Siloso': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Sentosa Island, Singapore' }, { icon: '🚇', label: '교통', value: 'Sentosa Express Beach Station 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Henry': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20 CAD, 어린이 $13.50' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '1 Fort Henry Drive, Kingston, ON, Canada' }, { icon: '🚇', label: '교통', value: '킹스턴 다운타운에서 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Fort York': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $14 CAD, 어린이 $8' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (1~3월 토·일만)' }, { icon: '📍', label: '위치', value: '250 Fort York Blvd, Toronto, ON, Canada' }, { icon: '🚇', label: '교통', value: 'Bathurst 스트릿카 / Exhibition 정류장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Douaumont': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Douaumont, Meuse, Verdun, France' }, { icon: '🚇', label: '교통', value: '베르됭에서 차량 20분. 1차대전 전장' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Fort Eben-Emael': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '3~11월 토·일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Rue du Fort 40, Eben-Emael, Belgium' }, { icon: '🚇', label: '교통', value: '리에주에서 차량 30분. 2차대전 요새' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort de Mutzig': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '3~11월 토·일 14:00 가이드 투어' }, { icon: '📍', label: '위치', value: 'Mutzig, Bas-Rhin, Alsace, France' }, { icon: '🚇', label: '교통', value: '스트라스부르에서 기차 30분. 독일 제국 최대 요새' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort de Loncin': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '4~10월 토·일·공휴일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Rue des Héros 15bis, Ans, Liège, Belgium' }, { icon: '🚇', label: '교통', value: '리에주에서 버스 20분. 1차대전 추모지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Pompelle Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Puisieulx, Marne, France' }, { icon: '🚇', label: '교통', value: '랭스에서 차량 10분. 1차대전 박물관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Chambly': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $4 CAD' }, { icon: '🕐', label: '운영시간', value: '6~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '2 Rue de Richelieu, Chambly, QC, Canada' }, { icon: '🚇', label: '교통', value: '몬트리올에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Denison': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD$35 (투어 포함)' }, { icon: '🕐', label: '운영시간', value: '가이드 투어 예약제' }, { icon: '📍', label: '위치', value: 'Sydney Harbour, NSW, Australia' }, { icon: '🚇', label: '교통', value: 'Circular Quay에서 보트' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort George': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $17.60 CAD' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Niagara-on-the-Lake, ON, Canada' }, { icon: '🚇', label: '교통', value: '나이아가라 폭포에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort Nelson': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Portsdown Hill Road, Fareham, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '포츠머스에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort Rodd Hill National Historic Site': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $4.25 CAD' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '603 Fort Rodd Hill Rd, Colwood, BC, Canada' }, { icon: '🚇', label: '교통', value: '빅토리아에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort VII concentration camp': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'ul. Polska 28, Poznań, Poland' }, { icon: '🚇', label: '교통', value: '포즈난 시내에서 트램 / 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Amherst': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £10, 어린이 £5' }, { icon: '🕐', label: '운영시간', value: '주말 가이드 투어 (예약제)' }, { icon: '📍', label: '위치', value: 'Chatham, Medway, Kent, UK' }, { icon: '🚇', label: '교통', value: '채텀역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort de Joux': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7.50€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'La Cluse-et-Mijoux, Doubs, France' }, { icon: '🚇', label: '교통', value: '퐁타를리에에서 차량 5분. 투생 루베르튀르 수감지' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort de Condé-sur-Aisne': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '4~10월 토·일 14:00-18:00' }, { icon: '📍', label: '위치', value: 'Chivres-Val, Aisne, France' }, { icon: '🚇', label: '교통', value: '수아송에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort de Bondues': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '수·일 10:00-12:00, 14:30-17:30' }, { icon: '📍', label: '위치', value: 'Bondues, Nord, France' }, { icon: '🚇', label: '교통', value: '릴에서 차량 15분. 레지스탕스 기념관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Rotterdam': { vi: [{ icon: '🎫', label: '입장료', value: '10,000 IDR (~$0.60)' }, { icon: '🕐', label: '운영시간', value: '화~일 08:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jl. Ujung Pandang, Makassar, Sulawesi, Indonesia' }, { icon: '🚇', label: '교통', value: '마카사르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort San Pedro': { vi: [{ icon: '🎫', label: '입장료', value: '100 PHP (~$2)' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-19:00' }, { icon: '📍', label: '위치', value: 'A. Pigafetta Street, Cebu City, Philippines' }, { icon: '🚇', label: '교통', value: '세부 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Fort Vredeburg': { vi: [{ icon: '🎫', label: '입장료', value: '10,000 IDR (~$0.60)' }, { icon: '🕐', label: '운영시간', value: '화~일 07:30-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jl. Jenderal Ahmad Yani 6, Yogyakarta, Indonesia' }, { icon: '🚇', label: '교통', value: '족자카르타 말리오보로 거리 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Forte di Gavi': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Gavi, Alessandria, Italy' }, { icon: '🚇', label: '교통', value: '알레산드리아에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Heldsberg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12 CHF' }, { icon: '🕐', label: '운영시간', value: '3~11월 매월 개방일 (웹사이트 확인)' }, { icon: '📍', label: '위치', value: 'St. Margrethen, St. Gallen, Switzerland' }, { icon: '🚇', label: '교통', value: '장크트마르그레텐역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Reuenthal': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12 CHF' }, { icon: '🕐', label: '운영시간', value: '4~10월 매월 개방일' }, { icon: '📍', label: '위치', value: 'Full-Reuenthal, Aargau, Switzerland' }, { icon: '🚇', label: '교통', value: '바젤에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Ebersberg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10 CHF' }, { icon: '🕐', label: '운영시간', value: '5~10월 예약제 투어' }, { icon: '📍', label: '위치', value: 'Berg am Irchel, Zürich, Switzerland' }, { icon: '🚇', label: '교통', value: '취리히에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Napoleon': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Vuurtorenweg, Ostend, Belgium' }, { icon: '🚇', label: '교통', value: '오스텐드역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'For Freedom Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Ramskapellestraat 91, Knokke-Heist, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼헤에서 차량 20분. 2차대전 해방 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Federseemuseum Bad Buchau': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'August-Gröber-Platz 2, Bad Buchau, Germany' }, { icon: '🚇', label: '교통', value: '울름에서 차량 45분. 신석기 수상가옥 유적' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fondazione Scienza e Tecnica': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Giusti 29, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 산타크로체 인근 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Forestry Museum of Lapland': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '6~8월 화~일 12:00-18:00' }, { icon: '📍', label: '위치', value: 'Metsäruusuntie 4, Rovaniemi, Finland' }, { icon: '🚇', label: '교통', value: '로바니에미 시내에서 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Sumter Visitor Education Center': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (센터). 보트 투어 성인 $30' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '340 Concord Street, Charleston, SC, USA' }, { icon: '🚇', label: '교통', value: '찰스턴 시내' }, { icon: '⏱️', label: '관람시간', value: '2.5시간 (보트+섬 포함)' }] },
    'Fort Morgan': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7, 어린이 $4' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-17:00' }, { icon: '📍', label: '위치', value: '51 Hwy 180 W, Gulf Shores, AL, USA' }, { icon: '🚇', label: '교통', value: '모빌에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Citadel Hill': { vi: [{ icon: '🎫', label: '입장료', value: '$11.70 CAD (6~9월)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Halifax, NS, Canada' }, { icon: '🚇', label: '교통', value: '핼리팩스 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Wellington': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $4 CAD' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '370 Vankoughnet St, Prescott, ON, Canada' }, { icon: '🚇', label: '교통', value: '오타와에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Brockhurst': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (가이드 투어 예약)' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Gunner\'s Way, Gosport, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '고스포트 시내에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Griswold': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '57 Fort Street, Groton, CT, USA' }, { icon: '🚇', label: '교통', value: '뉴런던에서 도보 / Amtrak New London역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Roupel': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 개방 (야외 기념관)' }, { icon: '📍', label: '위치', value: 'Sintiki, Central Macedonia, Greece' }, { icon: '🚇', label: '교통', value: '테살로니키에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Ingall': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7 CAD' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Témiscouata-sur-le-Lac, QC, Canada' }, { icon: '🚇', label: '교통', value: '리비에르뒤루에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Lennox': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7.90 CAD (페리 포함)' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: "Saint-Paul-de-l'Île-aux-Noix, QC, Canada" }, { icon: '🚇', label: '교통', value: '몬트리올에서 차량 1시간. 리슐리외 강 섬 요새' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort Malden': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $4 CAD' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '100 Laird Ave, Amherstburg, ON, Canada' }, { icon: '🚇', label: '교통', value: '윈저에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Eduardo Ribeiro House Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Manaus, Amazonas, Brazil' }, { icon: '🚇', label: '교통', value: '마나우스 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Estonian Military Academy museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00 (예약 권장)' }, { icon: '📍', label: '위치', value: 'Riia 12, Tartu, Estonia' }, { icon: '🚇', label: '교통', value: '타르투 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Florianópolis Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 13:00-17:00' }, { icon: '📍', label: '위치', value: 'Florianópolis, Santa Catarina, Brazil' }, { icon: '🚇', label: '교통', value: '플로리아노폴리스 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Florida Keys Eco-Discovery Center': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-16:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '35 E Quay Road, Key West, FL, USA' }, { icon: '🚇', label: '교통', value: '키웨스트 항구 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fait Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-18:00' }, { icon: '📍', label: '위치', value: 'Ve Vaňkovce 2, Brno, Czech Republic' }, { icon: '🚇', label: '교통', value: '브르노 중앙역 도보 5분 (Vaňkovka 쇼핑센터)' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'CFS Carp': { vi: [{ icon: '🎫', label: '입장료', value: '$20 CAD (가이드 투어)' }, { icon: '🕐', label: '운영시간', value: '예약제 투어 (주말)' }, { icon: '📍', label: '위치', value: 'Carp, Ottawa, ON, Canada' }, { icon: '🚇', label: '교통', value: '오타와에서 차량 30분. 냉전 핵 벙커' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort de Guentrange': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '4~10월 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Thionville, Moselle, France' }, { icon: '🚇', label: '교통', value: '메츠에서 기차 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Anne': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외). 투어 $4 CAD' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 09:00-17:30' }, { icon: '📍', label: '위치', value: 'Annapolis Royal, NS, Canada' }, { icon: '🚇', label: '교통', value: '핼리팩스에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        let r;
        if (info.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, info.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
