const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★ World-class museums
    'Hamburger Kunsthalle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€, 학생 8€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Glockengießerwall 5, Hamburg, Germany' }, { icon: '🚇', label: '교통', value: 'Hamburg Hbf 도보 3분. 독일 최고 미술관 중 하나' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Hayward Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '전시별 상이 (£15~20)' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-19:00 (목·금 ~21:00)' }, { icon: '📍', label: '위치', value: 'Southbank Centre, Belvedere Road, London, UK' }, { icon: '🚇', label: '교통', value: 'Northern/Bakerloo Waterloo역 도보 5분. 사우스뱅크' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Hirshhorn Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:30' }, { icon: '📍', label: '위치', value: 'Independence Ave SW, Washington, D.C., USA' }, { icon: '🚇', label: '교통', value: '메트로 L\'Enfant Plaza역 도보 5분. 스미스소니언 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Istanbul Modern': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 TRY (~$4). 목 무료 (터키 국민)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kılıçali Paşa, Beyoğlu, Istanbul, Turkey' }, { icon: '🚇', label: '교통', value: '트램 T1 Tophane역 도보 3분. 렌초 피아노 신관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Hong Kong Museum of History': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '월·수~금 10:00-18:00, 토·일 10:00-19:00. 화 휴관' }, { icon: '📍', label: '위치', value: '100 Chatham Road South, Tsim Sha Tsui, Hong Kong' }, { icon: '🚇', label: '교통', value: 'MTR East Tsim Sha Tsui역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Honolulu Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20. 매월 첫째 수·셋째 일 무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '900 S Beretania St, Honolulu, HI, USA' }, { icon: '🚇', label: '교통', value: '와이키키에서 버스 2번 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'House of European History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월 13:00-18:00, 화~금 09:00-18:00, 토·일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Rue Belliard 135, Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '메트로 1/5 Maalbeek/Maelbeek역 도보 5분. EU 의회 인근' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Hugh Lane Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~목 09:45-18:00, 금 09:45-17:00, 토 10:00-17:00, 일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Charlemont House, Parnell Square North, Dublin, Ireland' }, { icon: '🚇', label: '교통', value: 'Luas Green Line Parnell 도보 2분. 프랜시스 베이컨 스튜디오' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Hungarian Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2,600 HUF (~$7.50)' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Ludovika tér 2, Budapest, Hungary' }, { icon: '🚇', label: '교통', value: '메트로 M3 Klinikák역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Hunterian Museum and Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 11:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'University of Glasgow, Glasgow, UK' }, { icon: '🚇', label: '교통', value: '지하철 Hillhead역 도보 3분. 스코틀랜드 최고 대학 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'ICA Miami': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 12:00-18:00 (목 ~21:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: '61 NE 41st Street, Miami Design District, FL, USA' }, { icon: '🚇', label: '교통', value: '미아미 디자인 디스트릭트. Aranguren & Gallegos 건축' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Imperial Treasury': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€' }, { icon: '🕐', label: '운영시간', value: '수~월 09:00-17:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Hofburg, Schweizerhof, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U3 Herrengasse역 도보 3분. 합스부르크 왕관/보물' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'In Flanders Fields Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (11~3월 화~일). 월 휴관 (겨울)' }, { icon: '📍', label: '위치', value: 'Lakenhallen, Grote Markt 34, Ypres, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼셀에서 기차 Ieper역 2시간. 1차대전 추모' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'International Center of Photography': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $18, 학생 $12' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-19:00 (목 ~21:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: '79 Essex Street, Manhattan, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 F/J/M/Z Essex St역 도보 1분. 로어 이스트사이드' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ipiranga Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R$30 (~$6)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parque da Independência, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 1/2/3환승 Alto do Ipiranga역. 브라질 독립 선언지' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Irish Museum of Modern Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 11:30-17:30, 토 10:00-17:30, 일 12:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Royal Hospital Kilmainham, Dublin, Ireland' }, { icon: '🚇', label: '교통', value: 'Luas Red Line Heuston → 도보 5분. 아일랜드 대표 현대미술관' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Heeresgeschichtliches Museum
    'Heeresgeschichtliches Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€, 학생 5€. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Arsenal, Ghegastraße, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1 Südtiroler Platz역 도보 10분. 오스트리아 군사사 (프란츠 페르디난트 암살 차량)' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Haus der Geschichte': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Museumsmeile, Willy-Brandt-Allee 14, Bonn, Germany' }, { icon: '🚇', label: '교통', value: 'U16/63/66 Museum König역 / Heussallee역. 전후 독일사' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Haus der Weimarer Republik': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Theaterplatz 4, Weimar, Germany' }, { icon: '🚇', label: '교통', value: '바이마르역 도보 15분. 바이마르 공화국 역사' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Hispanic Society of America': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '목~일 12:00-18:00. 월~수 휴관' }, { icon: '📍', label: '위치', value: '613 W 155th St, Manhattan, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 1 155th St역. 고야·엘 그레코·벨라스케스 소장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Historium': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Markt 1, Bruges, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼헤 시장광장. VR 중세 체험' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Historical Museum of the Palatinate': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Domplatz, Speyer, Germany' }, { icon: '🚇', label: '교통', value: '슈파이어역 도보 15분. 팔츠 역사·대성당 보물' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Historical Museum Frankfurt': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€. 매월 마지막 토 무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Saalhof 1, Frankfurt, Germany' }, { icon: '🚇', label: '교통', value: 'U4/5 Dom/Römer역 도보 2분. 프랑크푸르트 구시가지' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Historiengewölbe mit Staatsverlies': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3.50€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Rathaus, Rothenburg ob der Tauber, Germany' }, { icon: '🚇', label: '교통', value: '로텐부르크 시청 지하. 중세 감옥 체험' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Historiecenter Dybbøl Banke': { vi: [{ icon: '🎫', label: '입장료', value: '성인 110 DKK (~$16)' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Dybbøl Banke 16, Sønderborg, Denmark' }, { icon: '🚇', label: '교통', value: '쇤더보르 시내 차량 5분. 1864년 전쟁' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Ho-Am Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6,000원' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '경기도 용인시 처인구 포곡읍 에버랜드로 562번길 38' }, { icon: '🚇', label: '교통', value: '에버랜드 인근. 삼성 이병철 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Henri Cartier-Bresson Foundation
    'Henri Cartier-Bresson Foundation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '79 Rue des Archives, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 11 Arts et Métiers역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Henry Moore Foundation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £14.50' }, { icon: '🕐', label: '운영시간', value: '4~10월 수~일 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Perry Green, Hertfordshire, UK' }, { icon: '🚇', label: '교통', value: '런던에서 차량 1시간. 무어의 스튜디오+야외 조각' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Henie-Onstad Art Centre': { vi: [{ icon: '🎫', label: '입장료', value: '성인 130 NOK (~$12)' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-17:00 (목 ~19:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Sonja Henies vei 31, Høvikodden, Norway' }, { icon: '🚇', label: '교통', value: '오슬로에서 버스 151/160번 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Hardwick Hall': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £18 (NT 회원 무료)' }, { icon: '🕐', label: '운영시간', value: '3~10월 수~일 11:00-16:30' }, { icon: '📍', label: '위치', value: 'Doe Lea, Chesterfield, Derbyshire, UK' }, { icon: '🚇', label: '교통', value: '체스터필드에서 차량 10분. 엘리자베스 시대 저택' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Hiroshima City Museum of Contemporary Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 370엔' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1-1 Hijiyama-kōen, Minami-ku, Hiroshima, Japan' }, { icon: '🚇', label: '교통', value: '히로시마역에서 버스 비지야마 공원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'High Desert Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20, 어린이 $12' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '59800 S Hwy 97, Bend, OR, USA' }, { icon: '🚇', label: '교통', value: '벤드에서 남쪽 차량 10분. 사막 생태 박물관' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Ipswich Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'High Street, Ipswich, Suffolk, UK' }, { icon: '🚇', label: '교통', value: '입스위치역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Israel Defense Forces History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 08:30-15:30. 금·토 휴관' }, { icon: '📍', label: '위치', value: 'Hatayasim St, Tel Aviv, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Historial Charles de Gaulle': { vi: [{ icon: '🎫', label: '입장료', value: '앵발리드 입장 15€ 포함' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (4~10월 ~18:00). 매월 첫째 월 휴관' }, { icon: '📍', label: '위치', value: 'Les Invalides, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 8/13 Invalides역' }, { icon: '⏱️', label: '관람시간', value: '앵발리드 전체 2-3시간 중 일부' }] },
    'Hocken Collections': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-17:00, 토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'University of Otago, Dunedin, New Zealand' }, { icon: '🚇', label: '교통', value: '더니든 대학 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Helsinki University Museum Flame': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토~일 11:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Yliopistonkatu 4, Helsinki, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키 중앙역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Inatura': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Jahngasse 9, Dornbirn, Austria' }, { icon: '🚇', label: '교통', value: '도른비른역 도보 10분. 인터랙티브 자연사' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Horim Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5,000원' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '서울시 관악구 (신림동)' }, { icon: '🚇', label: '교통', value: '지하철 2호선 신림역 도보 15분. 한국 고미술 전문' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Historical Museum of Bosnia and Herzegovina': { vi: [{ icon: '🎫', label: '입장료', value: '6 KM (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-14:00, 토 10:00-13:00' }, { icon: '📍', label: '위치', value: 'Zmaja od Bosne 5, Sarajevo, Bosnia' }, { icon: '🚇', label: '교통', value: '사라예보 트램 Skenderija역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gjirokastra Cold War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '200 ALL (~$2)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'Gjirokastër Castle, Albania' }, { icon: '🚇', label: '교통', value: '티라나에서 버스 4시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Iraq Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 09:00-14:00' }, { icon: '📍', label: '위치', value: 'Bab al-Muadham, Baghdad, Iraq' }, { icon: '🚇', label: '교통', value: '바그다드 대학교 캠퍼스 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'History of the Inquisition Museum': { vi: [{ icon: '🎫', label: '입장료', value: 'R$10 (~$2)' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Belo Horizonte, Minas Gerais, Brazil' }, { icon: '🚇', label: '교통', value: '벨루오리존치 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ishikawa Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 360엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 목 휴관' }, { icon: '📍', label: '위치', value: 'Kanazawa, Ishikawa, Japan' }, { icon: '🚇', label: '교통', value: '가나자와역에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ibaraki Nature Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 740엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Bando, Ibaraki, Japan' }, { icon: '🚇', label: '교통', value: '토쿄에서 츠쿠바 익스프레스+버스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
