const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'MMCA Seoul': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4,000원. 매월 마지막 수 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수·토 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '서울 종로구 삼청로 30' }, { icon: '🚇', label: '교통', value: '지하철 3호선 안국역 1번 출구 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'MOCA Los Angeles': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '목~일 11:00-17:00 (목 ~20:00). 월~수 휴관' }, { icon: '📍', label: '위치', value: '250 S Grand Ave, Los Angeles, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro B/D Civic Center역 도보 5분. 이소자키 아라타 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MOCA Taipei': { vi: [{ icon: '🎫', label: '입장료', value: '성인 50 TWD (~$1.60)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: '39 Chang\'an West Road, Datong, Taipei, Taiwan' }, { icon: '🚇', label: '교통', value: 'MRT 중산역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Moderna Museet': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 150 SEK (~$14)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (화·금 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Exercisplan 4, Skeppsholmen, Stockholm, Sweden' }, { icon: '🚇', label: '교통', value: 'T-bana Kungsträdgården역 도보 10분. 스웨덴 국립현대미술관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'MONA': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD 39 (~$25). 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: '655 Main Road, Berriedale, Hobart, Tasmania, Australia' }, { icon: '🚇', label: '교통', value: '호바트에서 페리 25분 또는 차량 15분. 데이비드 월시의 반(反)미술관' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'MUMOK': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€, 학생 9€. 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '월 14:00-19:00, 화~일 10:00-19:00 (목 ~21:00)' }, { icon: '📍', label: '위치', value: 'Museumsplatz 1, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U2 Museumsquartier역 도보 2분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Mori Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2,000엔 (전망대 포함)' }, { icon: '🕐', label: '운영시간', value: '월·수~일 10:00-22:00, 화 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Roppongi Hills Mori Tower 53F, Tokyo, Japan' }, { icon: '🚇', label: '교통', value: '메트로 히비야선 롯폰기역 도보 3분. 도쿄 스카이라인 전망' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'MUSE': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13€, 학생 9€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Corso del Lavoro e della Scienza 3, Trento, Italy' }, { icon: '🚇', label: '교통', value: '트렌토역 도보 20분. 렌초 피아노 건축 과학박물관' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    "Musée d'Art Moderne de Paris": { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 유료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~21:30). 월 휴관' }, { icon: '📍', label: '위치', value: '11 Avenue du Président Wilson, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 9 Iéna역 / RER C Pont de l\'Alma역' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Musée Carnavalet': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '23 Rue de Sévigné, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 1 Saint-Paul역 도보 3분. 파리시 역사 박물관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Musée de Cluny': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-18:15. 월 휴관' }, { icon: '📍', label: '위치', value: '28 Rue du Sommerard, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 10 Cluny–La Sorbonne역. 중세 미술 + 일각수 태피스트리' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Musée du quai Branly': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:30-19:00 (목 ~22:00). 월 휴관' }, { icon: '📍', label: '위치', value: '37 Quai Branly, Paris, France' }, { icon: '🚇', label: '교통', value: 'RER C Pont de l\'Alma역 / 메트로 9 Alma-Marceau역. 장 누벨 건축' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Musée Gustave Moreau': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-12:45, 14:00-17:15. 화 휴관' }, { icon: '📍', label: '위치', value: '14 Rue de La Rochefoucauld, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 12 Trinité역 도보 3분. 상징주의 화가 아틀리에' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "Musée d'Art et d'Histoire du Judaïsme": { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-18:00, 토·일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '71 Rue du Temple, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 11 Rambuteau역 도보 3분. 마레 지구' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Musée des Beaux-Arts de Caen': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-12:30, 14:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Le Château, Caen, France' }, { icon: '🚇', label: '교통', value: '캉역 트램 T1/T2 Château역. 노르망디 성 안' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Musée des beaux-arts de Marseille': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Palais Longchamp, Marseille, France' }, { icon: '🚇', label: '교통', value: '메트로 1 Cinq-Avenues Longchamp역. 롱샹 궁전' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Musée des Beaux-Arts de Tours': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '수~월 09:00-12:45, 14:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '18 Place François Sicard, Tours, France' }, { icon: '🚇', label: '교통', value: '투르역 트램 A Place Jean Jaurès역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "musée des impressionnismes Giverny": { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '4~11월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: '99 Rue Claude Monet, Giverny, France' }, { icon: '🚇', label: '교통', value: '파리에서 기차 Vernon역+셔틀. 모네 정원 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Blindés': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-18:00' }, { icon: '📍', label: '위치', value: '1043 Rte de Fontevraud, Saumur, France' }, { icon: '🚇', label: '교통', value: '소뮈르역 차량 5분. 세계 최대 전차 박물관 중 하나' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Musée Ariana': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Avenue de la Paix 10, Geneva, Switzerland' }, { icon: '🚇', label: '교통', value: '버스 8/F/V/Z Appia역. UN 본부 인근. 도자기·유리 전문' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée Fesch': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (하계 ~18:00). 월 휴관 (동절기)' }, { icon: '📍', label: '위치', value: '50 Rue du Cardinal Fesch, Ajaccio, Corsica, France' }, { icon: '🚇', label: '교통', value: '아작시오 시내 도보. 이탈리아 회화 프랑스 2위 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Other major
    "Musée d'art contemporain de Montréal": { vi: [{ icon: '🎫', label: '입장료', value: '성인 $12 CAD' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '185 Rue Sainte-Catherine O, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 Place-des-Arts역 도보 1분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Moravian Gallery in Brno': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200 CZK (~$9)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00 (목 ~19:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Husova 18, Brno, Czech Republic' }, { icon: '🚇', label: '교통', value: '브르노역 트램 4/9 Moravské náměstí역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Modern Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 40 HRK (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-19:00, 토·일 11:00-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Andrije Hebranga 1, Zagreb, Croatia' }, { icon: '🚇', label: '교통', value: '자그레브역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Mobile Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '4850 Museum Dr, Mobile, AL, USA' }, { icon: '🚇', label: '교통', value: '모빌 시내. Langan Park 내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Mons Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Boulevard Dolez 51, Mons, Belgium' }, { icon: '🚇', label: '교통', value: '몽스역 도보 15분. 1/2차 세계대전 기념' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Montréal Insectarium': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $23 CAD (식물원+곤충관 포함)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: '4581 Rue Sherbrooke E, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 Pie-IX역 도보 5분. 크루테 건축 2022 리뉴얼' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Moscow Paleontological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '400 RUB (~$4.50)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Profsoyuznaya 123, Moscow, Russia' }, { icon: '🚇', label: '교통', value: '메트로 Tyoply Stan역 도보 10분. 공룡 화석' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    "Musée de l'ordre de la Libération": { vi: [{ icon: '🎫', label: '입장료', value: '앵발리드 입장 15€ 포함' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Hôtel des Invalides, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 8/13 Invalides역' }, { icon: '⏱️', label: '관람시간', value: '앵발리드 전체 2-3시간 중 일부' }] },
    'Musée de la civilisation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $22 CAD. 수 17시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관 (하계 매일)' }, { icon: '📍', label: '위치', value: '85 Rue Dalhousie, Quebec City, QC, Canada' }, { icon: '🚇', label: '교통', value: '퀘벡 올드타운 도보. 모셰 사프디 건축' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Musée de la Cour d\'Or': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '수~월 09:00-12:30, 13:30-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: '2 Rue du Haut Poirier, Metz, France' }, { icon: '🚇', label: '교통', value: '메스역 도보 10분. 갈로-로마 유물' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Musée de la Résistance et de la Déportation à Grenoble": { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월·수~일 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '14 Rue Hébert, Grenoble, France' }, { icon: '🚇', label: '교통', value: '트램 A Verdun역 도보 5분. 프랑스 레지스탕스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "Mu.ZEE - Kunstmuseum aan Zee": { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Romestraat 11, Ostend, Belgium' }, { icon: '🚇', label: '교통', value: '오스텐드역 도보 10분. 벨기에 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Mother Armenia Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Victory Park, Yerevan, Armenia' }, { icon: '🚇', label: '교통', value: '예레반 캐스케이드에서 도보 15분. 어머니 아르메니아 동상' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'MOMus–Museum of Modern Art–Costakis Collection': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kolokotroni 21, Thessaloniki, Greece' }, { icon: '🚇', label: '교통', value: '테살로니키 시내. 러시아 아방가르드 코스타키스 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Tournai': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3.50€' }, { icon: '🕐', label: '운영시간', value: '수~월 09:30-12:30, 14:00-17:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Enclos Saint-Martin 3, Tournai, Belgium' }, { icon: '🚇', label: '교통', value: '투르네역 도보 10분. 빅토르 오르타 건축 유일 벨기에 외 미술관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Müritzeum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-19:00 (동절기 ~18:00)' }, { icon: '📍', label: '위치', value: 'Zur Steinmole 1, Waren, Germany' }, { icon: '🚇', label: '교통', value: '바렌역 도보 10분. 뮈리츠 호수 자연사' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Mjellby Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 SEK (~$7.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mjellby, Halmstad, Sweden' }, { icon: '🚇', label: '교통', value: '할름스타드에서 차량 10분. 할름스타드 그룹' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Mining Museum Prettau': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 09:30-16:30' }, { icon: '📍', label: '위치', value: 'Prettau, South Tyrol, Italy' }, { icon: '🚇', label: '교통', value: '브루니코에서 차량 30분. 구리 광산 체험' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Montevecchio Mining Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Arbus, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '칼리아리에서 차량 1.5시간. 사르디니아 광산 유산' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Miyanomori International Museum of Art, Sapporo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 600엔' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Miyanomori, Sapporo, Hokkaido, Japan' }, { icon: '🚇', label: '교통', value: '삿포로 시전차 마루야마코엔역 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée Dobrée': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '18 Rue Voltaire, Nantes, France' }, { icon: '🚇', label: '교통', value: '트램 1 Médiathèque역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
