const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Smaller/obscure galleries - quick entries
    '26th Field Artillery Regiment, Royal Canadian Artillery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Brandon, MB, Canada' }, { icon: '🚇', label: '교통', value: '브랜던 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    '2nd Floor Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Moncton, NB, Canada' }, { icon: '🚇', label: '교통', value: '멍턴 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Albertusstraße 18': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 개방' }, { icon: '📍', label: '위치', value: 'Cologne, Germany' }, { icon: '🚇', label: '교통', value: '쾰른 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Alfalibra Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-19:00' }, { icon: '📍', label: '위치', value: 'Paris 3rd, France' }, { icon: '🚇', label: '교통', value: '메트로 Arts et Métiers역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Altes Schlachthaus': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 개방' }, { icon: '📍', label: '위치', value: 'Mosbach, Germany' }, { icon: '🚇', label: '교통', value: '모스바흐역 도보' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Altes Theater': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 개방' }, { icon: '📍', label: '위치', value: 'Ravensburg, Germany' }, { icon: '🚇', label: '교통', value: '라벤스부르크역 도보' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Alton Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Melbourne, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '멜버른 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Amazon Navigation Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Belém, Pará, Brazil' }, { icon: '🚇', label: '교통', value: '벨렝 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Amtshaus': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중' }, { icon: '📍', label: '위치', value: 'Grünsfeld, Germany' }, { icon: '🚇', label: '교통', value: '뷔르츠부르크에서 차량' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'An der Schanz 1a': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중' }, { icon: '📍', label: '위치', value: 'Cologne, Germany' }, { icon: '🚇', label: '교통', value: '쾰른 Zoo/Flora역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    // Major museums
    'Centre Pompidou': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€. 매월 첫째 일 무료. 26세 이하 EU 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 11:00-21:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place Georges-Pompidou, Paris 4th, France' }, { icon: '🚇', label: '교통', value: '메트로 Rambuteau / Hôtel de Ville역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }], website: 'https://www.centrepompidou.fr/' },
    'Churchill War Rooms': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £28, 어린이 £14. 온라인 예약 필수' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-18:00' }, { icon: '📍', label: '위치', value: 'Clive Steps, King Charles Street, London, UK' }, { icon: '🚇', label: '교통', value: 'Westminster역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Bergenhus Fortress': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외). 홀 입장 80 NOK' }, { icon: '🕐', label: '운영시간', value: '매일 06:00-23:00 (야외)' }, { icon: '📍', label: '위치', value: 'Bergen, Norway' }, { icon: '🚇', label: '교통', value: '베르겐역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Berlinische Galerie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Alte Jakobstraße 124-128, Berlin' }, { icon: '🚇', label: '교통', value: 'U6 Kochstraße역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Bourse de Commerce': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€. 26세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '월·수~일 11:00-19:00 (금 ~21:00). 화 휴관' }, { icon: '📍', label: '위치', value: '2 Rue de Viarmes, Paris 1st, France' }, { icon: '🚇', label: '교통', value: '메트로 Les Halles / Louvre-Rivoli역' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }], website: 'https://www.pinaultcollection.com/boursedecommerce/' },
    'Botswana National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-18:00, 토 09:00-17:00, 일 14:00-17:00' }, { icon: '📍', label: '위치', value: '331 Independence Avenue, Gaborone, Botswana' }, { icon: '🚇', label: '교통', value: '가보로네 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Bunker Hill Monument': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Monument Square, Charlestown, Boston, MA' }, { icon: '🚇', label: '교통', value: 'Orange Line Community College역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Boston Navy Yard': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Charlestown Navy Yard, Boston, MA' }, { icon: '🚇', label: '교통', value: '이너하버 페리 / Community College역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Belize Archaeology Museum': { vi: [{ icon: '🎫', label: '입장료', value: 'BZ$10 (~$5)' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-16:30' }, { icon: '📍', label: '위치', value: 'Belmopan, Belize' }, { icon: '🚇', label: '교통', value: '벨모판 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bundeswehr Museum of German Defense Technology': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Am Rhein 1, Koblenz, Germany' }, { icon: '🚇', label: '교통', value: '코블렌츠역에서 버스 / 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Certosa di Padula': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '수~월 09:00-19:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Padula, Salerno, Italy' }, { icon: '🚇', label: '교통', value: '살레르노에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Certosa di San Giacomo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Capri, Naples, Italy' }, { icon: '🚇', label: '교통', value: '카프리 마리나 그란데에서 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Changi Chapel and Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: '1000 Upper Changi Road North, Singapore' }, { icon: '🚇', label: '교통', value: 'MRT Expo역에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Charles M. Schulz Museum and Research Center': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $14, 학생 $8' }, { icon: '🕐', label: '운영시간', value: '월·수~금 11:00-17:00, 토~일 10:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: '2301 Hardies Lane, Santa Rosa, CA, USA' }, { icon: '🚇', label: '교통', value: '샌프란시스코에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Château de Castelnaud-la-Chapelle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12.50€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Castelnaud-la-Chapelle, Dordogne, France' }, { icon: '🚇', label: '교통', value: '사를라에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Château de Compiègne': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7.50€. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place du Général de Gaulle, Compiègne, France' }, { icon: '🚇', label: '교통', value: '파리 북역에서 기차 50분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    "Château de l'Empéri": { vi: [{ icon: '🎫', label: '입장료', value: '성인 4.50€' }, { icon: '🕐', label: '운영시간', value: '수~월 13:30-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Montée du Puech, Salon-de-Provence, France' }, { icon: '🚇', label: '교통', value: '마르세유에서 차량 45분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cheongju National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00 (토·일 ~19:00). 월 휴관' }, { icon: '📍', label: '위치', value: '충북 청주시 상당구 명암로 143' }, { icon: '🚇', label: '교통', value: '청주 시내버스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cheshire Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Chester Castle, Chester, UK' }, { icon: '🚇', label: '교통', value: '체스터역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chilean National History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Plaza de Armas 951, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Plaza de Armas역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Chilean National Museum of Fine Arts': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:45. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parque Forestal, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Bellas Artes역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Chilean National Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:30, 일 11:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parque Quinta Normal, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Quinta Normal역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Chinese Aviation Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Datangshan, Changping, Beijing, China' }, { icon: '🚇', label: '교통', value: '베이징에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Chiran Peace Museum for Kamikaze Pilots': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Chiran-chō, Minamisatsuma, Kagoshima, Japan' }, { icon: '🚇', label: '교통', value: '가고시마에서 버스 70분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Chuncheon National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00 (토·일 ~19:00). 월 휴관' }, { icon: '📍', label: '위치', value: '강원 춘천시 우석로 70' }, { icon: '🚇', label: '교통', value: '춘천역에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Citadel Hill': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $11.70 CAD (6~9월). 그 외 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (여름). 그 외 산책 가능' }, { icon: '📍', label: '위치', value: '5425 Sackville Street, Halifax, NS, Canada' }, { icon: '🚇', label: '교통', value: '핼리팩스 다운타운 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Citadel of Besançon': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Rue des Fusillés de la Résistance, Besançon, France' }, { icon: '🚇', label: '교통', value: '브장송 비오트역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Citadel of Dinant': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€ (케이블카 포함)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Chemin de la Citadelle 1, Dinant, Belgium' }, { icon: '🚇', label: '교통', value: '디낭역 도보 10분 + 케이블카' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Citadelle of Quebec': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $18 CAD' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: '1 Côte de la Citadelle, Quebec City, QC, Canada' }, { icon: '🚇', label: '교통', value: '퀘벡시티 구시가지 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cité du train': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '2 Rue Alfred de Glehn, Mulhouse, France' }, { icon: '🚇', label: '교통', value: '뮐루즈역에서 트램 1번' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Città della Scienza': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€, 어린이 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Coroglio 57/104, Naples, Italy' }, { icon: '🚇', label: '교통', value: '나폴리 메트로 Campi Flegrei역 + 버스' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'City Museum of Rimini': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via L. Tonini 1, Rimini, Italy' }, { icon: '🚇', label: '교통', value: '리미니역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'City Museum Simeonstift, Trier': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Simeonstraße 60, Trier, Germany' }, { icon: '🚇', label: '교통', value: '트리어역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Civic Museum of Bozen': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Cassa di Risparmio 14, Bolzano, Italy' }, { icon: '🚇', label: '교통', value: '볼차노역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civic Museum of Palazzo Mosca': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 15:30-18:30' }, { icon: '📍', label: '위치', value: 'Piazza Toschi Mosca 29, Pesaro, Italy' }, { icon: '🚇', label: '교통', value: '페사로역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civic Museum of Teramo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Teramo, Abruzzo, Italy' }, { icon: '🚇', label: '교통', value: '테라모 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chiusi National Archaeological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-20:00' }, { icon: '📍', label: '위치', value: 'Via Porsenna 93, Chiusi, Siena, Italy' }, { icon: '🚇', label: '교통', value: '키우시역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chamber of Art and Curiosities': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Landshut, Bavaria, Germany' }, { icon: '🚇', label: '교통', value: '란트스후트역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chapelle des Cordeliers': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-12:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sarrebourg, Moselle, France' }, { icon: '🚇', label: '교통', value: '사루부르 SNCF역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Centro de Arte José Guerrero': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:30-14:00, 16:00-21:00. 일 10:30-14:00' }, { icon: '📍', label: '위치', value: 'Calle Oficios 8, Granada, Spain' }, { icon: '🚇', label: '교통', value: '그라나다 대성당 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Changsha Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kaifu District, Changsha, Hunan, China' }, { icon: '🚇', label: '교통', value: '창사 지하철' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Chongqing Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Beibei District, Chongqing, China' }, { icon: '🚇', label: '교통', value: '충칭 경전철 6호선' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Castel del Monte': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:45' }, { icon: '📍', label: '위치', value: 'Andria, BT, Italy' }, { icon: '🚇', label: '교통', value: '바리에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Chiesa del Tau': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Corso Silvano Fedi 30, Pistoia, Italy' }, { icon: '🚇', label: '교통', value: '피스토이아역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Chulalongkorn University Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '50 THB (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-16:00. 토·일 휴관' }, { icon: '📍', label: '위치', value: 'Chulalongkorn University, Bangkok, Thailand' }, { icon: '🚇', label: '교통', value: 'BTS Siam역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Church of the Santuccio': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-12:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Siena, Italy' }, { icon: '🚇', label: '교통', value: '시에나 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Cirta National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '200 DZD (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '토~목 09:00-17:00. 금 휴관' }, { icon: '📍', label: '위치', value: 'Constantine, Algeria' }, { icon: '🚇', label: '교통', value: '콘스탄틴 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civic museum of Palazzo Belgiojoso': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Corso Matteotti 32, Lecco, Italy' }, { icon: '🚇', label: '교통', value: '레코역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civic Museum and Pinacoteca, Mondavio': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-12:30, 15:30-18:30' }, { icon: '📍', label: '위치', value: 'Mondavio, Pesaro e Urbino, Italy' }, { icon: '🚇', label: '교통', value: '파노에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civic museum of Argenta': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-12:30, 15:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Argenta, Ferrara, Italy' }, { icon: '🚇', label: '교통', value: '페라라에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civic Museum of Fossils of Besano': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-12:00, 14:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Vittorio Veneto 21, Besano, Italy' }, { icon: '🚇', label: '교통', value: '밀라노 말펜사에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Citta di Castello Communal Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:30-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via della Cannoniera 22, Città di Castello, Italy' }, { icon: '🚇', label: '교통', value: '페루자에서 차량 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'civic art gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Civitanova Marche, Macerata, Italy' }, { icon: '🚇', label: '교통', value: '치비타노바 마르케역 도보' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Castello Aragonese': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Isola di Capo Rizzuto, KR, Italy' }, { icon: '🚇', label: '교통', value: '크로토네에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castello della Fava': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00 (동절기 ~17:00)' }, { icon: '📍', label: '위치', value: 'Posada, Nuoro, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '올비아에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Cattolica di Stilo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'Stilo, Reggio Calabria, Italy' }, { icon: '🚇', label: '교통', value: '레조칼라브리아에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Chichiri Museum': { vi: [{ icon: '🎫', label: '입장료', value: '500 MWK (~$0.50)' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-17:00, 토 09:00-13:00' }, { icon: '📍', label: '위치', value: 'Blantyre, Malawi' }, { icon: '🚇', label: '교통', value: '블랜타이어 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chinatown Storytelling Centre': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: '168 E Pender St, Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: 'SkyTrain Stadium-Chinatown역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Château des Rohan': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-12:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '4 Place de l\'Hôtel de Ville, Mutzig, France' }, { icon: '🚇', label: '교통', value: '스트라스부르에서 기차 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chūrui Naumann Elephant Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300엔' }, { icon: '🕐', label: '운영시간', value: '4~11월 매일 09:30-16:30' }, { icon: '📍', label: '위치', value: 'Makubetsu, Hokkaido, Japan' }, { icon: '🚇', label: '교통', value: '오비히로에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cité du Volcan': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Le Tampon, Réunion, France' }, { icon: '🚇', label: '교통', value: '생피에르에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    "Château de l'Empéri": { vi: [{ icon: '🎫', label: '입장료', value: '성인 4.50€' }, { icon: '🕐', label: '운영시간', value: '수~월 13:30-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Salon-de-Provence, France' }, { icon: '🚇', label: '교통', value: '마르세유에서 차량 45분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Château de Flers': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Villeneuve-d\'Ascq, Lille, France' }, { icon: '🚇', label: '교통', value: '릴에서 메트로 1 Pont de Bois역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chapel Bay Fort': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '야외, 항시 개방' }, { icon: '📍', label: '위치', value: 'Pembrokeshire, Wales, UK' }, { icon: '🚇', label: '교통', value: '펨브록셔 해안 경로' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Chamois Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-13:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Opi, L\'Aquila, Abruzzo, Italy' }, { icon: '🚇', label: '교통', value: '아브루초 국립공원 내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Andradas Historical and Pedagogical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Santos, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '산투스 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Applicat-Prazan': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (갤러리)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00' }, { icon: '📍', label: '위치', value: '16 Rue de Seine, Paris 6th, France' }, { icon: '🚇', label: '교통', value: '메트로 Saint-Germain-des-Prés역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Alfredo e Afonso de Taunay Historical and Pedagogical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Casa Branca, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '상파울루에서 차량 3시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Alfredo E. Múlgura Historical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'General Belgrano, Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: '부에노스아이레스에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'ALFs Kunst-Galerie': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Höpfingen, Baden-Württemberg, Germany' }, { icon: '🚇', label: '교통', value: '뷔르츠부르크에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Aaron Barber Memorial Building': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Avon, CT, USA' }, { icon: '🚇', label: '교통', value: '하트포드에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Ada Arts and Heritage Center': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Ada, OK, USA' }, { icon: '🚇', label: '교통', value: '오클라호마시티에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Africa Museum Suakoko': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Suakoko, Bong County, Liberia' }, { icon: '🚇', label: '교통', value: '몬로비아에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Alcheringa Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Victoria, BC, Canada' }, { icon: '🚇', label: '교통', value: '빅토리아 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Asam Building': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 개방' }, { icon: '📍', label: '위치', value: 'Freising, Bavaria, Germany' }, { icon: '🚇', label: '교통', value: '뮌헨 S1 프라이징역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'ArtPark Tegel': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Berlin-Tegel, Germany' }, { icon: '🚇', label: '교통', value: 'U6 Alt-Tegel역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Artists Space Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Melbourne, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '멜버른 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Augusto Vernarecci Civic Museum and Pinacotheca': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-12:30, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Fossombrone, Pesaro e Urbino, Italy' }, { icon: '🚇', label: '교통', value: '파노에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'ASLK gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 개방' }, { icon: '📍', label: '위치', value: 'Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼셀 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Atelier Ruth Roth': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Wertheim, Baden-Württemberg, Germany' }, { icon: '🚇', label: '교통', value: '뷔르츠부르크에서 기차 30분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'B.Y5 Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-18:00, 금 10:00-14:00' }, { icon: '📍', label: '위치', value: 'Tel Aviv, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        let r;
        if (info.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, info.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
