const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Madame Tussauds series + other notable
    'Madame Tussauds Amsterdam': { vi: [{ icon: '🎫', label: '입장료', value: '성인 24.50€ (온라인)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Dam 20, Amsterdam, Netherlands' }, { icon: '🚇', label: '교통', value: '트램 4/14 Dam역. 담 광장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Beijing': { vi: [{ icon: '🎫', label: '입장료', value: '190 CNY (~$26)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-21:00' }, { icon: '📍', label: '위치', value: 'Qianmen Pedestrian Street, Beijing, China' }, { icon: '🚇', label: '교통', value: '지하철 2호선 Qianmen역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Hollywood': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $30 (온라인)' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-19:00, 금·토 10:00-21:00' }, { icon: '📍', label: '위치', value: '6933 Hollywood Blvd, Hollywood, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro B Hollywood/Highland역 도보 1분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Hong Kong': { vi: [{ icon: '🎫', label: '입장료', value: 'HKD 280 (~$36)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-22:00' }, { icon: '📍', label: '위치', value: 'Peak Tower, The Peak, Hong Kong' }, { icon: '🚇', label: '교통', value: '피크 트램 The Peak역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Istanbul': { vi: [{ icon: '🎫', label: '입장료', value: '성인 250 TRY (~$7.50)' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-19:00' }, { icon: '📍', label: '위치', value: 'İstiklal Caddesi, Beyoğlu, Istanbul, Turkey' }, { icon: '🚇', label: '교통', value: '이스탄불 이스티클랄 거리' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Madame Tussauds New York': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $37 (온라인 $30)' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-20:00, 금·토 10:00-22:00' }, { icon: '📍', label: '위치', value: '234 W 42nd St, New York, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 1/2/3/7/N/Q/R/W Times Square역' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Madame Tussauds Sydney': { vi: [{ icon: '🎫', label: '입장료', value: 'AUD 42 (~$27)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Aquarium Wharf, Darling Harbour, Sydney, Australia' }, { icon: '🚇', label: '교통', value: 'Town Hall역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Dubai': { vi: [{ icon: '🎫', label: '입장료', value: 'AED 135 (~$37)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-22:00' }, { icon: '📍', label: '위치', value: 'Bluewaters Island, Dubai, UAE' }, { icon: '🚇', label: '교통', value: '두바이 블루워터스 아일랜드' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Delhi': { vi: [{ icon: '🎫', label: '입장료', value: '₹960 (~$11.50)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-19:00' }, { icon: '📍', label: '위치', value: 'Regal Building, Connaught Place, New Delhi, India' }, { icon: '🚇', label: '교통', value: '메트로 Yellow Line Rajiv Chowk역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Shanghai': { vi: [{ icon: '🎫', label: '입장료', value: '190 CNY (~$26)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-21:00' }, { icon: '📍', label: '위치', value: 'Nanjing Road, Shanghai, China' }, { icon: '🚇', label: '교통', value: '지하철 1/2/8호선 People\'s Square역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds San Francisco': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $27 (온라인)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '145 Jefferson St, Fisherman\'s Wharf, San Francisco, CA, USA' }, { icon: '🚇', label: '교통', value: '케이블카 Powell-Mason Line' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Orlando': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $30 (온라인)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-22:00' }, { icon: '📍', label: '위치', value: '8387 International Dr, Orlando, FL, USA' }, { icon: '🚇', label: '교통', value: 'I-Drive 국제 드라이브' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Washington D.C.': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25 (온라인)' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-18:00, 금·토 10:00-20:00' }, { icon: '📍', label: '위치', value: '1001 F St NW, Washington, D.C., USA' }, { icon: '🚇', label: '교통', value: 'Metro Red/Blue/Orange/Silver Metro Center역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds Blackpool': { vi: [{ icon: '🎫', label: '입장료', value: '£17 (온라인)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: '89 Promenade, Blackpool, UK' }, { icon: '🚇', label: '교통', value: '블랙풀 트램 Tower역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Madame Tussauds': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £33 (온라인 £23)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Marylebone Road, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube Baker Street역 도보 2분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Madrid Wax Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 21€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-14:00, 16:30-20:30' }, { icon: '📍', label: '위치', value: 'Paseo de Recoletos 41, Madrid, Spain' }, { icon: '🚇', label: '교통', value: '메트로 4 Colón역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MAC USP': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Pedro Álvares Cabral 1301, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 AACD-Servidor역. 오스카 니마이어 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'MACAAL Marrakech': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Rue Yougoslavie, Guéliz, Marrakech, Morocco' }, { icon: '🚇', label: '교통', value: '마라케시 신도시 게리즈 지구. 아프리카 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'MAMBO Bogotá': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00, 일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Calle 24 #6-00, Bogotá, Colombia' }, { icon: '🚇', label: '교통', value: '트랜스밀레니오 Av. Jiménez역 도보 5분. 콜롬비아 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Liege Fine Arts Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parc de la Boverie, Liège, Belgium' }, { icon: '🚇', label: '교통', value: '리에주역 도보 15분. 루벤 칼라트라바 건축' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Lithuanian Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-18:00, 일 11:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Didžioji g. 4, Vilnius, Lithuania' }, { icon: '🚇', label: '교통', value: '빌뉴스 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Paço das Artes': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 12:00-18:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Av. da Universidade 1, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 Butantã역. USP 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Regensburg Museum of History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Dachauplatz 2-4, Regensburg, Germany' }, { icon: '🚇', label: '교통', value: '레겐스부르크역 도보 15분. 로마·중세 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Mary and Leigh Block Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: '40 Arts Circle Dr, Evanston, IL, USA' }, { icon: '🚇', label: '교통', value: '노스웨스턴 대학교 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Woodmere Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: '9201 Germantown Ave, Philadelphia, PA, USA' }, { icon: '🚇', label: '교통', value: '필라델피아 체스넛힐. 필라델피아 미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Saginaw Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '1126 N Michigan Ave, Saginaw, MI, USA' }, { icon: '🚇', label: '교통', value: '사기노 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
