const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'Statens Museum for Kunst': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 성인 130 DKK' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Sølvgade 48-50, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: 'S-tog Nørreport역 도보 10분. 덴마크 국립미술관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Stedelijk Museum Amsterdam': { vi: [{ icon: '🎫', label: '입장료', value: '성인 22.50€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (금 ~22:00)' }, { icon: '📍', label: '위치', value: 'Museumplein 10, Amsterdam, Netherlands' }, { icon: '🚇', label: '교통', value: '트램 2/5/12 Van Baerlestraat역. 현대미술·디자인' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Storm King Art Center': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $22' }, { icon: '🕐', label: '운영시간', value: '4~11월 수~월 10:00-17:30. 화 휴관' }, { icon: '📍', label: '위치', value: '1 Museum Rd, New Windsor, NY, USA' }, { icon: '🚇', label: '교통', value: '뉴욕에서 차량 1시간. 200ha 야외 조각공원' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Taipei Fine Arts Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 30 TWD (~$1). 토 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:30 (토 ~20:30). 월 휴관' }, { icon: '📍', label: '위치', value: '181 Zhongshan N. Road Sec.3, Zhongshan, Taipei, Taiwan' }, { icon: '🚇', label: '교통', value: 'MRT Yuanshan역 도보 5분. 대만 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Tate Britain': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Millbank, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube Pimlico역 도보 5분. 터너·프리라파엘파·영국미술' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Tate Liverpool': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Royal Albert Dock, Liverpool, UK' }, { icon: '🚇', label: '교통', value: 'James Street역 도보 5분. 알버트 도크 UNESCO' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Te Papa Tongarewa': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: '55 Cable Street, Wellington, New Zealand' }, { icon: '🚇', label: '교통', value: '웰링턴 워터프론트 도보. 뉴질랜드 국립박물관' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Teshima Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 1,570엔' }, { icon: '🕐', label: '운영시간', value: '3~10월 10:00-17:00, 11~2월 10:00-16:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Teshima, Kagawa, Japan' }, { icon: '🚇', label: '교통', value: '다카마쓰에서 페리. 니시자와 류에 건축 + 나이토 레이 물방울' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Teylers Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Spaarne 16, Haarlem, Netherlands' }, { icon: '🚇', label: '교통', value: '하를렘역 도보 10분. 네덜란드 최초 박물관 (1784)' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'The Broad': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 유료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-17:00 (목·금 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: '221 S Grand Ave, Los Angeles, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro B/D Civic Center역 도보 5분. 쿠사마 인피니티룸' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'The Mondriaan House': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kortegracht 11, Amersfoort, Netherlands' }, { icon: '🚇', label: '교통', value: '아메르스포르트역 도보 10분. 몬드리안 생가' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Sursock Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월·수~일 10:00-18:00 (목 ~21:00). 화 휴관' }, { icon: '📍', label: '위치', value: 'Rue de l\'Archevêché Grec Orthodoxe, Beirut, Lebanon' }, { icon: '🚇', label: '교통', value: '베이루트 아쉬라피에 지구. 레바논 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Styrian Armoury': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-17:00. 11~3월 일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Herrengasse 16, Graz, Austria' }, { icon: '🚇', label: '교통', value: '그라츠 시내 헤렌가세. 세계 최대 역사 무기고' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Viking Museum Haithabu': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 09:00-17:00, 11~3월 화~일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Am Haddebyer Noor 5, Busdorf, Germany' }, { icon: '🚇', label: '교통', value: '슐레스비히에서 차량 10분. 바이킹 정착지 UNESCO' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Tàpies Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-19:00, 일 10:00-15:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Carrer d\'Aragó 255, Barcelona, Spain' }, { icon: '🚇', label: '교통', value: '메트로 L3/L4 Passeig de Gràcia역. 도메네크 이 몬타네르 건축' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Villa Carlotta': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-18:30' }, { icon: '📍', label: '위치', value: 'Via Regina 2, Tremezzina, Lake Como, Italy' }, { icon: '🚇', label: '교통', value: '코모에서 페리 Tremezzo. 코모 호수 정원 빌라' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Westphalian State Museum of Art and Cultural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (2번째 금 ~22:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Domplatz 10, Münster, Germany' }, { icon: '🚇', label: '교통', value: '뮌스터역 도보 10분. 뮌스터 대성당광장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Yad La-Shiryon': { vi: [{ icon: '🎫', label: '입장료', value: '30 ILS (~$8)' }, { icon: '🕐', label: '운영시간', value: '일~목 08:30-16:30, 금 08:30-12:00' }, { icon: '📍', label: '위치', value: 'Latrun, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브-예루살렘 고속도로 중간. 세계 최대 전차 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Tasmanian Museum and Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Dunn Place, Hobart, Tasmania, Australia' }, { icon: '🚇', label: '교통', value: '호바트 시내 워터프론트' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'State Museum of Natural History Karlsruhe': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~금 09:30-17:00, 토·일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Erbprinzenstraße 13, Karlsruhe, Germany' }, { icon: '🚇', label: '교통', value: '카를스루에역 트램 1/2/4' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Suan Pakkad Palace': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:00' }, { icon: '📍', label: '위치', value: '352-354 Si Ayuthaya Road, Bangkok, Thailand' }, { icon: '🚇', label: '교통', value: 'BTS Phaya Thai역 도보 5분. 태국 전통 티크 하우스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Strasbourg Historical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7.50€. 매월 첫 일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '2 Rue du Vieux-Marché-aux-Poissons, Strasbourg, France' }, { icon: '🚇', label: '교통', value: '트램 A/D Grand\'Rue역. 프띠프랑스 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Technik Museum Sinsheim': { vi: [{ icon: '🎫', label: '입장료', value: '성인 19€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Museumsplatz, Sinsheim, Germany' }, { icon: '🚇', label: '교통', value: '진스하임역 도보 15분. 콩코드+Tu-144 지붕 위 전시!' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Tallinn Art Hall': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '수~일 12:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Vabaduse väljak 6, Tallinn, Estonia' }, { icon: '🚇', label: '교통', value: '탈린 자유광장' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Tenerife Espacio de las Artes': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. de San Sebastián, Santa Cruz de Tenerife, Spain' }, { icon: '🚇', label: '교통', value: '산타크루스 시내. 카나리아 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Wax Museum of Fátima': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Rua Jacinta Marto, Fátima, Portugal' }, { icon: '🚇', label: '교통', value: '파티마 성지 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Trogir City Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 30 HRK (~$4.20)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-20:00 (동절기 ~17:00)' }, { icon: '📍', label: '위치', value: 'Gradska vrata 4, Trogir, Croatia' }, { icon: '🚇', label: '교통', value: '스플리트에서 차량 30분. UNESCO 중세 도시' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Wewelsburg': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Burgwall 19, Büren, Germany' }, { icon: '🚇', label: '교통', value: '파더보른에서 차량 20분. SS 역사 기록관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'West Stow Anglo-Saxon Village': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8.50' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Icklingham Rd, West Stow, Suffolk, UK' }, { icon: '🚇', label: '교통', value: '베리 세인트 에드먼즈에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Vlora History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '200 ALL (~$2)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-15:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Vlorë, Albania' }, { icon: '🚇', label: '교통', value: '블로라 시내. 알바니아 독립 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Yumeji Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 800엔' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Naka-ku, Okayama, Japan' }, { icon: '🚇', label: '교통', value: '오카야마역 도보 15분. 유메지 다케히사 미인화' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Verdun Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-19:00 (동절기 ~17:00)' }, { icon: '📍', label: '위치', value: '1 Avenue du Corps Européen, Verdun, France' }, { icon: '🚇', label: '교통', value: '베르됭역에서 차량 10분. 1차대전 전투 기념' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Yanase Takashi Memorial Hall': { vi: [{ icon: '🎫', label: '입장료', value: '성인 700엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Kami, Kochi, Japan' }, { icon: '🚇', label: '교통', value: '고치에서 차량 1시간. 호빵맨 작가 기념관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Omaha Beach Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8.90€' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 09:30-18:00' }, { icon: '📍', label: '위치', value: 'Avenue de la Libération, Saint-Laurent-sur-Mer, France' }, { icon: '🚇', label: '교통', value: '바이외에서 차량 15분. D-Day 오마하 해변' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
