const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    'Kestnergesellschaft': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Goseriede 11, Hanover, Germany' }, { icon: '🚇', label: '교통', value: '하노버 Kröpcke역 도보 3분. 1916년 설립 쿤스트페라인' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo delle Civiltà': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Guglielmo Marconi, EUR, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 B EUR Fermi역 도보 5분. 로마 문명 박물관 통합' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Museo di Palazzo Poggi': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-16:00, 토·일·공휴일 10:30-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Zamboni 33, Bologna, Italy' }, { icon: '🚇', label: '교통', value: '볼로냐 대학교 캠퍼스. 과학기구·자연표본·해부학' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo di Santa Corona': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Contrà Santa Corona 2, Vicenza, Italy' }, { icon: '🚇', label: '교통', value: '비첸차역 도보 10분. 베로네세·벨리니' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo de Sitio Oficinas Salitreras Humberstone y Santa Laura': { vi: [{ icon: '🎫', label: '입장료', value: '5,000 CLP (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Pozo Almonte, Tarapacá, Chile' }, { icon: '🚇', label: '교통', value: '이키게에서 차량 45분. UNESCO 세계유산 질산염 광산' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Museo de la Solidaridad Salvador Allende': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'República 475, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 1 República역 도보 3분. 미로·칼더·마타 기증작' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo de la Palabra y la Imagen': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-12:00, 14:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '27 San Salvador, El Salvador' }, { icon: '🚇', label: '교통', value: '산살바도르 시내. 엘살바도르 기억과 이미지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo de la Fuerza Armada de El Salvador': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:00-16:00' }, { icon: '📍', label: '위치', value: 'San Salvador, El Salvador' }, { icon: '🚇', label: '교통', value: '산살바도르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo de Santiago Casa Colorada': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토 10:00-17:00, 일 11:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Merced 860, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Plaza de Armas역 도보 2분. 식민시대 저택' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Museo del Meteorito': { vi: [{ icon: '🎫', label: '입장료', value: '4,000 CLP (~$4.40)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-13:00, 14:30-18:30' }, { icon: '📍', label: '위치', value: 'Toconao, San Pedro de Atacama, Chile' }, { icon: '🚇', label: '교통', value: '산페드로 데 아타카마. 아타카마 운석 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo de Sitio Nao Victoria': { vi: [{ icon: '🎫', label: '입장료', value: '5,000 CLP (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Punta Arenas, Chile' }, { icon: '🚇', label: '교통', value: '푼타아레나스 해안. 마젤란 나오 빅토리아호 복원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Diocesano of Palermo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:30' }, { icon: '📍', label: '위치', value: 'Via Matteo Bonello 2, Palermo, Italy' }, { icon: '🚇', label: '교통', value: '팔레르모 대성당 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo delle mummie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-13:00, 14:30-17:00' }, { icon: '📍', label: '위치', value: 'Ferentillo, Terni, Italy' }, { icon: '🚇', label: '교통', value: '테르니에서 차량 30분. 자연 미이라' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Museo dei Fossili di Bolca': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-13:00, 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Vestenanova, Verona, Italy' }, { icon: '🚇', label: '교통', value: '베로나에서 차량 40분. 에오세 5천만년 어류 화석' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo della via Ostiense': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-13:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Raffaele Persichetti 3, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 B Piramide역 도보 5분. 산 파올로 성문' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Museo Histórico Gabriel González Videla': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00, 토 10:00-13:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'La Serena, Chile' }, { icon: '🚇', label: '교통', value: '라 세레나 구시가지. 전 대통령 생가' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Histórico Cornelio de Saavedra': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Crisólogo Larralde 6309, Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: '부에노스아이레스 사아베드라 지구' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Indian Air Force Museum Palam': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Palam, New Delhi, India' }, { icon: '🚇', label: '교통', value: '델리 메트로 Palam역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museo de la Exploración Rudolph Amandus Philippi': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Valdivia, Chile' }, { icon: '🚇', label: '교통', value: '발디비아 강변. 독일계 이민사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Hollywood Wax Museum Branson': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $22' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-21:00' }, { icon: '📍', label: '위치', value: '3030 W 76 Country Blvd, Branson, MO, USA' }, { icon: '🚇', label: '교통', value: '브랜슨 스트립' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Hollywood Wax Museum Pigeon Forge': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-22:00' }, { icon: '📍', label: '위치', value: '106 Showplace Blvd, Pigeon Forge, TN, USA' }, { icon: '🚇', label: '교통', value: '피전 포지 스모키 마운틴 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
