const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★ Major museums
    'K21': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토 11:00-18:00, 일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Ständehausstraße 1, Düsseldorf, Germany' }, { icon: '🚇', label: '교통', value: 'U70/U74/U76/U77 Heinrich-Heine-Allee역. 21세기 현대미술 전문' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Iziko South African National Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R30 (~$1.60)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Government Ave, Company\'s Garden, Cape Town, South Africa' }, { icon: '🚇', label: '교통', value: '케이프타운 시내 컴퍼니즈 가든 내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Jakarta History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '5,000 IDR (~$0.30)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-15:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jl. Taman Fatahillah, Kota Tua, Jakarta, Indonesia' }, { icon: '🚇', label: '교통', value: '트랜스자카르타 Kota Tua 역. 코타 투아 광장' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'John and Mable Ringling Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25, 학생 무료. 월 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (목 ~20:00)' }, { icon: '📍', label: '위치', value: '5401 Bay Shore Rd, Sarasota, FL, USA' }, { icon: '🚇', label: '교통', value: '사라소타 시내 차량 10분. 바로크 미술 + Ca\' d\'Zan 저택' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Juno Beach Centre': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 09:30-19:00, 11~2월 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Voie des Français Libres, Courseulles-sur-Mer, France' }, { icon: '🚇', label: '교통', value: '캉에서 차량 20분. 노르망디 상륙 캐나다군 기념관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Jewish Museum Frankfurt': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Bertha-Pappenheim-Platz 1, Frankfurt, Germany' }, { icon: '🚇', label: '교통', value: 'U1/U2/U3 Willy-Brandt-Platz역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Jurassic Museum of Asturias': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7.24€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:30-14:30, 15:30-18:30. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'San Telmo, Colunga, Asturias, Spain' }, { icon: '🚇', label: '교통', value: '히혼에서 차량 40분. 공룡 해안 절벽 위' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Itamaraty Historical and Diplomatic Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 13:00-17:00' }, { icon: '📍', label: '위치', value: 'Av. Marechal Floriano, Rio de Janeiro, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 Uruguaiana역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Jehangir Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-19:00' }, { icon: '📍', label: '위치', value: '161B M.G. Road, Kala Ghoda, Mumbai, India' }, { icon: '🚇', label: '교통', value: 'CST역 도보 10분. 뭄바이 대표 갤러리' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'İzmir Painting and Sculpture Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Konak, İzmir, Turkey' }, { icon: '🚇', label: '교통', value: '이즈미르 메트로 Konak역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Juan Manuel Blanes Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-17:45. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Millán 4015, Montevideo, Uruguay' }, { icon: '🚇', label: '교통', value: '몬테비데오 프라도 공원 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Jaisalmer War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-18:00' }, { icon: '📍', label: '위치', value: 'Jaisalmer-Jodhpur Highway, Jaisalmer, Rajasthan, India' }, { icon: '🚇', label: '교통', value: '자이살메르 시내 차량 10분. 인도-파키스탄 전쟁 기념' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Indian War Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Red Fort, Delhi, India' }, { icon: '🚇', label: '교통', value: '메트로 바이올렛 라인 Lal Quila역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Institut Néerlandais': { vi: [{ icon: '🎫', label: '입장료', value: '무료~8€' }, { icon: '🕐', label: '운영시간', value: '화~일 13:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '121 Rue de Lille, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 12 Assemblée Nationale역' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Institute of Vertebrate Paleontology and Paleoanthropology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: '142 Xizhimenwai Dajie, Beijing, China' }, { icon: '🚇', label: '교통', value: '지하철 4호선 Dongsi역. 베이징 자연사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Israeli Air Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '30 ILS (~$8)' }, { icon: '🕐', label: '운영시간', value: '일~목 08:00-17:00. 금·토 휴관' }, { icon: '📍', label: '위치', value: 'Hatzerim AFB, Beer Sheva, Israel' }, { icon: '🚇', label: '교통', value: '베에르셰바에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Hellenic Air Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-14:00, 일 09:30-14:00' }, { icon: '📍', label: '위치', value: 'Dekelia Air Base, Tatoi, Athens, Greece' }, { icon: '🚇', label: '교통', value: '아테네 북쪽 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Hanover Historical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-17:00, 토·일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Pferdestraße 6, Hanover, Germany' }, { icon: '🚇', label: '교통', value: '하노버역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Jagdschloss Grunewald': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-17:30. 겨울 주말만' }, { icon: '📍', label: '위치', value: 'Grunewald, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S7 Grunewald역 도보 20분. 르네상스 사냥용 성' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Hollywood Wax Museums
    'Hollywood Wax Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $19.99' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-24:00' }, { icon: '📍', label: '위치', value: '6767 Hollywood Blvd, Hollywood, CA, USA' }, { icon: '🚇', label: '교통', value: 'Metro Red Line Hollywood/Highland역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Kagoshima Prefectural Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 310엔' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Shiroyama-chō, Kagoshima, Japan' }, { icon: '🚇', label: '교통', value: '가고시마 시전차 시로야마역. 사쿠라지마 전망' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Kanagawa Prefectural Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 720엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: '499 Iryūda, Odawara, Kanagawa, Japan' }, { icon: '🚇', label: '교통', value: '오다와라역에서 버스 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Historical Museum of Pomorie': { vi: [{ icon: '🎫', label: '입장료', value: '5 BGN (~$2.80)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00 (동절기 ~17:00)' }, { icon: '📍', label: '위치', value: 'Pomorie, Burgas Province, Bulgaria' }, { icon: '🚇', label: '교통', value: '부르가스에서 차량 20분. 흑해 해안' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Historical Museum of Skodër': { vi: [{ icon: '🎫', label: '입장료', value: '200 ALL (~$2)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Shkodër, Albania' }, { icon: '🚇', label: '교통', value: '티라나에서 미니버스 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Holy Defense Museum (Hamadan)': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-17:00' }, { icon: '📍', label: '위치', value: 'Hamadan, Iran' }, { icon: '🚇', label: '교통', value: '하마단 시내. 이란-이라크 전쟁 기념' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Hiwasa Sea Turtle Museum "Caretta"': { vi: [{ icon: '🎫', label: '입장료', value: '성인 610엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Hiwasa, Minami, Tokushima, Japan' }, { icon: '🚇', label: '교통', value: 'JR 히와사역 도보 15분. 바다거북 산란지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Hjemsted Oldtidspark': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 DKK (~$15)' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Hjemstedvej 53, Tønder, Denmark' }, { icon: '🚇', label: '교통', value: '뇬더에서 차량 10분. 철기시대 체험 공원' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Hurghada Marine Museum & Aquarium': { vi: [{ icon: '🎫', label: '입장료', value: '50 EGP (~$1.60)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-22:00' }, { icon: '📍', label: '위치', value: 'Hurghada, Red Sea, Egypt' }, { icon: '🚇', label: '교통', value: '후르가다 시내. 홍해 해양생물' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Heimatmuseum Oberammergau': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Dorfstraße 8, Oberammergau, Germany' }, { icon: '🚇', label: '교통', value: '뮌헨에서 기차 2시간. 수난극 마을' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Hardwick Hall': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £18 (NT)' }, { icon: '🕐', label: '운영시간', value: '3~10월 수~일 11:00-16:30' }, { icon: '📍', label: '위치', value: 'Doe Lea, Chesterfield, Derbyshire, UK' }, { icon: '🚇', label: '교통', value: '체스터필드 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'House of Photography': { vi: [{ icon: '🎫', label: '입장료', value: '150 CZK (~$6.50)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Revoluční 5, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 B Náměstí Republiky역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'Idaho Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'ISU Campus, Pocatello, ID, USA' }, { icon: '🚇', label: '교통', value: '아이다호 주립대 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Hichisō Precambrian Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Hichisō, Gifu, Japan' }, { icon: '🚇', label: '교통', value: '나고야에서 JR 타카야마선. 선캄브리아 화석' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Hobetsu Earth Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mukawa, Hokkaido, Japan' }, { icon: '🚇', label: '교통', value: '무카와역에서 버스. 무카와룡(카무이사우루스) 전시' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Houraijisan Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Shinshiro, Aichi, Japan' }, { icon: '🚇', label: '교통', value: 'JR 이이다선 혼나가시노역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Iwakishi Sekitan Kasekikan': { vi: [{ icon: '🎫', label: '입장료', value: '성인 650엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Iwaki, Fukushima, Japan' }, { icon: '🚇', label: '교통', value: '이와키역에서 버스. 석탄·화석 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Izu Ōshima Volcano Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Motomachi, Ōshima, Tokyo, Japan' }, { icon: '🚇', label: '교통', value: '도쿄 죽도항에서 고속선 1.5시간. 미하라야마 화산' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Japanese Fossil Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Okayama, Japan' }, { icon: '🚇', label: '교통', value: '오카야마 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geophysical Museum, Rocca di Papa': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-13:00 (예약)' }, { icon: '📍', label: '위치', value: 'Rocca di Papa, Lazio, Italy' }, { icon: '🚇', label: '교통', value: '로마에서 차량 30분. 지진·기상 관측 역사' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
