const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Major museums
    'Fondation Beyeler': { vi: [{ icon: '🎫', label: '입장료', value: '성인 25 CHF (~$28), 학생 12 CHF. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (수 ~20:00)' }, { icon: '📍', label: '위치', value: 'Baselstrasse 101, Riehen, Basel, Switzerland' }, { icon: '🚇', label: '교통', value: '바젤 SBB역에서 트램 6번 Fondation Beyeler 정류장. 렌초 피아노 설계' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Fotografiska': { vi: [{ icon: '🎫', label: '입장료', value: '성인 220 SEK (~$21), 학생 170 SEK' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-23:00' }, { icon: '📍', label: '위치', value: 'Stadsgårdshamnen 22, Stockholm, Sweden' }, { icon: '🚇', label: '교통', value: 'T-bana Slussen역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Fotografiska New York': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $31, 학생 $21' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-21:00 (금·토 ~23:00)' }, { icon: '📍', label: '위치', value: '281 Park Ave S, New York, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 6번 28th St역 도보 2분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Fotografiska Tallinn': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€, 학생 10€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-22:00' }, { icon: '📍', label: '위치', value: 'Telliskivi 60a, Tallinn, Estonia' }, { icon: '🚇', label: '교통', value: '탈린역 도보 10분. Telliskivi 창작구 내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fukui Prefectural Dinosaur Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 730엔, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 매월 둘째·넷째 수 휴관' }, { icon: '📍', label: '위치', value: 'Terao, Katsuyama, Fukui, Japan' }, { icon: '🚇', label: '교통', value: '후쿠이역에서 에치젠 철도 가쓰야마역 → 셔틀버스. 기시 쿠로카와 설계' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Frederik Meijer Gardens & Sculpture Park': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20, 어린이 $10' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-17:00, 일 11:00-17:00' }, { icon: '📍', label: '위치', value: '1000 E Beltline Ave NE, Grand Rapids, MI, USA' }, { icon: '🚇', label: '교통', value: '그랜드 래피즈 시내 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'French Foreign Legion Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-12:00, 14:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Chemin de la Thuilière, Aubagne, France' }, { icon: '🚇', label: '교통', value: '마르세유에서 기차 Aubagne역 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Forsvarsmuseet': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (9~4월 11:00-16:00)' }, { icon: '📍', label: '위치', value: 'Akershus Festning, Oslo, Norway' }, { icon: '🚇', label: '교통', value: '오슬로 중앙역 도보 10분. 아케르스후스 성 내' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Former Ford Factory': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: '351 Upper Bukit Timah Road, Singapore' }, { icon: '🚇', label: '교통', value: 'MRT Hillview역 도보 10분. 일본군 항복 장소' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fortress of Mimoyecques': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Landrethun-le-Nord, Pas-de-Calais, France' }, { icon: '🚇', label: '교통', value: '칼레에서 차량 15분. V-3 슈퍼건 벙커' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fortress of San Leo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-18:30 (동절기 ~16:30)' }, { icon: '📍', label: '위치', value: 'San Leo, Rimini, Italy' }, { icon: '🚇', label: '교통', value: '리미니에서 차량 30분. 카비올리오스트로 감금지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fossa Magna Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 12~2월 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Itoigawa, Niigata, Japan' }, { icon: '🚇', label: '교통', value: '이토이가와역에서 택시/버스 10분. 일본 지질 공원' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Fersman Mineralogical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 400₽ (~$4.50)' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Leninsky Prospekt 18, Moscow, Russia' }, { icon: '🚇', label: '교통', value: '모스크바 메트로 Oktyabrskaya역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Forbes Museum of Tangier': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (현재 문의 필요)' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Rue Shakespeare, Tangier, Morocco' }, { icon: '🚇', label: '교통', value: '탕헤르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Fotografisk / Fotohof
    'Fotografisk Center': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~금 12:00-18:00, 토·일 12:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Staldgade 16, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐 Dybbølsbro역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Fotohof': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 14:00-19:00, 토 11:00-15:00' }, { icon: '📍', label: '위치', value: 'Inge-Morath-Platz 1-3, Salzburg, Austria' }, { icon: '🚇', label: '교통', value: '잘츠부르크역에서 버스 / 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    // Fort series continued
    'Fort Beauséjour': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외). 전시 $4 CAD' }, { icon: '🕐', label: '운영시간', value: '6~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Point de Bute, NB, Canada' }, { icon: '🚇', label: '교통', value: '멍크턴에서 차량 45분. 아카디아 추방 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Paull': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £7, 어린이 £4' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Battery Road, Paull, East Riding of Yorkshire, UK' }, { icon: '🚇', label: '교통', value: '헐에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort Moultrie Visitor Center': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: "Sullivan's Island, Charleston, SC, USA" }, { icon: '🚇', label: '교통', value: '찰스턴에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Sumter Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:30 (보트 도착 시간 기준)' }, { icon: '📍', label: '위치', value: 'Sumter Island, Charleston Harbor, SC, USA' }, { icon: '🚇', label: '교통', value: 'Liberty Square에서 페리 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간 (섬)' }] },
    'Fort Erie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $9 CAD' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '350 Lakeshore Road, Fort Erie, ON, Canada' }, { icon: '🚇', label: '교통', value: '나이아가라 폭포에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Lytton National Park': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매월 첫째 일 10:00-15:00' }, { icon: '📍', label: '위치', value: 'South Brisbane, Queensland, Australia' }, { icon: '🚇', label: '교통', value: '브리즈번 시내에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Scratchley': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Nobbys Road, Newcastle, NSW, Australia' }, { icon: '🚇', label: '교통', value: '뉴캐슬역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Queenscliff': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD$15 (투어)' }, { icon: '🕐', label: '운영시간', value: '토·일 투어 (예약)' }, { icon: '📍', label: '위치', value: 'Queenscliff, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '멜버른에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Zoutman': { vi: [{ icon: '🎫', label: '입장료', value: '10 AFL (~$5.60)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Oranjestad, Aruba' }, { icon: '🚇', label: '교통', value: '오라녜스타트 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fortaleza San Felipe': { vi: [{ icon: '🎫', label: '입장료', value: '100 DOP (~$2)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Puerto Plata, Dominican Republic' }, { icon: '🚇', label: '교통', value: '푸에르토플라타 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Stewart 3d Infantry Division Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (군사기지, 신분증 필요)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Fort Stewart, Liberty County, GA, USA' }, { icon: '🚇', label: '교통', value: '사바나에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Italian fortresses
    'Forte di Santa Tecla': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Corso Matteotti, Sanremo, Italy' }, { icon: '🚇', label: '교통', value: '산레모역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fortezza di Firmafede': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Sarzana, La Spezia, Italy' }, { icon: '🚇', label: '교통', value: '사르자나역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fortezza di Sarzanello': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Sarzana, La Spezia, Italy' }, { icon: '🚇', label: '교통', value: '사르자나에서 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fortezza Santa Barbara': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Pistoia, Tuscany, Italy' }, { icon: '🚇', label: '교통', value: '피스토이아역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fossanova Abbey': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '매일 07:00-12:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Priverno, Latina, Italy' }, { icon: '🚇', label: '교통', value: '프리베르노역에서 택시. 로마에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fortress Dobrošov': { vi: [{ icon: '🎫', label: '입장료', value: '성인 90 CZK (~$4)' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Dobrošov, Náchod, Czech Republic' }, { icon: '🚇', label: '교통', value: '프라하에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Japanese museums
    'Fossil Museum of Ogano': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Ogano, Saitama, Japan' }, { icon: '🚇', label: '교통', value: '치치부 철도 Ogano역에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fossa Magna Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (12~2월 화 휴관)' }, { icon: '📍', label: '위치', value: 'Itoigawa, Niigata, Japan' }, { icon: '🚇', label: '교통', value: '이토이가와역 택시 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Firefly Museum of Toyota Town': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200엔' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Shimonoseki, Yamaguchi, Japan' }, { icon: '🚇', label: '교통', value: '시모노세키 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fujiwaradake Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Inabe, Mie, Japan' }, { icon: '🚇', label: '교통', value: '산요선 이나베역에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fukui City Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:15. 월 휴관' }, { icon: '📍', label: '위치', value: 'Fukui, Japan' }, { icon: '🚇', label: '교통', value: '후쿠이역에서 버스 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Others
    'Excavation of Stabiae': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-19:30 (동절기 ~17:00)' }, { icon: '📍', label: '위치', value: 'Castellammare di Stabia, Naples, Italy' }, { icon: '🚇', label: '교통', value: 'Circumvesuviana Castellammare di Stabia역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'estancia of Jesús María': { vi: [{ icon: '🎫', label: '입장료', value: '200 ARS (~$0.25)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jesús María, Córdoba, Argentina' }, { icon: '🚇', label: '교통', value: '코르도바에서 차량 50분. 예수회 에스탄시아 유네스코 유산' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Eversmann Zoology Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Kazan University, Kazan, Russia' }, { icon: '🚇', label: '교통', value: '카잔 크렘린 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Finnish Jaeger Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 12:00-17:00' }, { icon: '📍', label: '위치', value: 'Kauhava, South Ostrobothnia, Finland' }, { icon: '🚇', label: '교통', value: '카우하바역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fishing Bridge Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (옐로스톤 입장료 $35/차량)' }, { icon: '🕐', label: '운영시간', value: '5~9월 매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Yellowstone National Park, WY, USA' }, { icon: '🚇', label: '교통', value: '옐로스톤 호수 인근' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Federico Eusebio Civic Museum of Archaeology and Natural Sciences, Alba': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-12:30, 14:30-18:30, 토·일 10:00-12:30, 15:00-18:30' }, { icon: '📍', label: '위치', value: 'Via Vittorio Emanuele 19, Alba, Cuneo, Italy' }, { icon: '🚇', label: '교통', value: '알바역 도보 5분. 피에몬테 트러플 지역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Frugone Collection': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-19:00, 토·일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Capolungo 9, Nervi, Genoa, Italy' }, { icon: '🚇', label: '교통', value: '제노바 Nervi역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fonderie Darling': { vi: [{ icon: '🎫', label: '입장료', value: '무료~10 CAD (전시별 상이)' }, { icon: '🕐', label: '운영시간', value: '수~일 12:00-19:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '745 Rue Ottawa, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 Square-Victoria역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Far Eastern Prisoners Of War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제. 매월 첫째 토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Lichfield, Staffordshire, UK' }, { icon: '🚇', label: '교통', value: '리치필드 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fossils and Lithography Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Gunzenhausen, Bavaria, Germany' }, { icon: '🚇', label: '교통', value: '뉘른베르크에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fundação Casa da Cultura de Marabá': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 08:00-17:00' }, { icon: '📍', label: '위치', value: 'Marabá, Pará, Brazil' }, { icon: '🚇', label: '교통', value: '마라바 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Fur Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 75 DKK (~$11)' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Fur, Skive, Denmark' }, { icon: '🚇', label: '교통', value: '스키베에서 페리. 모러 퇴적물 화석' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'G. A. Sanna National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Roma 64, Sassari, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '사사리역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Gaio Cilnio Mecenate State Archaeological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Margaritone 10, Arezzo, Italy' }, { icon: '🚇', label: '교통', value: '아레초역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galería de la Historia de Concepción': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lincoyan esquina Larenas, Concepción, Chile' }, { icon: '🚇', label: '교통', value: '콘셉시온 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort San Carlos': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-14:00, 16:00-19:30' }, { icon: '📍', label: '위치', value: 'Palma de Mallorca, Spain' }, { icon: '🚇', label: '교통', value: '팔마 시내 해안가' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fort Dunree': { vi: [{ icon: '🎫', label: '입장료', value: '성인 €6' }, { icon: '🕐', label: '운영시간', value: '월~금 10:30-18:00, 토·일 13:00-18:00' }, { icon: '📍', label: '위치', value: 'Dunree Head, Inishowen, County Donegal, Ireland' }, { icon: '🚇', label: '교통', value: '데리에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Ligonier': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $12, 어린이 $8' }, { icon: '🕐', label: '운영시간', value: '4~11월 월~토 10:00-16:30, 일 12:00-16:30' }, { icon: '📍', label: '위치', value: '200 S Market St, Ligonier, PA, USA' }, { icon: '🚇', label: '교통', value: '피츠버그에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Forks Timber Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: '1421 S Forks Ave, Forks, WA, USA' }, { icon: '🚇', label: '교통', value: '시애틀에서 차량 3.5시간. 트와일라잇 촬영지 인근' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Expiatory Chapel of Monza': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 14:00-18:00' }, { icon: '📍', label: '위치', value: 'Via Carlo Porta, Monza, Italy' }, { icon: '🚇', label: '교통', value: '밀라노에서 메트로 M1 + 기차 Monza역' }, { icon: '⏱️', label: '관람시간', value: '20분' }] },
    'Fondazione Cassa di risparmio di Tortona. Pinacoteca': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 15:00-19:00' }, { icon: '📍', label: '위치', value: 'Via Emilia 34, Tortona, Alessandria, Italy' }, { icon: '🚇', label: '교통', value: '토르토나역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Gabii archaeological area': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제 (가이드 투어)' }, { icon: '📍', label: '위치', value: 'Via Prenestina, Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마 동쪽 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort de Leveau': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '4~10월 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Maubeuge, Nord, France' }, { icon: '🚇', label: '교통', value: '모뵈주역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Franck A. Perret Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '월~금 08:30-17:00' }, { icon: '📍', label: '위치', value: 'Saint-Pierre, Martinique, France' }, { icon: '🚇', label: '교통', value: '포르드프랑스에서 차량 40분. 1902 펠레 화산 폭발 박물관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort de Saint-Héribert': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '가이드 투어 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Wépion, Namur, Belgium' }, { icon: '🚇', label: '교통', value: '나뮈르에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Edward': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Fort Edward, Windsor, NS, Canada' }, { icon: '🚇', label: '교통', value: '핼리팩스에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Farneta antiquarium': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Farneta, Cortona, Arezzo, Italy' }, { icon: '🚇', label: '교통', value: '코르토나에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
