const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★ Major museums
    'German Museum of Technology': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 학생 4€. 15시 이후 4€' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:30, 토·일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Trebbiner Straße 9, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U1/U2 Gleisdreieck역 도보 3분 / S1 Anhalter Bahnhof역' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Germanisches Nationalmuseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 학생 5€. 수 18시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수 ~20:30). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kartäusergasse 1, Nuremberg, Germany' }, { icon: '🚇', label: '교통', value: '뉘른베르크역 도보 10분. 독일어권 최대 문화사 박물관' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Glyptothek': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€. 일 1€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Königsplatz 3, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Königsplatz역 도보 1분. 그리스·로마 조각' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Grand Gallery of Evolution': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€, 학생 7€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00 (수 잘 확인). 화 휴관' }, { icon: '📍', label: '위치', value: '36 Rue Geoffroy-Saint-Hilaire, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 5/10 Gare d\'Austerlitz역. 자르뎅 데 플랑트 내' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Grand Gallery of Louvre-Lens': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 별도' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '99 Rue Paul Bert, Lens, France' }, { icon: '🚇', label: '교통', value: '파리 북역에서 TGV 1시간 Lens역 셔틀. SANAA 건축' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Great North Museum: Hancock': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00, 일 11:00-16:00' }, { icon: '📍', label: '위치', value: 'Barras Bridge, Newcastle upon Tyne, UK' }, { icon: '🚇', label: '교통', value: '메트로 Haymarket역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Georgian National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15 GEL (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '3 Rustaveli Ave, Tbilisi, Georgia' }, { icon: '🚇', label: '교통', value: '메트로 Liberty Square역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Gimhae National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-18:00, 토·일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '경남 김해시 가야의길 190' }, { icon: '🚇', label: '교통', value: '부산-김해 경전철 봉황역 도보 15분. 가야문화 전문' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Gongju National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-18:00, 토·일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '충남 공주시 관광단지길 34' }, { icon: '🚇', label: '교통', value: '공주시 공산성 인근. 무령왕릉 유물 전시' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Gibraltar Museum': { vi: [{ icon: '🎫', label: '입장료', value: '£5, 어린이 £2.50' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00, 토 10:00-14:00. 일 휴관' }, { icon: '📍', label: '위치', value: '18-20 Bomb House Lane, Gibraltar' }, { icon: '🚇', label: '교통', value: '스페인 라리네아에서 도보 국경 통과 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'German Tank Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Hans-Krüger-Str. 33, Munster, Lower Saxony, Germany' }, { icon: '🚇', label: '교통', value: '함부르크에서 차량 1시간. 독일 기갑 역사' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Great Palace Mosaic Museum': { vi: [{ icon: '🎫', label: '입장료', value: '60 TRY (~$2)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00 (동절기 ~17:00)' }, { icon: '📍', label: '위치', value: 'Torun Sokak, Sultanahmet, Istanbul, Turkey' }, { icon: '🚇', label: '교통', value: '트램 T1 Sultanahmet역 도보 3분. 비잔틴 모자이크' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'George C. Page Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15. 매월 첫째 화 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00' }, { icon: '📍', label: '위치', value: '5801 Wilshire Blvd, Los Angeles, CA, USA (La Brea Tar Pits)' }, { icon: '🚇', label: '교통', value: 'Metro Bus 20/720 Wilshire/Curson. 라브레아 타르핏' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Georgia Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00, 토 10:00-17:00. 일 휴관' }, { icon: '📍', label: '위치', value: '101 Cedar St, Athens, GA, USA' }, { icon: '🚇', label: '교통', value: 'UGA 캠퍼스 내. 애틀랜타에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gotoh Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 1,100엔' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '9-25 Kaminoge 3-chome, Setagaya, Tokyo, Japan' }, { icon: '🚇', label: '교통', value: '도쿄 도큐 오이마치선 카미노게역 도보 5분. 동양미술·국보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Goshoura Cretaceous Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Goshoura, Amakusa, Kumamoto, Japan' }, { icon: '🚇', label: '교통', value: '아마쿠사에서 차량/페리. 백악기 화석' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gothenburg Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-17:00, 토·일 11:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Slottsskogen, Gothenburg, Sweden' }, { icon: '🚇', label: '교통', value: '트램 Linnéplatsen 정류장 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Goulandris Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '월·수~토 09:00-14:30, 일 10:00-14:30. 화 휴관' }, { icon: '📍', label: '위치', value: '13 Levidou, Kifissia, Athens, Greece' }, { icon: '🚇', label: '교통', value: '아테네 메트로 1 Kifissia역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Government Museum and Art Gallery, Chandigarh': { vi: [{ icon: '🎫', label: '입장료', value: '10 INR (~$0.12)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sector 10, Chandigarh, India' }, { icon: '🚇', label: '교통', value: '찬디가르 시내. 르코르뷔지에 도시계획 인근' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Goya Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '2 Rue de l\'Hôtel de Vicomte, Castres, France' }, { icon: '🚇', label: '교통', value: '툴루즈에서 차량 1시간. 고야 스페인 미술 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Grant Museum of Zoology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 13:00-17:00. 일 휴관' }, { icon: '📍', label: '위치', value: '21 University St, London WC1E, UK' }, { icon: '🚇', label: '교통', value: 'Warren Street역 도보 5분. UCL 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'Gloucester Waterways Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £6.50' }, { icon: '🕐', label: '운영시간', value: '매일 10:30-17:00' }, { icon: '📍', label: '위치', value: 'Llanthony Warehouse, Gloucester Docks, UK' }, { icon: '🚇', label: '교통', value: '글로스터역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Gjirokastra Cold War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '200 ALL (~$2)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'Gjirokastër, Albania' }, { icon: '🚇', label: '교통', value: '티라나에서 버스 4시간. 지로카스트라 성 내 냉전 벙커' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Giant Forest Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (세퀘이어 국립공원 입장 $35/차량)' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Sequoia National Park, CA, USA' }, { icon: '🚇', label: '교통', value: '비살리아에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Giorgio De Chirico House': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00 (월 제외, 사전 예약 권장)' }, { icon: '📍', label: '위치', value: 'Piazza di Spagna 31, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 A Spagna역 바로 앞. 데 키리코 아틀리에' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'Georges Labit Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '17 Rue du Japon, Toulouse, France' }, { icon: '🚇', label: '교통', value: '메트로 B François Verdier역 도보 5분. 동양 미술 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Giacomo Doria Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Brigata Liguria 9, Genoa, Italy' }, { icon: '🚇', label: '교통', value: '제노바 Brignole역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Giardino Storico della Villa Medicea di Castello': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-일몰 (시즌별 상이). 둘째·셋째 월 휴관' }, { icon: '📍', label: '위치', value: 'Via di Castello 47, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체에서 버스 28번. 메디치 가문 정원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Grafeneck Euthanasia Centre': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 개방 (추모관)' }, { icon: '📍', label: '위치', value: 'Gomadingen, Baden-Württemberg, Germany' }, { icon: '🚇', label: '교통', value: '슈투트가르트에서 차량 1시간. 나치 안락사 추모관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gateway Science Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $6, 어린이 $4' }, { icon: '🕐', label: '운영시간', value: '목~일 12:00-17:00' }, { icon: '📍', label: '위치', value: '625 Esplanade, Chico, CA, USA' }, { icon: '🚇', label: '교통', value: '치코 CSU 캠퍼스 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gallery of Contemporary Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Civitella in Val di Chiana, Arezzo, Italy' }, { icon: '🚇', label: '교통', value: '아레초에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Geological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200엔' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Higashi, Japan' }, { icon: '🚇', label: '교통', value: '지역 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geological Museum of the State Geological Institute': { vi: [{ icon: '🎫', label: '입장료', value: '8 PLN (~$2)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'ul. Rakowiecka 4, Warsaw, Poland' }, { icon: '🚇', label: '교통', value: '메트로 M1 Pole Mokotowskie역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geomuseum Faxe': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 DKK (~$15)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Østsjællandsvej 2, Faxe, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐에서 기차 1시간. 산호초 화석 채석장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Government bunker': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '수~일 투어 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Ahrweiler, Rhineland-Palatinate, Germany' }, { icon: '🚇', label: '교통', value: '본에서 차량 30분. 냉전 서독 정부 비밀 벙커' }, { icon: '⏱️', label: '관람시간', value: '1.5시간 (가이드 투어)' }] },
    'Gran Paradiso National Park Visitors Centre': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 09:00-12:30, 14:30-18:00' }, { icon: '📍', label: '위치', value: 'Rhêmes-Notre-Dame, Aosta Valley, Italy' }, { icon: '🚇', label: '교통', value: '아오스타에서 차량 45분. 이탈리아 최초 국립공원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Glacier Point Trailside Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (요세미티 입장 $35/차량)' }, { icon: '🕐', label: '운영시간', value: '5~10월 매일' }, { icon: '📍', label: '위치', value: 'Glacier Point, Yosemite National Park, CA, USA' }, { icon: '🚇', label: '교통', value: '요세미티 밸리에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galerie Schwartzsche Villa': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Grunewaldstraße 55, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S1 Rathaus Steglitz역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Galerie Pankow': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 13:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Breite Straße 8, Berlin-Pankow, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Pankow역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Glasmuseum Wertheim': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mühlenstraße 24, Wertheim, Germany' }, { icon: '🚇', label: '교통', value: '뷔르츠부르크에서 차량 30분. 유리공예 박물관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Giacomo Manzù Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Laurentina km 32, Ardea, Lazio, Italy' }, { icon: '🚇', label: '교통', value: '로마에서 차량 40분. 만주 조각' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gemma 1786 museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Emilia San Pietro, Modena, Italy' }, { icon: '🚇', label: '교통', value: '모데나역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'General Nicolas Plantamura Historical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-13:00' }, { icon: '📍', label: '위치', value: 'Mendoza Province, Argentina' }, { icon: '🚇', label: '교통', value: '멘도사 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galerie Moderne': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Silkeborg, Denmark' }, { icon: '🚇', label: '교통', value: '실케보르 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Great War Flying Museum': { vi: [{ icon: '🎫', label: '입장료', value: '$10 CAD (기부)' }, { icon: '🕐', label: '운영시간', value: '5~10월 토 10:00-15:00' }, { icon: '📍', label: '위치', value: 'Brampton Airport, Caledon, ON, Canada' }, { icon: '🚇', label: '교통', value: '토론토에서 차량 1시간. 1차대전 복원 항공기' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
