const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Major museums & attractions
    'Ambras Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€, 학생 12€. 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Schloßstraße 20, Innsbruck, Austria' }, { icon: '🚇', label: '교통', value: '인스브루크역에서 트램 6번 / 시글 버스' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Australian National Maritime Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (실내). 선박 투어 성인 AUD$32' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00' }, { icon: '📍', label: '위치', value: '2 Murray Street, Darling Harbour, Sydney, Australia' }, { icon: '🚇', label: '교통', value: '시드니 Lightrail Pyrmont Bay 정류장 / Town Hall역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Blue Grotto': { vi: [{ icon: '🎫', label: '입장료', value: '입장 15€ + 보트 15€ (~30€ 총)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (해상 조건에 따라 변경)' }, { icon: '📍', label: '위치', value: 'Via Grotta Azzurra, Anacapri, Capri, Italy' }, { icon: '🚇', label: '교통', value: '나폴리/소렌토에서 페리→카프리 마리나 그란데→버스/보트' }, { icon: '⏱️', label: '관람시간', value: '30분 (동굴 내 5분)' }] },
    'Battleship Cove': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25, 어린이 $15' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '5 Water Street, Fall River, MA, USA' }, { icon: '🚇', label: '교통', value: '보스턴에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Buffalo and Erie County Naval & Military Park': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $16, 어린이 $10' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '1 Naval Park Cove, Buffalo, NY, USA' }, { icon: '🚇', label: '교통', value: '버팔로 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Chester Beatty Library': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:45-17:30, 토 09:45-17:30, 일 12:00-17:30' }, { icon: '📍', label: '위치', value: 'Dublin Castle, Dublin 2, Ireland' }, { icon: '🚇', label: '교통', value: 'Luas Red Line Smithfield / DART Tara St역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Chatham Historic Dockyard': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £20.50, 어린이 £10' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (11~3월 ~16:00)' }, { icon: '📍', label: '위치', value: 'Main Gate Road, Chatham, Kent, UK' }, { icon: '🚇', label: '교통', value: '채텀역 도보 15분. 런던에서 기차 1시간' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Central Naval Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300₽ (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'pl. Truda 5, St Petersburg, Russia' }, { icon: '🚇', label: '교통', value: '메트로 Admiralteyskaya역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Brest national naval museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '매일 13:30-18:30 (여름 10:00-18:30)' }, { icon: '📍', label: '위치', value: 'Château de Brest, Brest, France' }, { icon: '🚇', label: '교통', value: '브레스트역 도보 20분. 트램 A/B 정류장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Blockhaus d'Éperlecques": { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Rue des Sarts, Éperlecques, Pas-de-Calais, France' }, { icon: '🚇', label: '교통', value: '칼레에서 차량 20분. V-2 발사 벙커' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Braidense National Library of Milan': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 08:30-18:15, 토 09:00-13:30. 일 휴관' }, { icon: '📍', label: '위치', value: 'Via Brera 28, Milan, Italy' }, { icon: '🚇', label: '교통', value: '메트로 M2 Lanza역 도보 3분 (브레라 미술관 건물 내)' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Brandenburg-Preussen Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Eichenallee 7a, Wustrau-Altfriesack, Germany' }, { icon: '🚇', label: '교통', value: '베를린에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Chilean cultural centers
    'Centro Cultural Casa Gonzalo Rojas': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-13:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Chillán, Ñuble, Chile' }, { icon: '🚇', label: '교통', value: '치얀 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Centro Cultural Comunitario Monumento Histórico Pabellón 83': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lota, Biobío, Chile' }, { icon: '🚇', label: '교통', value: '콘셉시온에서 버스 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Centro Cultural La Unión': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-18:00' }, { icon: '📍', label: '위치', value: 'La Unión, Los Ríos, Chile' }, { icon: '🚇', label: '교통', value: '발디비아에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Centro de Cultura Tradicional Curarrehue': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Curarrehue, Araucanía, Chile' }, { icon: '🚇', label: '교통', value: '푸콘에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Museo Padre Pancho': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Pucón, Araucanía, Chile' }, { icon: '🚇', label: '교통', value: '테무코에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Casa Museo Luisa Chijani': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Ancud, Chiloé, Chile' }, { icon: '🚇', label: '교통', value: '카스트로에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Casa Museo Familia San Martín': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Gorbea, Araucanía, Chile' }, { icon: '🚇', label: '교통', value: '테무코에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Casona Cultural Duao': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Talca, Maule, Chile' }, { icon: '🚇', label: '교통', value: '탈카 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Casa del Arte Diego Rivera': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-13:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Puerto Montt, Los Lagos, Chile' }, { icon: '🚇', label: '교통', value: '푸에르토몬트 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Casa do Benin': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:00, 토·일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Pelourinho, Salvador, Bahia, Brazil' }, { icon: '🚇', label: '교통', value: '살바도르 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Casa da Memória Paraná': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Ponta Grossa, Paraná, Brazil' }, { icon: '🚇', label: '교통', value: '쿠리치바에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa museo de la ciudad': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-13:00, 15:00-20:00' }, { icon: '📍', label: '위치', value: 'San Miguel de Tucumán, Argentina' }, { icon: '🚇', label: '교통', value: '투쿠만 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Others
    'Charlotte County Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '6~9월 월~토 09:30-16:30' }, { icon: '📍', label: '위치', value: '443 Milltown Blvd, St. Stephen, NB, Canada' }, { icon: '🚇', label: '교통', value: 'US 국경 인근. 세인트존에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chad National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:00-17:00' }, { icon: '📍', label: '위치', value: "N'Djamena, Chad" }, { icon: '🚇', label: '교통', value: '은자메나 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chaiya National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Chaiya, Surat Thani, Thailand' }, { icon: '🚇', label: '교통', value: '수랏타니에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chiang Saen National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Chiang Saen, Chiang Rai, Thailand' }, { icon: '🚇', label: '교통', value: '치앙라이에서 차량 1시간. 골든 트라이앵글 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chumphon National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Chumphon, Thailand' }, { icon: '🚇', label: '교통', value: '추폰역에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Colección Museográfica de la Legión en Almería': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Base Álvarez de Sotomayor, Viator, Almería, Spain' }, { icon: '🚇', label: '교통', value: '알메리아에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Clemente Susini\'s wax anatomical models': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Cagliari, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '칼리아리 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civico Museo Insubrico di Storia Naturale': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 14:00-18:00 및 예약' }, { icon: '📍', label: '위치', value: 'Clivio, Varese, Italy' }, { icon: '🚇', label: '교통', value: '바레세에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bork Vikingehavn': { vi: [{ icon: '🎫', label: '입장료', value: '성인 75 DKK (~$11)' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Nørre Nebel, Ringkøbing-Skjern, Denmark' }, { icon: '🚇', label: '교통', value: '빌룬에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Benin City National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '500 NGN (~$0.50)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'King Square, Benin City, Edo State, Nigeria' }, { icon: '🚇', label: '교통', value: '베닌시티 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Boubou Hama National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '500 XOF (~$0.80)' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-18:00' }, { icon: '📍', label: '위치', value: 'Niamey, Niger' }, { icon: '🚇', label: '교통', value: '니아메 시내' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Bergenhus Fortress Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 NOK (~$8), 학생 40 NOK' }, { icon: '🕐', label: '운영시간', value: '5~9월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Bergen, Norway' }, { icon: '🚇', label: '교통', value: '베르겐역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Berliner Kunsthalle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '수~월 11:00-19:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Tempelhofer Feld, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U6 Tempelhof역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chelungpu Fault Trench Preservation Hall': { vi: [{ icon: '🎫', label: '입장료', value: '50 TWD (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jhushan, Nantou County, Taiwan' }, { icon: '🚇', label: '교통', value: '타이중에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Centro de Interpretación „Castillo de San Cristóbal"': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Santa Cruz de Tenerife, Canary Islands, Spain' }, { icon: '🚇', label: '교통', value: '산타크루스 시내 트램' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Civic gallery of Sarnano': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Sarnano, Macerata, Italy' }, { icon: '🚇', label: '교통', value: '마체라타에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Civic Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Cadorna, Cremona, Italy' }, { icon: '🚇', label: '교통', value: '크레모나역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cimalonga tower': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Scalea, Cosenza, Italy' }, { icon: '🚇', label: '교통', value: '스칼레아역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '15분' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        let r;
        if (info.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, info.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
