const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★ World-class
    'Egyptian Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300 EGP (~$10), 학생 150 EGP' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Tahrir Square, Cairo, Egypt' }, { icon: '🚇', label: '교통', value: '카이로 메트로 Sadat역 도보 5분. 세계 최대 고대 이집트 유물 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Dia:Beacon': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $20, 학생 $12' }, { icon: '🕐', label: '운영시간', value: '금~월 11:00-17:00 (4~10월), 토·일 11:00-16:00 (11~3월)' }, { icon: '📍', label: '위치', value: '3 Beekman St, Beacon, NY, USA' }, { icon: '🚇', label: '교통', value: '메트로노스 Beacon역 도보 15분. NYC에서 기차 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Es Baluard': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€, 학생 3€' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-20:00, 일 10:00-15:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Plaça Porta de Santa Catalina 10, Palma, Mallorca, Spain' }, { icon: '🚇', label: '교통', value: '팔마 시내 도보. 16세기 성벽 위 현대미술관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'EMMA': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€' }, { icon: '🕐', label: '운영시간', value: '화·수·금 11:00-17:00, 목 11:00-19:00, 토·일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'WeeGee Exhibition Centre, Ahertie 2, Espoo, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키 메트로 Tapiola역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Escher Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 11€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lange Voorhout 74, The Hague, Netherlands' }, { icon: '🚇', label: '교통', value: '헤이그 중앙역 도보 10분. M.C. 에셔 전문 미술관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Deutsches Marinemuseum Wilhelmshaven': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9.50€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (11~3월 ~17:00)' }, { icon: '📍', label: '위치', value: 'Südstrand 125, Wilhelmshaven, Germany' }, { icon: '🚇', label: '교통', value: '빌헬름스하펜역 도보 20분. 잠수함·구축함 실물 전시' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Design Museum of Thessaloniki': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '166 Mitropoleos, Thessaloniki, Greece' }, { icon: '🚇', label: '교통', value: '테살로니키 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Durham Light Infantry Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £4' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (11~3월 ~16:00)' }, { icon: '📍', label: '위치', value: 'Aykley Heads, Durham, UK' }, { icon: '🚇', label: '교통', value: '더럼역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Egyptian Geological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 09:00-15:00' }, { icon: '📍', label: '위치', value: 'Corniche El Nil, Cairo, Egypt' }, { icon: '🚇', label: '교통', value: '카이로 시내 나일강변' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Colombian Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-16:00, 토·일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Calle 10 #4-92, La Candelaria, Bogotá, Colombia' }, { icon: '🚇', label: '교통', value: '트랜스밀레니오 La Candelaria 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dajing Ge Pavilion': { vi: [{ icon: '🎫', label: '입장료', value: '5 CNY (~$0.70)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:30' }, { icon: '📍', label: '위치', value: 'Renmin Road, Shanghai, China' }, { icon: '🚇', label: '교통', value: '메트로 8호선 Dapuqiao역 도보 10분. 명나라 성벽' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Enrico Caffi Museum of Natural Science': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Cittadella 10, Bergamo Alta, Italy' }, { icon: '🚇', label: '교통', value: '후니쿨라로 베르가모 알타 도착' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Ernesto Bachmann Paleontological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '1,200 ARS (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00 (동절기 ~18:00)' }, { icon: '📍', label: '위치', value: 'Villa El Chocón, Neuquén, Argentina' }, { icon: '🚇', label: '교통', value: '네우켄에서 차량 1.5시간. 기가노토사우루스 화석' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort des Dunes': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '4~11월 토·일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Leffrinckoucke, Nord, France' }, { icon: '🚇', label: '교통', value: '덩케르크에서 차량 10분. 덩케르크 철수 작전 요새' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort de Bellegarde': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:30-18:30' }, { icon: '📍', label: '위치', value: 'Le Perthus, Pyrénées-Orientales, France' }, { icon: '🚇', label: '교통', value: '페르피냥에서 차량 30분. 스페인 국경 요새' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Petrie Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '$5 CAD' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'New Victoria, Cape Breton, NS, Canada' }, { icon: '🚇', label: '교통', value: '시드니에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fort Roberdeau': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '5~10월 화~토 10:00-17:00, 일 13:00-17:00' }, { icon: '📍', label: '위치', value: 'Altoona, PA, USA' }, { icon: '🚇', label: '교통', value: '알투나에서 차량 10분. 미국 독립전쟁 요새' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort Glanville Conservation Park': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매월 셋째 일 12:00-17:00' }, { icon: '📍', label: '위치', value: 'Semaphore Park, SA, Australia' }, { icon: '🚇', label: '교통', value: '아들레이드 시내에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Henri Cartier-Bresson Foundation': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '79 Rue des Archives, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 11 Arts et Métiers역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Challenge at Aldershot (Military & Aerospace Museums)': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Queens Avenue, Aldershot, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '알더숏역 도보 10분. 영국 군사 역사' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Echigo-Matsunoyama Museum of Natural Science "Kyororo"': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Tōkamachi, Niigata, Japan' }, { icon: '🚇', label: '교통', value: '마쓰노야마 온천역에서 바스. 설국 자연과학' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Essex Regiment Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00, 일 13:00-17:00' }, { icon: '📍', label: '위치', value: 'Oaklands Park, Chelmsford, Essex, UK' }, { icon: '🚇', label: '교통', value: '첼름스퍼드역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civitacampomarano Castle': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Civitacampomarano, Campobasso, Molise, Italy' }, { icon: '🚇', label: '교통', value: '캄포바소에서 차량 40분. CVTà 스트리트아트 축제' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Elgin Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '$5 CAD' }, { icon: '🕐', label: '운영시간', value: '수~토 10:00-16:00' }, { icon: '📍', label: '위치', value: '30 Talbot St, St. Thomas, ON, Canada' }, { icon: '🚇', label: '교통', value: '런던(ON)에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Conakry National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Conakry, Guinea' }, { icon: '🚇', label: '교통', value: '코나크리 시내. 서아프리카 문화유산' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Chinese Militia Weapons and Equipment Exhibition Hall': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Luyi, Henan, China' }, { icon: '🚇', label: '교통', value: '루이현 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Davidstow Moor RAF Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '부활절~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Davidstow, Cornwall, UK' }, { icon: '🚇', label: '교통', value: '보드민에서 차량 30분. 2차대전 RAF 기지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Earth and Man National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '6 BGN (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '4 Cherni Vrah Blvd, Sofia, Bulgaria' }, { icon: '🚇', label: '교통', value: '소피아 메트로 남쪽 공원 인근' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
