const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

// 100 museums: {id: {vi: [...], website?: 'url'}}
const data = {
    // Abteiberg Museum - Mönchengladbach, DE
    '0e0aea14-184': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€, 할인 4.50€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Abteistraße 27, Mönchengladbach, Germany' }, { icon: '🚇', label: '교통', value: 'Mönchengladbach Hbf에서 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Accademia Carrara - Bergamo, IT
    'd8594a17-783': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 할인 8€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Giacomo Carrara 82, Bergamo, Italy' }, { icon: '🚇', label: '교통', value: '베르가모역에서 버스 1번 → Accademia Carrara 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    // Albertina - Vienna, AT
    'a2bf23aa-dd5': { vi: [{ icon: '🎫', label: '입장료', value: '성인 18.90€, 학생 13.90€. 19세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (수·금 10:00-21:00)' }, { icon: '📍', label: '위치', value: 'Albertinaplatz 1, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U2/U4 Karlsplatz역 도보 5분 / 트램 D, 1, 2 Oper 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    // Albertina Modern - Vienna, AT
    '3v0phg3u': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16.90€, 학생 12.90€. Albertina와 콤비티켓 22.90€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (수 10:00-21:00)' }, { icon: '📍', label: '위치', value: 'Karlsplatz 5, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U2/U4 Karlsplatz역 직결' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Albrecht Dürer's House - Nuremberg, DE
    'a9cfe33f-63f': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€, 할인 1.50€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Albrecht-Dürer-Straße 39, Nuremberg, Germany' }, { icon: '🚇', label: '교통', value: '뉘른베르크 중앙역에서 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // Alte Pinakothek - Munich, DE
    '88196fc5-31a': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€, 할인 5€. 일요일 1€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (화 10:00-20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Barer Straße 27, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Theresienstraße역 도보 5분 / 트램 27 Pinakotheken 정류장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    // Altes Museum - Berlin, DE
    'q6ha809w': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€, 할인 5€. 18세 이하 무료. Museum Island 콤비 19€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 10:00-20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Am Lustgarten, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Hackescher Markt역 도보 10분 / 버스 100, 200' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Amon Carter Museum - Fort Worth, US
    '652e6e93-238': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00 (목 10:00-20:00), 일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '3501 Camp Bowie Blvd, Fort Worth, TX, USA' }, { icon: '🚇', label: '교통', value: '포트워스 시내에서 차량 10분. 무료 주차' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Amos Rex - Helsinki, FI
    'e5jmzot1': { vi: [{ icon: '🎫', label: '입장료', value: '성인 18€, 학생 8€, 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '월·금 11:00-18:00, 수·목 11:00-20:00, 토~일 11:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Mannerheimintie 22-24, Helsinki, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키 중앙역에서 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-2시간' }], website: 'https://amosrex.fi/en/' },
    // Anıtkabir - Ankara, TR
    'b9006c66-4ad': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (5~10월 09:00-17:30)' }, { icon: '📍', label: '위치', value: 'Anıt Caddesi, Tandoğan, Ankara, Turkey' }, { icon: '🚇', label: '교통', value: '앙카라 메트로 Tandoğan역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Antalya Museum - Muratpaşa, TR
    'b5f2daf3-cb1': { vi: [{ icon: '🎫', label: '입장료', value: '120 TL (~$4). Museum Pass Turkey 사용 가능' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-19:00 (동절기 ~17:30)' }, { icon: '📍', label: '위치', value: 'Konyaaltı Cad. 88, Antalya, Turkey' }, { icon: '🚇', label: '교통', value: '안탈리아 시내 트램 Müze 정류장 하차' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    // Apsley House - London, GB
    '9219a85c-da0': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £12.50, 어린이 무료. English Heritage 회원 무료' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '149 Piccadilly, Hyde Park Corner, London, UK' }, { icon: '🚇', label: '교통', value: 'Hyde Park Corner역 직결' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // Admont Abbey - Admont, AT
    'd88a6ddf-cba': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13.50€, 학생 8€. 가족 28€' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-17:00, 12~2월 토·일 10:00-14:00' }, { icon: '📍', label: '위치', value: 'Kirchplatz 1, Admont, Austria' }, { icon: '🚇', label: '교통', value: '그라츠에서 기차+버스 약 2시간. Admont 버스정류장 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    // African American Civil War Museum
    '31ff7971-0a7': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:30, 일 12:00-18:30. 월 휴관' }, { icon: '📍', label: '위치', value: '1925 Vermont Ave NW, Washington, D.C., USA' }, { icon: '🚇', label: '교통', value: '메트로 Green Line U St/Cardozo역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // Agung Rai Museum of Art - Bali, ID
    'c2105072-778': { vi: [{ icon: '🎫', label: '입장료', value: '80,000 IDR (~$5). 어린이 40,000 IDR' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Jl. Raya Pengosekan, Ubud, Bali, Indonesia' }, { icon: '🚇', label: '교통', value: '우붓 중심가에서 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Airborne & Special Ops Museum
    '358c189d-9c9': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00, 일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '100 Bragg Blvd, Fayetteville, NC, USA' }, { icon: '🚇', label: '교통', value: '페이어트빌 시내, 무료 주차' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Akademisches Kunstmuseum - Bonn, DE
    'df817709-55b': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€, 학생 1.50€' }, { icon: '🕐', label: '운영시간', value: '화~금 15:00-17:00, 일 11:00-18:00. 월·토 휴관' }, { icon: '📍', label: '위치', value: 'Am Hofgarten 21, Bonn, Germany' }, { icon: '🚇', label: '교통', value: '본 중앙역에서 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Air Force Museum of New Zealand
    '9f0309e6-820': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '45 Harvard Avenue, Wigram, Christchurch, NZ' }, { icon: '🚇', label: '교통', value: '크라이스트처치 시내에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Adrien Dubouché National Museum - Limoges, FR
    '3b01fdf1-1e1': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 매월 첫째 일요일 무료. 26세 이하 EU 시민 무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-12:30, 14:00-17:45. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place Winston Churchill, Limoges, France' }, { icon: '🚇', label: '교통', value: '리모주 베네딕탱역에서 버스 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Aero Space Museum of Calgary
    'x2ixb1mu': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15 CAD, 학생 $10, 6세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: '4629 McCall Way NE, Calgary, AB, Canada' }, { icon: '🚇', label: '교통', value: '캘거리 공항 인근. 차량 접근 권장' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Aeroseum - Gothenburg, SE
    '63df15b3-94b': { vi: [{ icon: '🎫', label: '입장료', value: '성인 150 SEK (~$14), 어린이 100 SEK' }, { icon: '🕐', label: '운영시간', value: '토~일 11:00-16:00 (학기 중). 여름 매일' }, { icon: '📍', label: '위치', value: 'Säve flygplats, Gothenburg, Sweden' }, { icon: '🚇', label: '교통', value: '예테보리 중앙역에서 버스 32분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Anglo-Boer War Museum - Bloemfontein, ZA
    'a05b03c2-9cc': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R40 (~$2), 학생 R20' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-16:30, 토 10:00-17:00, 일 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Monument Rd, Bloemfontein, South Africa' }, { icon: '🚇', label: '교통', value: '블룸폰테인 시내에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Accademia di San Luca - Rome, IT
    '8fadf3e1-37f': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-19:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Piazza dell\'Accademia di San Luca 77, Rome, Italy' }, { icon: '🚇', label: '교통', value: 'A선 Barberini역 도보 10분 / 트레비분수 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Academy of San Carlos - Mexico City, MX
    'a47d5c27-262': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00. 토·일 휴관' }, { icon: '📍', label: '위치', value: 'Academia 22, Centro, Mexico City, Mexico' }, { icon: '🚇', label: '교통', value: '메트로 Zócalo역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Abegg Foundation - Riggisberg, CH
    '67cfc291-da3': { vi: [{ icon: '🎫', label: '입장료', value: '성인 20 CHF (~$22), 학생 10 CHF' }, { icon: '🕐', label: '운영시간', value: '4~11월 화~일 14:00-17:30. 월 휴관. 동절기 휴관' }, { icon: '📍', label: '위치', value: 'Werner Abeggstr. 67, Riggisberg, Switzerland' }, { icon: '🚇', label: '교통', value: '베른에서 버스 160번 약 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Airborne Museum - Sainte-Mère-Église, FR
    'anlrr0bd': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9.50€, 어린이 6€' }, { icon: '🕐', label: '운영시간', value: '2~11월 매일 09:00-18:30 (계절별 상이). 동절기 휴관' }, { icon: '📍', label: '위치', value: '14 Rue Eisenhower, Sainte-Mère-Église, France' }, { icon: '🚇', label: '교통', value: '셰르부르에서 차량 40분. D-Day 해변 투어 코스' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }], website: 'https://www.airborne-museum.org' },
    // Abbey of Monte Cassino - Cassino, IT
    'd473a974-82a': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '매일 08:45-12:30, 15:30-17:00 (여름 ~18:00). 일요일 미사 시간 제외' }, { icon: '📍', label: '위치', value: 'Via Montecassino, Cassino, Italy' }, { icon: '🚇', label: '교통', value: '카시노역에서 셔틀버스 또는 택시 20분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    // Altare della Patria - Rome, IT
    'e6943a9e-059': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (전망대 엘리베이터 7€)' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-19:30 (전망대 ~18:30)' }, { icon: '📍', label: '위치', value: 'Piazza Venezia, Rome, Italy' }, { icon: '🚇', label: '교통', value: '버스 Piazza Venezia 정류장 / 메트로 B선 Colosseo역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Abbazia di Pomposa - Codigoro, IT
    'fe7b83ad-256': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€, 할인 2.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Pomposa Centro 12, Codigoro, Italy' }, { icon: '🚇', label: '교통', value: '페라라에서 차량 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // 9.18 Historical Museum - Shenyang, CN
    '9a89ded4-b9c': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (신분증 필수)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:30 (마감 30분 전 입장 마감). 월 휴관' }, { icon: '📍', label: '위치', value: '46 Wanghua South St, Dadong District, Shenyang, China' }, { icon: '🚇', label: '교통', value: '선양 지하철 9호선 9·18 역사박물관역' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    // Allied Museum - Berlin, DE
    'vpz3matx': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Clayallee 135, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U3 Oskar-Helene-Heim역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // Aldershot Military Museum - GB
    '4e2d8ed8-4e9': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5.50, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Queens Avenue, Aldershot, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '올더숏역에서 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Aihui History Museum - Heilongjiang, CN
    '4f453e97-d9d': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Aihui District, Heihe, Heilongjiang, China' }, { icon: '🚇', label: '교통', value: '허이허 시내 버스 이용' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // 82nd Airborne Museum
    '14a25a77-68e': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:30. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Ardennes Street, Fort Liberty, NC, USA' }, { icon: '🚇', label: '교통', value: '페이어트빌에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // ADBC Museum - Wellsburg, US
    'd1b4008f-3e6': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $5, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00 또는 예약제' }, { icon: '📍', label: '위치', value: 'Wellsburg, WV, USA' }, { icon: '🚇', label: '교통', value: '피츠버그에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Ankara Painting and Sculpture Museum
    '2981beb3-1c5': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Opera Meydanı, Ulus, Ankara, Turkey' }, { icon: '🚇', label: '교통', value: '앙카라 메트로 Ulus역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Ankara Aviation Museum
    '7969d850-cb0': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Etimesgut, Ankara, Turkey' }, { icon: '🚇', label: '교통', value: '앙카라 시내에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // Aldan Maadyr National Museum - Kyzyl, RU
    'af36a08a-af3': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200₽ (~$2), 학생 100₽' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Titan str. 30, Kyzyl, Tuva Republic, Russia' }, { icon: '🚇', label: '교통', value: '크즐 시내 중심부' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }], website: 'https://museum.tuva.ru/' },
    // 8Q SAM - Singapore
    '1836bd85-a34': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-19:00 (금 10:00-21:00)' }, { icon: '📍', label: '위치', value: '8 Queen Street, Singapore 188535' }, { icon: '🚇', label: '교통', value: 'MRT Bras Basah역 도보 3분 / City Hall역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // 6th Cavalry Museum - Georgia, US
    'ebe23b2a-039': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00 또는 예약제' }, { icon: '📍', label: '위치', value: 'Fort Oglethorpe, GA, USA' }, { icon: '🚇', label: '교통', value: '채터누가에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // 493rd Bomb Group Museum - GB
    '707bb0a1-861': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '5~9월 일요일 14:00-17:00 또는 예약제' }, { icon: '📍', label: '위치', value: 'Debach Airfield, East Suffolk, UK' }, { icon: '🚇', label: '교통', value: '이프스위치에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // ANZAC Memorial - Sydney, AU
    'i4rl6yza': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Hyde Park South, Liverpool St, Sydney, Australia' }, { icon: '🚇', label: '교통', value: '시드니 Museum역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Airborne Assault - Cambridgeshire, GB
    '04509a06-7bc': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £7, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Building 20M, IWM Duxford, Cambridgeshire, UK' }, { icon: '🚇', label: '교통', value: '케임브리지에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Alabama Veterans Museum
    '7fc2aa4c-d7d': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-15:00. 일 휴관' }, { icon: '📍', label: '위치', value: '100 W Pryor Street, Athens, AL, USA' }, { icon: '🚇', label: '교통', value: '앨라배마 아테네 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // American Memorial Park - Saipan, US
    '9903d932-162': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰' }, { icon: '📍', label: '위치', value: 'Beach Road, Garapan, Saipan, CNMI' }, { icon: '🚇', label: '교통', value: '사이판 가라판 지역 중심부' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Aquitaine Museum - Bordeaux, FR
    'uixrs5j3': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€, 26세 이하 무료. 매월 첫째 일요일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '20 Cours Pasteur, Bordeaux, France' }, { icon: '🚇', label: '교통', value: '트램 B선 Musée d\'Aquitaine역 / 보르도 생장역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    // 400 ASA Gallery - Prague, CZ
    'qdr0b9vd': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 13:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Školská 28, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 I.P. Pavlova역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Anna Schwartz Gallery - Melbourne, AU
    'av1mvyzd': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-17:00, 토 11:00-16:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Melbourne, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '플린더스 스트리트역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Abbey of the Holy Spirit Monte Morrone - IT
    '75f80a6f-d55': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-19:00' }, { icon: '📍', label: '위치', value: 'Badia Morronese, Sulmona, Italy' }, { icon: '🚇', label: '교통', value: '술모나역에서 택시 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Aboriginal Gallery of Dreamings - Melbourne, AU
    'b3quu6m6': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (갤러리)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-17:00, 토 11:00-16:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Melbourne, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '멜버른 CBD 내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // African American Military History Museum
    'b22ae712-471': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $5, 어린이 $3' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '305 E 6th St, Hattiesburg, MS, USA' }, { icon: '🚇', label: '교통', value: '해티스버그 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Alderney Museum - GG
    'b0hmyall': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £3, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-16:00. 동절기 휴관' }, { icon: '📍', label: '위치', value: 'High Street, St Anne, Alderney, Channel Islands' }, { icon: '🚇', label: '교통', value: '올더니 공항에서 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Annan Museum - GB
    '41e12d0f-5cc': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-16:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Bank Street, Annan, Dumfries and Galloway, UK' }, { icon: '🚇', label: '교통', value: '에난역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Anti-Aircraft Museum - Tuusula, FI
    'lsib96io': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 어린이 4€' }, { icon: '🕐', label: '운영시간', value: '6~8월 화~일 11:00-17:00. 동절기 예약제' }, { icon: '📍', label: '위치', value: 'Tykkimetsäntie 1, Tuusula, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    // Antiquarian Hall - Worcester, US
    'e504a842-f20': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (회원 전용 열람)' }, { icon: '🕐', label: '운영시간', value: '수·금 09:00-17:00, 토 09:00-15:00' }, { icon: '📍', label: '위치', value: '185 Salisbury St, Worcester, MA, USA' }, { icon: '🚇', label: '교통', value: '우스터 유니온역에서 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Ammassalik Museum - Greenland
    'oj67x64l': { vi: [{ icon: '🎫', label: '입장료', value: '30 DKK (~$4)' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 13:00-16:00. 동절기 휴관' }, { icon: '📍', label: '위치', value: 'Tasiilaq, East Greenland' }, { icon: '🚇', label: '교통', value: '쿨루숙 공항에서 헬리콥터/보트' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Aqaba Archaeological Museum - Jordan
    '871b406c-324': { vi: [{ icon: '🎫', label: '입장료', value: '2 JOD (~$3). Jordan Pass 포함' }, { icon: '🕐', label: '운영시간', value: '토~목 08:00-16:00. 금 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Aqaba, Jordan' }, { icon: '🚇', label: '교통', value: '아카바 시내 마말루크 성 내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }], website: 'https://www.mota.gov.jo/' },
    // A La Vieille Russie - New York, US
    'rgjneu71': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (갤러리/상점)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-17:00. 토·일 휴관' }, { icon: '📍', label: '위치', value: '745 Fifth Avenue, New York, NY, USA' }, { icon: '🚇', label: '교통', value: 'E/M 5th Ave/53rd St역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    // Aghstafa State Art Gallery - Azerbaijan
    'thujyz2y': { vi: [{ icon: '🎫', label: '입장료', value: '2 AZN (~$1)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Aghstafa District, Azerbaijan' }, { icon: '🚇', label: '교통', value: '바쿠에서 기차 아그스타파역' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // 45th Infantry Division Museum - Oklahoma City, US
    '799f89b8-110': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-16:15, 토 10:00-16:15, 일 13:00-16:15. 월 휴관' }, { icon: '📍', label: '위치', value: '2145 NE 36th St, Oklahoma City, OK, USA' }, { icon: '🚇', label: '교통', value: '오클라호마시티 시내에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }], website: 'https://www.45thdivisionmuseum.com/' },
    // Andrew Jackson Cottage - Northern Ireland, GB
    '9fd82714-505': { vi: [{ icon: '🎫', label: '입장료', value: '£5, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '6~9월 화~토 11:00-16:00. 동절기 예약제' }, { icon: '📍', label: '위치', value: 'Boneybefore, Carrickfergus, Co. Antrim, UK' }, { icon: '🚇', label: '교통', value: '벨파스트에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Angers Engineering Museum - FR
    '05tzwdyv': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Angers, France' }, { icon: '🚇', label: '교통', value: '앙제 생로역에서 트램 A선' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Anne Baillie Building - Kingston, CA
    '3o77w0mv': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-16:00. 토·일 휴관' }, { icon: '📍', label: '위치', value: 'Royal Military College, Kingston, ON, Canada' }, { icon: '🚇', label: '교통', value: '킹스턴 시내에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Adbccoburg - Austria
    'd88a6ddf-cba---skip': { skip: true },
    // Annaborg - Denmark
    '8bx95iyj': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 화~일 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Hillerød Municipality, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐에서 S-tog E선 + 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Amiternum archaeological site - L'Aquila, IT
    '7726f076-fe4': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외 유적지)' }, { icon: '📍', label: '위치', value: 'Loc. San Vittorino, L\'Aquila, Italy' }, { icon: '🚇', label: '교통', value: '라퀼라에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Antiquarium di Boscoreale - IT
    'd83f5131-2ad': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€. 폼페이 콤비티켓 22€' }, { icon: '🕐', label: '운영시간', value: '수~월 08:30-19:30 (마감 1시간 전 입장). 화 휴관' }, { icon: '📍', label: '위치', value: 'Via Settetermini, Boscoreale, Italy' }, { icon: '🚇', label: '교통', value: '나폴리에서 Circumvesuviana 기차 Boscoreale역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Alte Feste - Windhoek, NA
    'd49d0eda-0fd': { vi: [{ icon: '🎫', label: '입장료', value: 'N$50 (~$3)' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-18:00, 토 09:00-14:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Robert Mugabe Avenue, Windhoek, Namibia' }, { icon: '🚇', label: '교통', value: '빈트후크 시내 중심' }, { icon: '⏱️', label: '관람시간', value: '1시간' }], website: 'https://www.museums.com.na/' },
    // Al Ain National Museum - UAE
    '85393b47-83d': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 금 15:00-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sultan Bin Zayed Fort, Al Ain, UAE' }, { icon: '🚇', label: '교통', value: '두바이/아부다비에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Al Mahatta Fort - Sharjah, UAE
    'eb39c719-570': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토~목 08:00-20:00, 금 16:00-20:00' }, { icon: '📍', label: '위치', value: 'Al Estiqlal Square, Sharjah, UAE' }, { icon: '🚇', label: '교통', value: '두바이에서 차량 30분. 샤르자 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Africa Museum Suakoko - Liberia
    '1ec33274-408': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00. 토·일 휴관' }, { icon: '📍', label: '위치', value: 'Suakoko, Bong County, Liberia' }, { icon: '🚇', label: '교통', value: '몬로비아에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Air Force Museum of Iran
    'ojzd6515': { vi: [{ icon: '🎫', label: '입장료', value: '30,000 IRR (~$1)' }, { icon: '🕐', label: '운영시간', value: '토~목 08:00-16:30. 금 휴관' }, { icon: '📍', label: '위치', value: 'Mehrabad Airport area, Tehran, Iran' }, { icon: '🚇', label: '교통', value: '테헤란 메트로 Mehrabad Airport역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }], website: 'https://airforcemuseum.ir/' },
    // Aerospace Technology Museum - Argentina
    'v441rkkj': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Las Higueras, Córdoba, Argentina' }, { icon: '🚇', label: '교통', value: '코르도바 시내에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Aeronautical Military Museum - Argentina
    'gw7c0r8j': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Funes, Santa Fe, Argentina' }, { icon: '🚇', label: '교통', value: '로사리오에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Air Force Heritage Museum - Manitoba, CA
    'et4y5bwm': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'CFB Winnipeg, Manitoba, Canada' }, { icon: '🚇', label: '교통', value: '위니펙 시내에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Antiquarium Pyrgense - Santa Marinella, IT
    '16c8c6ba-392': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Castello di Santa Severa, Santa Marinella, Italy' }, { icon: '🚇', label: '교통', value: '로마에서 기차 Santa Severa역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Antiquarium Statale di Numana - IT
    '052f05ac-8ee': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€, 할인 2€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via La Fenice, Numana, Italy' }, { icon: '🚇', label: '교통', value: '안코나에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Antiquarium Turritano - Porto Torres, IT
    'e6746af6-3c9': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€, 할인 2.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Ponte Romano 99, Porto Torres, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '포르토 토레스 항구에서 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Antiquarium di Cannae - Barletta, IT
    '14136216-cbf': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Località Canne della Battaglia, Barletta, Italy' }, { icon: '🚇', label: '교통', value: '바를레타역에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Antiquarium Lucrezia Romana - Rome, IT
    '35634ff5-27f': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via dell\'Acqua Felice, Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마 시내 버스' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    // Ancient Aeclanum - Mirabella Eclano, IT
    'd96f8fd7-ef2': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외 유적지)' }, { icon: '📍', label: '위치', value: 'Mirabella Eclano, Avellino, Italy' }, { icon: '🚇', label: '교통', value: '아벨리노에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Ancient Roman architecture in Trieste - IT
    'fe2d5e51-e74': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외 유적)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Via del Teatro Romano, Trieste, Italy' }, { icon: '🚇', label: '교통', value: '트리에스테 중앙역에서 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    // Ancient Roman basilica - Brescia, IT
    'a33c9f4d-5e9': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€ (Museo Santa Giulia 콤비티켓)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Musei, Brescia, Italy' }, { icon: '🚇', label: '교통', value: '브레시아역에서 도보 15분 / 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Ancient Roman Theatre of Teano - IT
    '9ac61655-35f': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰' }, { icon: '📍', label: '위치', value: 'Teano, Caserta, Italy' }, { icon: '🚇', label: '교통', value: '나폴리에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
};

async function run() {
    let ok = 0, skip = 0;
    for (const [id, d] of Object.entries(data)) {
        if (d.skip) { skip++; continue; }
        const vi = JSON.stringify(d.vi);
        if (d.website) {
            await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE id=$3', [vi, d.website, id]);
        } else {
            await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE id=$2', [vi, id]);
        }
        ok++;
    }
    console.log(`✅ ${ok}개 업데이트 완료, ${skip}개 스킵`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
