const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★ Notable museums
    "Bunk'Art": { vi: [{ icon: '🎫', label: '입장료', value: '성인 500 ALL (~$5)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Fadil Deliu, Tirana, Albania' }, { icon: '🚇', label: '교통', value: '티라나 시내에서 차량 20분. 호자 시대 거대 벙커' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    "Bunk'Art 2": { vi: [{ icon: '🎫', label: '입장료', value: '성인 500 ALL (~$5)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'Rruga Abdi Toptani, Tirana, Albania' }, { icon: '🚇', label: '교통', value: '스칸데르베그 광장 도보 3분. 비밀경찰 역사' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Chelsea Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $8' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-18:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '556 W 22nd St, Manhattan, NY, USA' }, { icon: '🚇', label: '교통', value: '지하철 C/E 23rd St역 도보 5분. 첼시 갤러리 지구' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Foundation E.G. Bührle Collection': { vi: [{ icon: '🎫', label: '입장료', value: '쿤스트하우스 취리히 입장 포함 CHF 23' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수·목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kunsthaus Zürich, Heimplatz, Zurich, Switzerland' }, { icon: '🚇', label: '교통', value: '트램 3/5/8/9 Kunsthaus역. 인상파 걸작 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fundación NMAC': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-14:00 (하계 ~일몰). 월 휴관' }, { icon: '📍', label: '위치', value: 'Dehesa Montenmedio, Vejer de la Frontera, Cádiz, Spain' }, { icon: '🚇', label: '교통', value: '카디스/세비야에서 차량 1시간. 야외 대지미술' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Central Army Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 09:00-16:00' }, { icon: '📍', label: '위치', value: 'El Madania, Algiers, Algeria' }, { icon: '🚇', label: '교통', value: '알제 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Copenhagen University Botanical Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-18:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Gothersgade 130, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: 'S-tog Nørreport역 도보 5분. 코펜하겐 식물원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Centro de Interpretación „Castillo de San Cristóbal"': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Santa Cruz de Tenerife, Canary Islands, Spain' }, { icon: '🚇', label: '교통', value: '산타크루스 시내. 16세기 요새 유적' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Dead Sea Museum': { vi: [{ icon: '🎫', label: '입장료', value: '3 JOD (~$4.25)' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-16:00' }, { icon: '📍', label: '위치', value: 'Jordan Valley, Jordan' }, { icon: '🚇', label: '교통', value: '암만에서 차량 1시간. 사해 생태·역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dedovsk Museum of Universe History, Russia': { vi: [{ icon: '🎫', label: '입장료', value: '500 RUB (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Talitsy, Moscow Oblast, Russia' }, { icon: '🚇', label: '교통', value: '모스크바에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Deutsch-Jüdisches Museum Santiago': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토 10:00-14:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Vitacura, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '산티아고 비타쿠라 지역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Didactic Museum of Zoology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-12:00, 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Via Celoria, Milan, Italy' }, { icon: '🚇', label: '교통', value: '메트로 M2 Piola역 도보 5분. 밀라노 대학교' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Essl Collection': { vi: [{ icon: '🎫', label: '입장료', value: '현재 쿤스트하우스 빈에 소장' }, { icon: '🕐', label: '운영시간', value: '쿤스트하우스 빈: 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Klosterneuburg (원래), Wien (현재), Austria' }, { icon: '🚇', label: '교통', value: '빈에서 기차 Klosterneuburg' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Dr. Ángel Gallardo Provincial Natural Sciences Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-18:00, 토·일 14:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'San Lorenzo 1949, Rosario, Santa Fe, Argentina' }, { icon: '🚇', label: '교통', value: '로사리오 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dinan Remember 1939-1945 Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '7~8월 매일 14:00-18:00' }, { icon: '📍', label: '위치', value: 'Dinan, Côtes-d\'Armor, France' }, { icon: '🚇', label: '교통', value: '렌에서 기차 1시간. 2차대전 기념' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fort Garry Horse Museum & Archives': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수 19:00-21:00 (화문의)' }, { icon: '📍', label: '위치', value: 'McGregor Armoury, Winnipeg, MB, Canada' }, { icon: '🚇', label: '교통', value: '위니펙 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'France 40 Vehicles Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '4~10월 토·일 14:00-18:00' }, { icon: '📍', label: '위치', value: 'Fismes, Marne, France' }, { icon: '🚇', label: '교통', value: '랭스에서 차량 30분. 1940년 프랑스 군용차량' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Eilat Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-14:00' }, { icon: '📍', label: '위치', value: 'Eilat, Israel' }, { icon: '🚇', label: '교통', value: '에일랏 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Eiszeit-Haus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Flensburg, Schleswig-Holstein, Germany' }, { icon: '🚇', label: '교통', value: '플렌스부르크역 도보 15분. 빙하기 지질학' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Enrico Caffi Museum of Natural Science': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Cittadella 10, Bergamo Alta, Italy' }, { icon: '🚇', label: '교통', value: '후니쿨라 베르가모 알타' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Esapolis': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via dei Colli 28, Padua, Italy' }, { icon: '🚇', label: '교통', value: '파도바역 차량 10분. 살아있는 곤충 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Essig Museum of Entomology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-12:00, 13:00-17:00' }, { icon: '📍', label: '위치', value: 'UC Berkeley Campus, CA, USA' }, { icon: '🚇', label: '교통', value: 'BART Downtown Berkeley역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galeria Luisa Strina': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-19:00, 토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Rua Padre João Manuel 755, São Paulo, Brazil' }, { icon: '🚇', label: '교통', value: '메트로 Consolação역. 브라질 대표 갤러리' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Byzantine Museum of Holy Bishopric of Tamasos and Oreinis': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Nicosia, Cyprus' }, { icon: '🚇', label: '교통', value: '니코시아 시내. 비잔틴 성화(이콘) 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Cobweb Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Gyumri, Armenia' }, { icon: '🚇', label: '교통', value: '예레반에서 기차/차량 3시간' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Ernesto Bachmann Paleontological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '1,200 ARS (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00 (동절기 ~18:00)' }, { icon: '📍', label: '위치', value: 'Villa El Chocón, Neuquén, Argentina' }, { icon: '🚇', label: '교통', value: '네우켄에서 차량 1.5시간. 기가노토사우루스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Canadian Engineers Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수 19:00-21:00 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Gagetown, NB, Canada' }, { icon: '🚇', label: '교통', value: '프레더릭턴에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Jehangir Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-19:00' }, { icon: '📍', label: '위치', value: '161B M.G. Road, Kala Ghoda, Mumbai, India' }, { icon: '🚇', label: '교통', value: 'CST역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Entomological and Natural History Museum of Vicuña': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Vicuña, Elqui Valley, Chile' }, { icon: '🚇', label: '교통', value: '라세레나에서 차량 1시간. 엘키 밸리 곤충학' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Environmental History Museum of Almería': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-14:00 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Alcudia de Monteagud, Almería, Spain' }, { icon: '🚇', label: '교통', value: '알메리아에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Frost Entomological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:30-16:30' }, { icon: '📍', label: '위치', value: 'Penn State University, PA, USA' }, { icon: '🚇', label: '교통', value: '스테이트 칼리지 대학 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'David Hall Art Gallery Fort Kochi': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-19:00' }, { icon: '📍', label: '위치', value: 'Fort Kochi, Ernakulam, Kerala, India' }, { icon: '🚇', label: '교통', value: '포트코치 도보. 인도 비엔날레 갤러리' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fruttuaria': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '토·일 14:30-18:30' }, { icon: '📍', label: '위치', value: 'San Benigno Canavese, Piedmont, Italy' }, { icon: '🚇', label: '교통', value: '토리노에서 차량 30분. 중세 수도원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
