const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Small galleries/obscure - with better detail
    '1912–1913 War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-15:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Dodoni Municipality, Ioannina, Greece' }, { icon: '🚇', label: '교통', value: '이오안니나에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Balkan Wars Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-15:00' }, { icon: '📍', label: '위치', value: 'Gefyra, Kilkis, Greece' }, { icon: '🚇', label: '교통', value: '테살로니키에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ban Kao national museum': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Ban Kao, Kanchanaburi, Thailand' }, { icon: '🚇', label: '교통', value: '칸차나부리에서 차량 45분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bror Hjorths Hus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 SEK (~$8)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Norbyvägen 26, Uppsala, Sweden' }, { icon: '🚇', label: '교통', value: '웁살라역 버스 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bullecourt 1917, Jean and Denise Letaille museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 10:00-17:30' }, { icon: '📍', label: '위치', value: '1 Rue d\'Arras, Bullecourt, Pas-de-Calais, France' }, { icon: '🚇', label: '교통', value: '아라스에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Caillou Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Genappe (Vieux-Genappe), Walloon Brabant, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼셀에서 차량 40분 (워털루 전장 인근)' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Calgary Highlanders Regimental Museum and Archives': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Mewata Armoury, Calgary, AB, Canada' }, { icon: '🚇', label: '교통', value: '캘거리 CTrain Downtown West역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Carleton Martello Tower': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $4 CAD' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-17:30' }, { icon: '📍', label: '위치', value: '454 Whipple Street, Saint John, NB, Canada' }, { icon: '🚇', label: '교통', value: '세인트존 시내에서 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Carmelite Monastery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Karmelitergasse 1, Frankfurt, Germany' }, { icon: '🚇', label: '교통', value: 'U-Bahn Willy-Brandt-Platz역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa del Arte': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토 10:00-14:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Chacabuco esq. Larenas, Concepción, Chile' }, { icon: '🚇', label: '교통', value: '콘셉시온 대학교 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Escuela Museo de Sitio Gabriela Mistral': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Montegrande, Paiguano, Elqui Valley, Chile' }, { icon: '🚇', label: '교통', value: '라 세레나에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Château des Baux': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 어린이 8€' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-18:30 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Les Baux-de-Provence, Bouches-du-Rhône, France' }, { icon: '🚇', label: '교통', value: '아를에서 차량 20분 / 아비뇽에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Chengdu Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (예약 필수)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Chenghua District, Chengdu, Sichuan, China' }, { icon: '🚇', label: '교통', value: '청두 지하철 7호선 North Railway Station역' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Chiang Mai National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Superhighway Road, Chiang Mai, Thailand' }, { icon: '🚇', label: '교통', value: '치앙마이 구시가지에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Chao Sam Phraya National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '100 THB (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Rojana Road, Ayutthaya, Thailand' }, { icon: '🚇', label: '교통', value: '아유타야역에서 툭툭 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Major museums
    'Cleveland Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수·금 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '11150 East Boulevard, Cleveland, OH, USA' }, { icon: '🚇', label: '교통', value: 'RTA Red Line University Circle역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Cleveland Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $17, 학생 $15. 매월 셋째 일 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (수 ~21:00)' }, { icon: '📍', label: '위치', value: '1 Wade Oval Drive, Cleveland, OH, USA' }, { icon: '🚇', label: '교통', value: 'RTA Red Line University Circle역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Cloth Hall, Ypres': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 6€ (In Flanders Fields Museum)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00. 월 휴관 (11~3월)' }, { icon: '📍', label: '위치', value: 'Grote Markt 34, Ypres, Belgium' }, { icon: '🚇', label: '교통', value: '이프르역 도보 10분. 브뤼셀에서 기차 2시간' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Colditz Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Schloßgasse 1, Colditz, Saxony, Germany' }, { icon: '🚇', label: '교통', value: '라이프치히에서 기차+버스 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Collegio del Cambio': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-12:30, 14:30-17:30. 일 09:00-13:00' }, { icon: '📍', label: '위치', value: 'Corso Vannucci 25, Perugia, Italy' }, { icon: '🚇', label: '교통', value: '페루자 미니메트로 Pincetto 종점 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Colombian National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4,000 COP (~$1), 학생 무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00, 일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Carrera 7 No. 28-66, Bogotá, Colombia' }, { icon: '🚇', label: '교통', value: 'TransMilenio Museo Nacional역' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Colosseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€. 콤비(포로 로마노+팔라티노) 포함. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-일몰 1시간 전 (계절별 16:30~19:15)' }, { icon: '📍', label: '위치', value: 'Piazza del Colosseo, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 B선 Colosseo역 직결' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Columbia Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1515 Main Street, Columbia, SC, USA' }, { icon: '🚇', label: '교통', value: '컬럼비아 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Contemporary Art Centre': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€, 학생 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Vokiečių g. 2, Vilnius, Lithuania' }, { icon: '🚇', label: '교통', value: '빌뉴스 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Contemporary Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '555 Nelson Street, Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: 'SkyTrain Yaletown-Roundhouse역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Contemporary Art Museum of Caracas': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Parque Central, Caracas, Venezuela' }, { icon: '🚇', label: '교통', value: '메트로 Bellas Artes역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Contemporary Arts Museum Houston': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00 (목 ~21:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: '5216 Montrose Blvd, Houston, TX, USA' }, { icon: '🚇', label: '교통', value: 'METRORail Museum District역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Coptic Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 EGP (~$3), 학생 50 EGP' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Mar Girgis, Old Cairo, Egypt' }, { icon: '🚇', label: '교통', value: '카이로 메트로 Mar Girgis역 직결' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Croatian History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 20 HRK (~$3)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00, 토·일 10:00-13:00' }, { icon: '📍', label: '위치', value: 'Matoševa 9, Zagreb, Croatia' }, { icon: '🚇', label: '교통', value: '자그레브 상부 마을 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Croatian Natural History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 20 HRK (~$3)' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 10:00-13:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Demetrova 1, Zagreb, Croatia' }, { icon: '🚇', label: '교통', value: '자그레브 상부 마을 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Crypta Balbi': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€. Museo Nazionale 콤비 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:45. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via delle Botteghe Oscure 31, Rome, Italy' }, { icon: '🚇', label: '교통', value: '버스 Largo Argentina / 트램 8' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Curtius Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€, 학생 5€' }, { icon: '🕐', label: '운영시간', value: '월·수~일 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Quai de Maastricht 13, Liège, Belgium' }, { icon: '🚇', label: '교통', value: '리에주 기예맹역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Cyprus Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4.50€' }, { icon: '🕐', label: '운영시간', value: '화~금 08:00-18:00, 토 09:00-17:00, 일 10:00-13:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mouseiou 1, Nicosia, Cyprus' }, { icon: '🚇', label: '교통', value: '니코시아 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Czartoryski Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 25 PLN (~$6), 학생 15 PLN. 화요일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'ul. Św. Jana 19, Kraków, Poland' }, { icon: '🚇', label: '교통', value: '크라쿠프 구시가지 도보 (플로리안 문 인근)' }, { icon: '⏱️', label: '관람시간', value: '2시간' }], website: 'https://www.mnk.pl/' },
    'D-Day Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7.90€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Place du 6 Juin, Arromanches-les-Bains, Normandy, France' }, { icon: '🚇', label: '교통', value: '바이외에서 버스 74번 / 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Daegu National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00 (토·일 ~19:00). 월 휴관' }, { icon: '📍', label: '위치', value: '대구광역시 수성구 청호로 321' }, { icon: '🚇', label: '교통', value: '대구 지하철 2호선 대공원역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Danish Railway Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 90 DKK (~$13), 학생 60 DKK' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Dannebrogsgade 24, Odense, Denmark' }, { icon: '🚇', label: '교통', value: '오덴세역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Danish War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Tøjhusgade 3, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: '메트로 Christianshavn역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'David Collection': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kronprinsessegade 30, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: 'Nørreport S-tog역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Darwin Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD$18, 어린이 $8' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00' }, { icon: '📍', label: '위치', value: 'East Point, Darwin, NT, Australia' }, { icon: '🚇', label: '교통', value: '다윈 시내에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Como Civic Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Diaz 84, Como, Italy' }, { icon: '🚇', label: '교통', value: '코모 산조반니역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Copertino Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Castello, Copertino, Lecce, Italy' }, { icon: '🚇', label: '교통', value: '레체에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civitavecchia national archaeological museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Largo Cavour, Civitavecchia, Rome, Italy' }, { icon: '🚇', label: '교통', value: '치비타베키아역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civitas Classis': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Classense 29, Classe, Ravenna, Italy' }, { icon: '🚇', label: '교통', value: '라벤나에서 버스 4번' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cold war museum Stevnsfort': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 DKK (~$17)' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Korsnæbvej 60, Rødvig Stevns, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Crownhill Fort': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8.50, 어린이 £5' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Crownhill Fort Road, Plymouth, Devon, UK' }, { icon: '🚇', label: '교통', value: '플리머스 시내에서 버스 / 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Cumbria\'s Museum of Military Life': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Carlisle Castle, Carlisle, Cumbria, UK' }, { icon: '🚇', label: '교통', value: '칼라일역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Dartmouth Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8, 어린이 £4.80' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Castle Road, Dartmouth, Devon, UK' }, { icon: '🚇', label: '교통', value: '다트머스 항구에서 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Corgarff Castle': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £6, 어린이 £3.60' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 09:30-17:30' }, { icon: '📍', label: '위치', value: 'Strathdon, Aberdeenshire, Scotland, UK' }, { icon: '🚇', label: '교통', value: '애버딘에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castle Rushen': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £10' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Castletown, Isle of Man' }, { icon: '🚇', label: '교통', value: '더글러스에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cornwall\'s Army Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £5, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00, 주말 예약' }, { icon: '📍', label: '위치', value: 'The Keep, Bodmin, Cornwall, UK' }, { icon: '🚇', label: '교통', value: '보드민 Pkwy역에서 택시/버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Coudehard-Montormel Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 09:30-18:00' }, { icon: '📍', label: '위치', value: 'Les Hayettes, Coudehard, Normandy, France' }, { icon: '🚇', label: '교통', value: '캉에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cregneash Village Folk Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '부활절~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Cregneash, Isle of Man' }, { icon: '🚇', label: '교통', value: '더글러스에서 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civil War Soldiers Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $6, 어린이 $4' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '108 South Palafox Place, Pensacola, FL, USA' }, { icon: '🚇', label: '교통', value: '펜서콜라 다운타운' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cold War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10, 학생 $7' }, { icon: '🕐', label: '운영시간', value: '금~일 10:00-17:00' }, { icon: '📍', label: '위치', value: '7142 Lineweaver Road, Warrenton, VA, USA' }, { icon: '🚇', label: '교통', value: '워싱턴DC에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Comox Air Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'CFB Comox, BC, Canada' }, { icon: '🚇', label: '교통', value: '빅토리아에서 차량 3시간 / 코목스 공항' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Commonwealth Air Training Plan Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7 CAD' }, { icon: '🕐', label: '운영시간', value: '5~9월 월~토 09:00-17:00, 일·공휴일 13:00-17:00' }, { icon: '📍', label: '위치', value: 'Brandon Municipal Airport, MB, Canada' }, { icon: '🚇', label: '교통', value: '브랜던 시내에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Concordiese national archeological museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '월 14:00-19:00, 화~일 08:30-19:30' }, { icon: '📍', label: '위치', value: 'Via Seminario 26, Portogruaro, Venice, Italy' }, { icon: '🚇', label: '교통', value: '포르토그루아로역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Citadel Hill': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $11.70 CAD (6~9월). 그 외 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '5425 Sackville St, Halifax, NS, Canada' }, { icon: '🚇', label: '교통', value: '핼리팩스 다운타운 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Civic Pinacotheca': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-12:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Pieve di Cento, Bologna, Italy' }, { icon: '🚇', label: '교통', value: '볼로냐에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Civic Pinacotheca of Reggio Calabria': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Largo Tommaso Campanella, Reggio Calabria, Italy' }, { icon: '🚇', label: '교통', value: '레조칼라브리아 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civico Museo Archeologico': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 14:30-18:00 또는 예약' }, { icon: '📍', label: '위치', value: 'Arsago Seprio, Varese, Italy' }, { icon: '🚇', label: '교통', value: '밀라노 말펜사에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Civicampomarano Castle': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-13:00' }, { icon: '📍', label: '위치', value: 'Civitacampomarano, Campobasso, Italy' }, { icon: '🚇', label: '교통', value: '캄포바소에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Chapelle des Cordeliers': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-12:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sarrebourg, Moselle, France' }, { icon: '🚇', label: '교통', value: '사루부르 SNCF역 도보 5분. 샤갈 스테인드글라스' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Coalhouse Fort': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일요일 11:00-16:00 (여름)' }, { icon: '📍', label: '위치', value: 'Princess Margaret Road, East Tilbury, Essex, UK' }, { icon: '🚇', label: '교통', value: 'East Tilbury역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Clifford Road Air Raid Shelter': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Ipswich, Suffolk, UK' }, { icon: '🚇', label: '교통', value: '이프스위치역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Cole Museum of Zoology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'University of Reading, RG6, UK' }, { icon: '🚇', label: '교통', value: '레딩역 버스 / 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cloister of the Scalzo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월·목·토 08:15-13:50' }, { icon: '📍', label: '위치', value: 'Via Cavour 69, Florence, Italy' }, { icon: '🚇', label: '교통', value: 'San Marco 광장 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '20분' }] },
    'Danish Museum of Hunting and Forestry': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 DKK (~$12)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Folehavevej 15-17, Hørsholm, Denmark' }, { icon: '🚇', label: '교통', value: 'S-tog Rungsted Kyst역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cavalry Tank Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-13:00, 14:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Ahmednagar, Maharashtra, India' }, { icon: '🚇', label: '교통', value: '아메드나가르 시내' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Crisbecq Battery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '4~10월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Saint-Marcouf, Manche, Normandy, France' }, { icon: '🚇', label: '교통', value: 'Utah Beach에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Colorado School of Mines Geology Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-16:00. 일 휴관' }, { icon: '📍', label: '위치', value: '1310 Maple Street, Golden, CO, USA' }, { icon: '🚇', label: '교통', value: '덴버에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Combined Military Services Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £6, 어린이 £3' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Maldon, Essex, UK' }, { icon: '🚇', label: '교통', value: '첼름스퍼드에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Cumae amphitheatre': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€ (쿠마이 고고학 유적 포함)' }, { icon: '🕐', label: '운영시간', value: '수~월 09:00-일몰 1시간 전. 화 휴관' }, { icon: '📍', label: '위치', value: 'Bacoli, Naples, Italy' }, { icon: '🚇', label: '교통', value: '나폴리에서 Cumana 전차 Fusaro역 + 도보' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Copenhagen Contemporary': { vi: [{ icon: '🎫', label: '입장료', value: '성인 120 DKK (~$17). 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Refshalevej 173A, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: '메트로 Christianshavn + 도보 / 워터버스' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }], website: 'https://copenhagencontemporary.org/' },
    'Crustumerium archaeological park': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '가이드 투어 예약제' }, { icon: '📍', label: '위치', value: 'Via della Marcigliana, Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마 북부 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cultural Park of West Sumatra': { vi: [{ icon: '🎫', label: '입장료', value: '5,000 IDR (~$0.30)' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-17:00' }, { icon: '📍', label: '위치', value: 'Padang, West Sumatra, Indonesia' }, { icon: '🚇', label: '교통', value: '파당 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Currahee Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00' }, { icon: '📍', label: '위치', value: '160 N Alexander St, Toccoa, GA, USA' }, { icon: '🚇', label: '교통', value: '애틀랜타에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Boxted Airfield Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '일요일 10:00-16:00 (여름)' }, { icon: '📍', label: '위치', value: 'Langham, Colchester, Essex, UK' }, { icon: '🚇', label: '교통', value: '콜체스터에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        let r;
        if (info.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, info.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
