const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Musée + other notable from remaining
    "Musée d'Art moderne de Troyes": { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '14 Place Saint-Pierre, Troyes, France' }, { icon: '🚇', label: '교통', value: '트루아역 도보 15분. 피에르&드니스 레비 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Musée de l'Air": { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기체 내부 방문 유료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Aéroport Paris-Le Bourget, Le Bourget, France' }, { icon: '🚇', label: '교통', value: 'RER B Le Bourget역+버스 152. 세계 최초 항공박물관' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    "Musée de l'Hospice Comtesse": { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '월 14:00-18:00, 수~일 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '32 Rue de la Monnaie, Lille, France' }, { icon: '🚇', label: '교통', value: '릴 메트로 Rihour역 도보 5분. 13세기 병원' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "musée d'Art contemporain du Val-de-Marne": { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~금 12:00-19:00, 토·일 12:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Place de la Libération, Vitry-sur-Seine, France' }, { icon: '🚇', label: '교통', value: '메트로 8 Liberté역. MAC/VAL 파리 근교 현대미술' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Musée d'histoire naturelle et d'ethnographie de Colmar": { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-12:00, 14:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '11 Rue Turenne, Colmar, France' }, { icon: '🚇', label: '교통', value: '콜마르역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Dunkerque': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-12:30, 14:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place du Général de Gaulle, Dunkirk, France' }, { icon: '🚇', label: '교통', value: '됭케르크역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des beaux-arts de La Chaux-de-Fonds': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 9' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '33 Rue des Musées, La Chaux-de-Fonds, Switzerland' }, { icon: '🚇', label: '교통', value: '라쇼드퐁역 도보 10분. 르 코르뷔지에 고향' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Valenciennes': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Boulevard Watteau, Valenciennes, France' }, { icon: '🚇', label: '교통', value: '발랑시엔역 도보 10분. 와토 탄생지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée Bossuet': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-12:00, 14:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '5 Place Charles de Gaulle, Meaux, France' }, { icon: '🚇', label: '교통', value: '모역 도보 5분. 브리 지방 미술' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "Musée de la Légion d'honneur": { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 13:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '2 Rue de la Légion d\'Honneur, Paris, France' }, { icon: '🚇', label: '교통', value: 'RER C Musée d\'Orsay역. 오르세 맞은편' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Chartres': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-12:30, 14:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: '29 Cloître Notre-Dame, Chartres, France' }, { icon: '🚇', label: '교통', value: '샤르트르역 도보 10분. 대성당 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Chambéry': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-12:00, 14:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Place du Palais de Justice, Chambéry, France' }, { icon: '🚇', label: '교통', value: '샹베리역 도보 10분. 이탈리아 회화' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Carcassonne': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-12:15, 14:00-17:00 (하계 ~18:00)' }, { icon: '📍', label: '위치', value: '1 Rue de Verdun, Carcassonne, France' }, { icon: '🚇', label: '교통', value: '카르카손역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des beaux-arts de Mulhouse': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~월 13:00-18:30. 화 휴관' }, { icon: '📍', label: '위치', value: '4 Place Guillaume Tell, Mulhouse, France' }, { icon: '🚇', label: '교통', value: '뮐루즈역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Béziers': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Place de la Révolution, Béziers, France' }, { icon: '🚇', label: '교통', value: '베지에역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée des Beaux-Arts de Troyes': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '21 Rue Chrétien de Troyes, Troyes, France' }, { icon: '🚇', label: '교통', value: '트루아 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "musée des Beaux-Arts et d'Archéologie de Vienne": { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-13:00, 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Place de Miremont, Vienne, France' }, { icon: '🚇', label: '교통', value: '비엔역 도보 10분. 갈로-로마 유물' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "Musée des Collections Historiques de la Préfecture de Police": { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:30-17:00, 토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '4 Rue de la Montagne Sainte-Geneviève, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 10 Maubert-Mutualité역. 파리 경찰 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée Dobrée': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '18 Rue Voltaire, Nantes, France' }, { icon: '🚇', label: '교통', value: '트램 1 Médiathèque역. 2022 리뉴얼' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Musée de Minéralogie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~금 13:30-18:00, 토 10:00-12:30, 14:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '60 Boulevard Saint-Michel, Paris, France' }, { icon: '🚇', label: '교통', value: 'RER B Luxembourg역. 에콜 데 민 광물학' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    "musée des impressionnismes Giverny": { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '4~11월 매일 10:00-18:00' }, { icon: '📍', label: '위치', value: '99 Rue Claude Monet, Giverny, France' }, { icon: '🚇', label: '교통', value: '파리에서 기차 Vernon역+셔틀. 모네 정원 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Geológico del Seminario de Barcelona': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (사전 예약)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-14:00' }, { icon: '📍', label: '위치', value: 'C/ de la Diputació 231, Barcelona, Spain' }, { icon: '🚇', label: '교통', value: '메트로 Passeig de Gràcia역. 19세기 광물 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Musée du Montparnasse': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '수~일 12:30-19:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '21 Avenue du Maine, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 6 Montparnasse–Bienvenüe역' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'Museo di scienze planetarie': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '금·토 10:00-13:00, 15:00-19:00, 일 10:00-13:00, 15:00-19:00' }, { icon: '📍', label: '위치', value: 'Via Galcianese 20, Prato, Italy' }, { icon: '🚇', label: '교통', value: '프라토역 도보 15분. 운석 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
