const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const d = {
    // Small/obscure first (quick entries)
    '103 West 135th Street': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Manhattan, NY, USA' }, { icon: '🚇', label: '교통', value: '2/3 135th St역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    '180 Projects': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 12:00-17:00' }, { icon: '📍', label: '위치', value: 'Sault Ste. Marie, ON, Canada' }, { icon: '🚇', label: '교통', value: '시내 중심부' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    '1blick': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 개방' }, { icon: '📍', label: '위치', value: 'Hallein, Salzburg, Austria' }, { icon: '🚇', label: '교통', value: '잘츠부르크에서 S3 기차 20분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'A la Reine Margot': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (앤티크 갤러리)' }, { icon: '🕐', label: '운영시간', value: '화~토 10:30-18:30' }, { icon: '📍', label: '위치', value: '7 Quai de Conti, Paris 6th, France' }, { icon: '🚇', label: '교통', value: '메트로 Pont Neuf역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Alfred Schmela Galerie': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '전시 기간 중 화~토 11:00-18:00' }, { icon: '📍', label: '위치', value: 'Mutter-Ey-Straße 3, Düsseldorf, Germany' }, { icon: '🚇', label: '교통', value: '뒤셀도르프 Altstadt 도보' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Alvar-Aalto-Kulturhaus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Porschestraße 45, Wolfsburg, Germany' }, { icon: '🚇', label: '교통', value: '볼프스부르크역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Major museums
    'British Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도). 기부 환영' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (금 ~20:30)' }, { icon: '📍', label: '위치', value: 'Great Russell Street, London WC1B 3DG, UK' }, { icon: '🚇', label: '교통', value: 'Russell Square / Holborn / Tottenham Court Road역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '3-5시간' }] },
    'Brooklyn Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $16, 학생 $10. 매월 첫째 토 무료' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-18:00 (목 ~22:00). 월·화 휴관' }, { icon: '📍', label: '위치', value: '200 Eastern Pkwy, Brooklyn, NY, USA' }, { icon: '🚇', label: '교통', value: '2/3 Eastern Parkway–Brooklyn Museum역' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Brukenthal National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 30 RON (~$7)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piata Mare 4-5, Sibiu, Romania' }, { icon: '🚇', label: '교통', value: '시비우 구시가지 광장' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Budapest History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2,400 HUF (~$7)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Buda Castle, Wing E, Budapest, Hungary' }, { icon: '🚇', label: '교통', value: '버스 16 / 케이블카 Clark Ádám tér' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Bundeswehr Military History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '월·수·금 10:00-18:00, 목 10:00-21:00, 토·일 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Olbrichtplatz 2, Dresden, Germany' }, { icon: '🚇', label: '교통', value: '드레스덴 트램 7,8번 Stauffenbergallee' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    "Bunk'Art": { vi: [{ icon: '🎫', label: '입장료', value: '성인 500 ALL (~$5)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Linza, Tirana, Albania' }, { icon: '🚇', label: '교통', value: '티라나 시내에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Bunk'Art 2": { vi: [{ icon: '🎫', label: '입장료', value: '성인 500 ALL (~$5)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Rruga Abdi Toptani, Tirana, Albania' }, { icon: '🚇', label: '교통', value: '티라나 시내 중심' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Busan Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: '부산광역시 해운대구 APEC로 58' }, { icon: '🚇', label: '교통', value: '부산 지하철 2호선 시립미술관역 5번 출구' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Buyeo National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00 (토·일 ~19:00). 월 휴관' }, { icon: '📍', label: '위치', value: '충남 부여군 부여읍 금성로 5' }, { icon: '🚇', label: '교통', value: '부여 시내버스 / 대전에서 고속버스 1시간' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Bröhan Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 할인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Schloßstraße 1a, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Sophie-Charlotte-Platz역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Burnaby Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-16:30, 토~일 12:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '6344 Deer Lake Ave, Burnaby, BC, Canada' }, { icon: '🚇', label: '교통', value: 'SkyTrain Metrotown역 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Canada Aviation and Space Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $18 CAD, 학생 $14' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '11 Aviation Pkwy, Ottawa, ON, Canada' }, { icon: '🚇', label: '교통', value: '오타와 시내에서 버스 129' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Canada Science and Technology Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $22 CAD, 어린이 $15' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '1867 St Laurent Blvd, Ottawa, ON, Canada' }, { icon: '🚇', label: '교통', value: '오타와 시내에서 버스' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Canadian Museum for Human Rights': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $18 CAD, 학생 $12' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '85 Israel Asper Way, Winnipeg, MB, Canada' }, { icon: '🚇', label: '교통', value: '위니펙 시내 The Forks 인근' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Canadian Museum of History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $23 CAD, 학생 $19' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00 (목 ~20:00)' }, { icon: '📍', label: '위치', value: '100 Laurier St, Gatineau, QC, Canada' }, { icon: '🚇', label: '교통', value: '오타와 시내에서 도보 15분 (다리 건너편)' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Canadian War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $21 CAD, 학생 $17. 목 17시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00 (목 ~20:00)' }, { icon: '📍', label: '위치', value: '1 Vimy Place, Ottawa, ON, Canada' }, { icon: '🚇', label: '교통', value: '오타와 시내에서 버스 / 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Canadian Warplane Heritage Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $16 CAD' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: '9280 Airport Rd, Mount Hope, Hamilton, ON, Canada' }, { icon: '🚇', label: '교통', value: '해밀턴 공항 인근' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Canberra Museum and Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'London Circuit, Canberra, ACT, Australia' }, { icon: '🚇', label: '교통', value: '캔버라 Civic 중심부' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'CAPC musée d\'art contemporain de Bordeaux': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 매월 첫째 일요일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: '7 Rue Ferrère, Bordeaux, France' }, { icon: '🚇', label: '교통', value: '트램 B선 CAPC 정류장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Capitoline Museums': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€, 할인 13€. 매월 첫째 일요일 무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-19:30' }, { icon: '📍', label: '위치', value: 'Piazza del Campidoglio, Rome, Italy' }, { icon: '🚇', label: '교통', value: '버스 Piazza Venezia / 메트로 B Colosseo 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Carpet Museum of Iran': { vi: [{ icon: '🎫', label: '입장료', value: '300,000 IRR (~$1)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Dr. Fatemi Ave, Tehran, Iran' }, { icon: '🚇', label: '교통', value: '테헤란 메트로 Ferdowsi역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Buonarroti': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Via Ghibellina 70, Florence, Italy' }, { icon: '🚇', label: '교통', value: '산타크로체 광장 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castel del Monte': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:45 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Contrada Castel del Monte, Andria, BT, Italy' }, { icon: '🚇', label: '교통', value: '바리에서 차량 1시간 / 안드리아에서 셔틀버스' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Castelvecchio Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€. 매월 첫째 일요일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 13:30-19:30' }, { icon: '📍', label: '위치', value: 'Corso Castelvecchio 2, Verona, Italy' }, { icon: '🚇', label: '교통', value: '베로나 포르타누오바역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Castle Rushen': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £10, 어린이 £5' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Castletown, Isle of Man' }, { icon: '🚇', label: '교통', value: '더글러스에서 버스 1, 2번' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Caen Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '성인 19.80€, 학생 17.30€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:30 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Esplanade Général Eisenhower, Caen, France' }, { icon: '🚇', label: '교통', value: '캉역에서 트램 T1 + 버스 / 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Cayman Islands National Museum': { vi: [{ icon: '🎫', label: '입장료', value: 'CI$10 (~$12 USD)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00, 토 10:00-14:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'George Town, Grand Cayman' }, { icon: '🚇', label: '교통', value: '조지타운 항구 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Center of the Tokyo Raids and War Damage': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 12:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Kitasuna, Koto-ku, Tokyo, Japan' }, { icon: '🚇', label: '교통', value: '도에이 신주쿠선 Ojima역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Central Armed Forces Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 250₽ (~$3)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Sovetskoy Armii 2, Moscow, Russia' }, { icon: '🚇', label: '교통', value: '메트로 Dostoevskaya역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Central Air Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300₽ (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '수~일 09:30-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Monino, Moscow Oblast, Russia' }, { icon: '🚇', label: '교통', value: '모스크바에서 전기철도 Monino역' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Castello Normanno-Svevo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Federico II, Bari, Italy' }, { icon: '🚇', label: '교통', value: '바리 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bahrain National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 1 BHD (~$2.60)' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-20:00' }, { icon: '📍', label: '위치', value: 'Al Fatih Highway, Manama, Bahrain' }, { icon: '🚇', label: '교통', value: '마나마 시내 택시' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Buenos Aires Holocaust Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00, 일 11:00-19:00. 토 휴관' }, { icon: '📍', label: '위치', value: 'Montevideo 919, Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: 'Subte D Callao역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Bill Reid Gallery of Northwest Coast Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $13 CAD' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00' }, { icon: '📍', label: '위치', value: '639 Hornby St, Vancouver, BC' }, { icon: '🚇', label: '교통', value: 'Burrard역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Brunei Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토~목 09:00-17:00, 금 09:00-11:30, 14:30-17:00' }, { icon: '📍', label: '위치', value: 'Jalan Kota Batu, Brunei' }, { icon: '🚇', label: '교통', value: 'BSB에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Byzantine Museum of Antivouniotissa': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-15:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Arseniou Street, Corfu, Greece' }, { icon: '🚇', label: '교통', value: '코르푸 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Butser Ancient Farm': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £10, 어린이 £7' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Chalton Lane, Chalton, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '피터스필드에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Cabinet des estampes et des dessins': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~토 14:00-18:00' }, { icon: '📍', label: '위치', value: '5 Place du Château, Strasbourg, France' }, { icon: '🚇', label: '교통', value: '트램 C/D/E Langstross/Grand Rue역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'California State Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1119 2nd St, Sacramento, CA, USA' }, { icon: '🚇', label: '교통', value: '새크라멘토 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Canadian Clay and Glass Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '수~일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '25 Caroline St N, Waterloo, ON, Canada' }, { icon: '🚇', label: '교통', value: 'ION LRT 이용' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cambridge Art Galleries': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Cambridge, ON, Canada' }, { icon: '🚇', label: '교통', value: '토론토에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Cape Canaveral Space Force Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (Kennedy Space Center 별도)' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-14:00 (예약 필수)' }, { icon: '📍', label: '위치', value: 'Cape Canaveral SFS, FL, USA' }, { icon: '🚇', label: '교통', value: '올랜도에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Casa Romei': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Savonarola 30, Ferrara, Italy' }, { icon: '🚇', label: '교통', value: '페라라역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casamari Abbey': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-12:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Veroli, Frosinone, Italy' }, { icon: '🚇', label: '교통', value: '프로시노네에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castello Bufalini': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'San Giustino, Perugia, Italy' }, { icon: '🚇', label: '교통', value: '페루자에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castello di Capua': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-13:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Gambatesa, Campobasso, Italy' }, { icon: '🚇', label: '교통', value: '캄포바소에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castello Malaspina': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Bobbio, Piacenza, Italy' }, { icon: '🚇', label: '교통', value: '피아첸차에서 차량 50분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castle and Regimental Museum, Monmouth': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Castle Hill, Monmouth, Wales, UK' }, { icon: '🚇', label: '교통', value: '몬머스 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castle of Lagopesole': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-13:00, 15:30-18:30' }, { icon: '📍', label: '위치', value: 'Avigliano, Potenza, Italy' }, { icon: '🚇', label: '교통', value: '포텐자에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castle of Moncalieri': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '금~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Piazza Baden Baden 4, Moncalieri, Italy' }, { icon: '🚇', label: '교통', value: '토리노에서 버스 45, 67번' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castle of Racconigi': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Morosini 3, Racconigi, Italy' }, { icon: '🚇', label: '교통', value: '토리노에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Castle of Trani': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-19:30' }, { icon: '📍', label: '위치', value: 'Piazza Re Manfredi 16, Trani, BT, Italy' }, { icon: '🚇', label: '교통', value: '트라니역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Carcere Borbonico': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Avellino, Campania, Italy' }, { icon: '🚇', label: '교통', value: '아벨리노 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Bellezza': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Capo di Bove': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-일몰. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Appia Antica 222, Rome, Italy' }, { icon: '🚇', label: '교통', value: '아피아 안티카 공원 내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Cenacolo di Ognissanti': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (예약)' }, { icon: '🕐', label: '운영시간', value: '월·토 09:00-12:00' }, { icon: '📍', label: '위치', value: 'Borgo Ognissanti 42, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 산타마리아 노벨라역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Centre for Contemporary Photography': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~금 11:00-17:00, 토~일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '404 George St, Fitzroy, Melbourne, Australia' }, { icon: '🚇', label: '교통', value: '트램 86 Fitzroy 정류장' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Centre for International Light Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~금 14:00-17:00, 토~일 12:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lindenplatz 1, Unna, Germany' }, { icon: '🚇', label: '교통', value: '도르트문트에서 S4 Unna역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    "Centre d'Histoire de la Résistance et de la Déportation": { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '14 Avenue Berthelot, Lyon 7th, France' }, { icon: '🚇', label: '교통', value: '메트로 B Jean Macé역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Centre de la mémoire d'Oradour": { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00 (계절별 상이)' }, { icon: '📍', label: '위치', value: 'Oradour-sur-Glane, Haute-Vienne, France' }, { icon: '🚇', label: '교통', value: '리모주에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Capel Battery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00 (여름)' }, { icon: '📍', label: '위치', value: 'Western Heights, Dover, Kent, UK' }, { icon: '🚇', label: '교통', value: '도버 프리오리역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Buckinghamshire Military Museum Trust': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '수 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Buckingham, UK' }, { icon: '🚇', label: '교통', value: '런던에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Brandts Museum of Photographic Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 DKK (~$12)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Brandts Passage 37, Odense, Denmark' }, { icon: '🚇', label: '교통', value: '오덴세역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bor Hjorths Hus': { vi: [{ icon: '🎫', label: '입장료', value: '성인 80 SEK (~$8)' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Norbyvägen 26, Uppsala, Sweden' }, { icon: '🚇', label: '교통', value: '웁살라역 버스 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Basilica Church of Santa Maria Maggiore': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-18:00' }, { icon: '📍', label: '위치', value: 'Tuscania, Viterbo, Italy' }, { icon: '🚇', label: '교통', value: '비테르보에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Breendonk Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 6€' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:30' }, { icon: '📍', label: '위치', value: 'Brandstraat 57, Willebroek, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼셀에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Castle of St. John': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £3' }, { icon: '🕐', label: '운영시간', value: '4~9월 매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Stranraer, Dumfries and Galloway, Scotland, UK' }, { icon: '🚇', label: '교통', value: '스트란라어역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Castle of San Terenzo': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외)' }, { icon: '📍', label: '위치', value: 'Lerici, La Spezia, Italy' }, { icon: '🚇', label: '교통', value: '라스페치아에서 버스 L' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Cathedral of Grottaferrata': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 06:00-18:00' }, { icon: '📍', label: '위치', value: 'Grottaferrata, Rome, Italy' }, { icon: '🚇', label: '교통', value: '로마에서 COTRAL 버스 30분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Casa Museo Isla Negra': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8,000 CLP (~$9)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Isla Negra, El Quisco, Chile' }, { icon: '🚇', label: '교통', value: '산티아고에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Museo La Chascona': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8,000 CLP (~$9)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Fernando Márquez de la Plata 0192, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Baquedano역 도보 10분 (Bellavista 지구)' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Museo Eduardo Frei Montalva': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-13:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Providencia, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 Tobalaba역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Casa Museo Delia del Carril': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'La Reina, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '산티아고 시내에서 차량' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Capodimonte park': { vi: [{ icon: '🎫', label: '입장료', value: '공원 무료. 미술관 성인 12€' }, { icon: '🕐', label: '운영시간', value: '목~화 08:30-19:30. 수 휴관' }, { icon: '📍', label: '위치', value: 'Via Miano 2, Naples, Italy' }, { icon: '🚇', label: '교통', value: '나폴리 메트로 1 Museo역 + 셔틀버스' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Centre A': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: '밴쿠버 차이나타운' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Caulonia': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'Monasterace, Reggio Calabria, Italy' }, { icon: '🚇', label: '교통', value: '로크리에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bunkermuseum Hanstholm': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 DKK (~$15)' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Molevej 29, Hanstholm, Denmark' }, { icon: '🚇', label: '교통', value: '틱스테드에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Bunkermuseet Hirtshals': { vi: [{ icon: '🎫', label: '입장료', value: '성인 60 DKK (~$9)' }, { icon: '🕐', label: '운영시간', value: '6~8월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Hirtshals, Hjørring, Denmark' }, { icon: '🚇', label: '교통', value: '히르트할스 항구 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Burke Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 13:00-16:00' }, { icon: '📍', label: '위치', value: 'Beechworth, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '멜버른에서 차량 3시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Carrière Wellington': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7.50€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-12:30, 13:30-18:00' }, { icon: '📍', label: '위치', value: 'Rue Delétoille, Arras, France' }, { icon: '🚇', label: '교통', value: '아라스역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Canadian Centre for the Great War': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10 CAD' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '몬트리올 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bragin museum of history and art gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5 BYN (~$2)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Brahin, Gomel Region, Belarus' }, { icon: '🚇', label: '교통', value: '고멜에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Câmara Cascudo Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 08:00-17:00' }, { icon: '📍', label: '위치', value: 'Natal, Rio Grande do Norte, Brazil' }, { icon: '🚇', label: '교통', value: '나탈 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};

async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        let r;
        if (info.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, info.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
