const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'Museo Reina Sofía': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€. 월·수~토 19:00 이후, 일 13:30 이후 무료' }, { icon: '🕐', label: '운영시간', value: '월·수~토 10:00-21:00, 일 10:00-14:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Calle de Santa Isabel 52, Madrid, Spain' }, { icon: '🚇', label: '교통', value: '메트로 1 Atocha역 도보 3분. 피카소 게르니카 소장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Museo Tamayo': { vi: [{ icon: '🎫', label: '입장료', value: '85 MXN (~$4.70). 일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Paseo de la Reforma 51, Mexico City, Mexico' }, { icon: '🚇', label: '교통', value: '메트로 7 Auditorio역 도보 5분. 차풀테펙 공원' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museum Brandhorst': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€. 일 1€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Theresienstraße 35a, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Theresienstraße역 도보 3분. 사울레·트웜블리 전용관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museum Berlin-Karlshorst': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Zwieseler Str. 4, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S3 Karlshorst역 도보 10분. 1945년 독일 항복 조인 장소' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museu de Belles Arts de València': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Carrer de Sant Pius V 9, Valencia, Spain' }, { icon: '🚇', label: '교통', value: '메트로 3/5 Alameda역 도보 10분. 스페인 3대 미술관' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Museu Paraense Emílio Goeldi': { vi: [{ icon: '🎫', label: '입장료', value: '6 BRL (~$1.20)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Magalhães Barata 376, Belém, Pará, Brazil' }, { icon: '🚇', label: '교통', value: '벨렘 시내. 아마존 자연사·동식물원' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Museu de História Natural do Funchal': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00, 토·일 12:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Rua da Mouraria 31, Funchal, Madeira, Portugal' }, { icon: '🚇', label: '교통', value: '푼샬 구시가지 도보. 마데이라 자연사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museu Nacional de História Natural de Angola': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Luanda, Angola' }, { icon: '🚇', label: '교통', value: '루안다 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museu de História Natural Capão da Imbuia': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Rua Prof. Benedito Conceição 407, Curitiba, Brazil' }, { icon: '🚇', label: '교통', value: '쿠리치바 시내. 파라나 자연사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Histórico y Militar de Chile': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:30-17:00, 토·일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Blanco Encalada 1550, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 1 Los Héroes역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museo Interactivo Mirador': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4,500 CLP (~$5)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-18:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Punta Arenas 6711, La Granja, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 5 Mirador역 도보 5분. 어린이 과학체험' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Museo Nacional Aeronáutico y del Espacio': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Pedro Aguirre Cerda 5000, Cerrillos, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '산티아고 세리요스. 항공우주 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museo Horne': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-14:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Via dei Benci 6, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 베키오 다리에서 도보 3분. 지오토 십자가' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Paleontologico Astigiano e Monferrato': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '요일별 09:30-12:30, 15:00-17:30' }, { icon: '📍', label: '위치', value: 'Corso Alfieri 381, Asti, Italy' }, { icon: '🚇', label: '교통', value: '아스티역 도보 15분. 플리오세 고래 화석' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Salesiano Maggiorino Borgatello': { vi: [{ icon: '🎫', label: '입장료', value: '2,000 CLP (~$2.20)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-12:30, 15:00-17:30' }, { icon: '📍', label: '위치', value: 'Av. Bulnes 336, Punta Arenas, Chile' }, { icon: '🚇', label: '교통', value: '푼타아레나스 시내. 파타고니아 원주민·자연사' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museo Regional de Antofagasta': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Balmaceda 2786, Antofagasta, Chile' }, { icon: '🚇', label: '교통', value: '안토파가스타 해변가' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Regional de Aysén': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Eusebio Lillo 23, Coyhaique, Chile' }, { icon: '🚇', label: '교통', value: '코이아이케 시내. 아이센 지역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Regional de Iquique': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:30-17:30, 일 10:00-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Baquedano 951, Iquique, Chile' }, { icon: '🚇', label: '교통', value: '이키게 구시가지 바게다노 거리' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Pedro del Río Zañartu': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:30' }, { icon: '📍', label: '위치', value: 'Hualpén, Biobío, Chile' }, { icon: '🚇', label: '교통', value: '콘셉시온에서 차량 30분. 태평양 해안 저택' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Storico Nazionale dell\'Arte Sanitaria': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월·수·금 10:00-13:00' }, { icon: '📍', label: '위치', value: 'Lungotevere in Sassia 3, Rome, Italy' }, { icon: '🚇', label: '교통', value: '바티칸에서 도보 10분. 의학 역사' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Museu Entomológico Fritz Plaumann': { vi: [{ icon: '🎫', label: '입장료', value: '5 BRL (~$1)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-11:30, 13:30-17:00' }, { icon: '📍', label: '위치', value: 'Seara, Santa Catarina, Brazil' }, { icon: '🚇', label: '교통', value: '샤페코에서 차량 40분. 8만 종 곤충 표본' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museu do Expedicionário': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-12:00, 14:00-17:00, 토·일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Praça do Expedicionário, Curitiba, Brazil' }, { icon: '🚇', label: '교통', value: '쿠리치바 시내. 2차대전 브라질 원정군' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Nacional de Historia Natural (Dominican Republic)': { vi: [{ icon: '🎫', label: '입장료', value: '100 DOP (~$1.70)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'César Nicolás Penson, Santo Domingo, Dominican Republic' }, { icon: '🚇', label: '교통', value: '산토도밍고 Plaza de la Cultura' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Nacional de Historia Natural de Cuba': { vi: [{ icon: '🎫', label: '입장료', value: '3 CUP (~$0.12)' }, { icon: '🕐', label: '운영시간', value: '화~토 09:30-16:00, 일 09:30-12:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Obispo 61, La Habana Vieja, Havana, Cuba' }, { icon: '🚇', label: '교통', value: '아바나 비에하 오비스포 거리. 카리브 자연사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museu de História e Artes do Estado do Rio de Janeiro': { vi: [{ icon: '🎫', label: '입장료', value: '6 BRL (~$1.20)' }, { icon: '🕐', label: '운영시간', value: '화~금 11:00-17:00, 토·일 13:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Niterói, Rio de Janeiro, Brazil' }, { icon: '🚇', label: '교통', value: '니테로이 시내. 리우 건너편' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museu Paleontològic d\'Elx': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-14:00. 월·일 휴관' }, { icon: '📍', label: '위치', value: 'Plaça de Sant Joan, Elche, Spain' }, { icon: '🚇', label: '교통', value: '엘체역 도보 10분. 야자나무의 도시' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
