const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const infoByName = {
    '12 Service Battalion Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Richmond, BC, Canada' }, { icon: '🚇', label: '교통', value: '밴쿠버에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '15th Field Artillery Regiment, RCA Museum and Archives': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: '밴쿠버 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Aldan Maadyr National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200₽ (~$2)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kyzyl, Tuva Republic, Russia' }, { icon: '🚇', label: '교통', value: '크즐 시내 중심부' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }], website: 'https://museum.tuva.ru/' },
    'Alte Feste': { vi: [{ icon: '🎫', label: '입장료', value: 'N$50 (~$3)' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-18:00, 토 09:00-14:00' }, { icon: '📍', label: '위치', value: 'Robert Mugabe Avenue, Windhoek, Namibia' }, { icon: '🚇', label: '교통', value: '빈트후크 시내 중심' }, { icon: '⏱️', label: '관람시간', value: '1시간' }], website: 'https://www.museums.com.na/' },
    'Amdavad ni Gufa': { vi: [{ icon: '🎫', label: '입장료', value: '50 INR (~$0.60)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00' }, { icon: '📍', label: '위치', value: 'CEPT University, Ahmedabad, India' }, { icon: '🚇', label: '교통', value: '아메다바드 시내 오토릭샤' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Aqaba Archaeological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '2 JOD (~$3). Jordan Pass 포함' }, { icon: '🕐', label: '운영시간', value: '토~목 08:00-16:00, 금 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Aqaba, Jordan' }, { icon: '🚇', label: '교통', value: '아카바 시내 마말루크 성' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }], website: 'https://www.mota.gov.jo/' },
    'Archaeological Civic Museum and Edilberto Rosa Pinacotheca': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 15:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Amelia, Terni, Italy' }, { icon: '🚇', label: '교통', value: '테르니에서 버스 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Museum of ancient Capua': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Santa Maria Capua Vetere, Caserta, Italy' }, { icon: '🚇', label: '교통', value: '나폴리에서 기차 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Archaeological Museum of Ariano Irpino': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Ariano Irpino, Avellino, Italy' }, { icon: '🚇', label: '교통', value: '아벨리노에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Museum of Aruba': { vi: [{ icon: '🎫', label: '입장료', value: '$8 USD' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토~일 10:00-14:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Schelpstraat 42, Oranjestad, Aruba' }, { icon: '🚇', label: '교통', value: '오라녜스타드 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Museum of Capo Colonna': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Capo Colonna, Crotone, Italy' }, { icon: '🚇', label: '교통', value: '크로토네에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Museum of Teanum Sidicinum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Teano, Caserta, Italy' }, { icon: '🚇', label: '교통', value: '나폴리에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Museum of Venafro': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Venafro, Isernia, Italy' }, { icon: '🚇', label: '교통', value: '이세르니아에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Park of Urbs Salvia': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Urbisaglia, Macerata, Italy' }, { icon: '🚇', label: '교통', value: '마체라타에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Archäologisches Museum Hamburg und Stadtmuseum Harburg': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Museumsplatz 2, Hamburg-Harburg, Germany' }, { icon: '🚇', label: '교통', value: 'S-Bahn Harburg역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Archbishop Makarios III Foundation Art Galleries': { vi: [{ icon: '🎫', label: '입장료', value: '성인 2€' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00, 토 09:00-13:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Nicosia, Cyprus' }, { icon: '🚇', label: '교통', value: '니코시아 구시가지 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archeological Museum La Civitella': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-20:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Gen. Pianell, Chieti, Italy' }, { icon: '🚇', label: '교통', value: '키에티역에서 버스 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archeological Park of Siponto': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰 (야외)' }, { icon: '📍', label: '위치', value: 'Manfredonia, Foggia, Italy' }, { icon: '🚇', label: '교통', value: '만프레도니아 시내 차량 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Architecture & Design Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Kasarmikatu 24, Helsinki, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Arctic Convoy Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £4, 어린이 무료' }, { icon: '🕐', label: '운영시간', value: '부활절~10월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Aultbea, Wester Ross, Scotland, UK' }, { icon: '🚇', label: '교통', value: '인버네스에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Area archeologica e Antiquarium di Veleia': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lugagnano Val d\'Arda, Piacenza, Italy' }, { icon: '🚇', label: '교통', value: '피아첸차에서 차량 40분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Argyll and Sutherland Highlanders Regimental Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8 (스털링성 입장료 포함)' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-17:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Stirling Castle, Stirling, Scotland, UK' }, { icon: '🚇', label: '교통', value: '스털링역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Arian Baptistry': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:30-19:30 (동절기 ~16:30)' }, { icon: '📍', label: '위치', value: 'Via Degli Ariani, Ravenna, Italy' }, { icon: '🚇', label: '교통', value: '라벤나역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Arkansas Museum of Fine Arts': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~토 10:00-20:00, 일 11:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '501 E 9th St, Little Rock, AR, USA' }, { icon: '🚇', label: '교통', value: '리틀록 시내 MacArthur Park 내' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'ARKEN Museum of Modern Art': { vi: [{ icon: '🎫', label: '입장료', value: '성인 130 DKK (~$19), 학생 100 DKK' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Skovvej 100, Ishøj, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐에서 S-tog A선 Ishøj역 + 버스 128' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Armia Krajowa Museum in Kraków': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14 PLN (~$3.50), 학생 7 PLN' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'ul. Wita Stwosza 12, Kraków, Poland' }, { icon: '🚇', label: '교통', value: '크라쿠프 구시가지 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Armored Weaponry Museum, Poznań': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10 PLN (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'ul. Golęcińska 24, Poznań, Poland' }, { icon: '🚇', label: '교통', value: '포즈난 시내 버스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Armourgeddon Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (탱크 체험 별도)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Husbands Bosworth, Leicestershire, UK' }, { icon: '🚇', label: '교통', value: '레스터에서 차량 25분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Army Flying Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £10, 어린이 £5' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Middle Wallop, Hampshire, UK' }, { icon: '🚇', label: '교통', value: '안도버에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Army Light Aviation and Helicopter Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '수~일 14:00-18:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '58 Ave de l\'Aérodrome, Dax, France' }, { icon: '🚇', label: '교통', value: '닥스역에서 택시 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Army Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€. 일요일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Cuesta de Carlos V 2, Toledo, Spain' }, { icon: '🚇', label: '교통', value: '톨레도역에서 시내 버스 / 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Army Museum Lahore': { vi: [{ icon: '🎫', label: '입장료', value: '50 PKR (~$0.20)' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-17:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'The Mall, Lahore, Pakistan' }, { icon: '🚇', label: '교통', value: '라호르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Army Museum of Western Australia': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:30-15:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Artillery Barracks, Fremantle, WA, Australia' }, { icon: '🚇', label: '교통', value: '프리맨틀역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Army Museum Žižkov': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'U Památníku 2, Prague 3, Czech Republic' }, { icon: '🚇', label: '교통', value: '트램 Památník Národní역' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Army Quartermaster Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토~일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Fort Gregg-Adams, VA, USA' }, { icon: '🚇', label: '교통', value: '리치몬드에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'ARoS': { vi: [{ icon: '🎫', label: '입장료', value: '성인 150 DKK (~$22), 학생 100 DKK. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (수 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Aros Allé 2, Aarhus, Denmark' }, { icon: '🚇', label: '교통', value: '오르후스 중앙역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }], website: 'https://www.aros.dk/en/' },
    'Art Centre Salmela': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '6~8월 화~일 11:00-18:00' }, { icon: '📍', label: '위치', value: 'Mäntyharju, Finland' }, { icon: '🚇', label: '교통', value: '헬싱키에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Art Collections Chemnitz': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 학생 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Theaterplatz 1, Chemnitz, Germany' }, { icon: '🚇', label: '교통', value: '켐니츠 중앙역 트램 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Art Gallery of New South Wales': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (수 ~21:00)' }, { icon: '📍', label: '위치', value: 'Art Gallery Road, The Domain, Sydney, Australia' }, { icon: '🚇', label: '교통', value: '시드니 Martin Place역 도보 10분 / 버스' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Art Gallery of Ontario': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $25 CAD, 학생 $16. 25세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:30-17:00 (금 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '317 Dundas Street West, Toronto, Canada' }, { icon: '🚇', label: '교통', value: 'St. Patrick역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Art Gallery of Southwestern Manitoba': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Brandon, Manitoba, Canada' }, { icon: '🚇', label: '교통', value: '브랜던 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Art gallery of the convent of Sant\'Antonio': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-13:00' }, { icon: '📍', label: '위치', value: 'Nocera Inferiore, Salerno, Italy' }, { icon: '🚇', label: '교통', value: '노체라 인페리오레역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Art Museums of Bergen': { vi: [{ icon: '🎫', label: '입장료', value: '성인 150 NOK (~$14), 학생 75 NOK' }, { icon: '🕐', label: '운영시간', value: '매일 11:00-16:00 (목 ~20:00)' }, { icon: '📍', label: '위치', value: 'Rasmus Meyers allé, Bergen, Norway' }, { icon: '🚇', label: '교통', value: '베르겐역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Art Pavilion in Zagreb': { vi: [{ icon: '🎫', label: '입장료', value: '성인 40 HRK (~$6)' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-19:00, 일 10:00-13:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Trg Kralja Tomislava 22, Zagreb, Croatia' }, { icon: '🚇', label: '교통', value: '자그레브 중앙역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Art Sonje Center': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5,000원, 학생 3,000원' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '서울 종로구 율곡로3길 87' }, { icon: '🚇', label: '교통', value: '3호선 안국역 1번 출구 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Arthur M. Sackler Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:30' }, { icon: '📍', label: '위치', value: '1050 Independence Ave SW, Washington, D.C.' }, { icon: '🚇', label: '교통', value: 'Smithsonian역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Artport Tel Aviv': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-18:00, 금 ~14:00' }, { icon: '📍', label: '위치', value: 'Tel Aviv Port, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 항구 지역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Artspace Sydney': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '43-51 Cowper Wharf Road, Woolloomooloo, Sydney' }, { icon: '🚇', label: '교통', value: 'Kings Cross역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Artspace Tel Aviv': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~목 10:00-20:00, 금 10:00-14:00, 토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Tel Aviv, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Asenovgrad history museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4 BGN (~$2)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Asenovgrad, Plovdiv Province, Bulgaria' }, { icon: '🚇', label: '교통', value: '플로브디프에서 버스 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ashmolean Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Beaumont Street, Oxford, UK' }, { icon: '🚇', label: '교통', value: '옥스퍼드역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Art Gallery and Museum of the Island of San Lazzaro degli Armeni': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '매일 15:25 (가이드 투어만)' }, { icon: '📍', label: '위치', value: 'Isola di San Lazzaro, Venice, Italy' }, { icon: '🚇', label: '교통', value: '산마르코에서 바포레토 20번 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Arte Vetraria Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-12:30, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Altare, Savona, Italy' }, { icon: '🚇', label: '교통', value: '사보나에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '1st Infantry Division Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-16:00, 토·일 12:00-16:00' }, { icon: '📍', label: '위치', value: 'Fort Riley, Kansas, USA' }, { icon: '🚇', label: '교통', value: '캔자스시티에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '100th Bomb Group Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '5~9월 토·일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Common Road, Dickleburgh, Norfolk, UK' }, { icon: '🚇', label: '교통', value: '노리치에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Art Mûr': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Montreal, Quebec, Canada' }, { icon: '🚇', label: '교통', value: '몬트리올 메트로' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Ars Diva Galerie': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '프라하 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Artazart': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (서점/갤러리)' }, { icon: '🕐', label: '운영시간', value: '월~토 11:00-20:00, 일 11:00-19:00' }, { icon: '📍', label: '위치', value: '83 Quai de Valmy, Paris 10th, France' }, { icon: '🚇', label: '교통', value: '메트로 Jacques Bonsergent역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'ArtSociates': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Lembang, Bandung, Indonesia' }, { icon: '🚇', label: '교통', value: '반둥 시내에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ashton Armoury Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Victoria, BC, Canada' }, { icon: '🚇', label: '교통', value: '빅토리아 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Art Shelter Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-18:00, 금 10:00-14:00. 토 휴관' }, { icon: '📍', label: '위치', value: 'Jerusalem, Israel' }, { icon: '🚇', label: '교통', value: '예루살렘 트램' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Arma - Galeria de Artes': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Marabá, Pará, Brazil' }, { icon: '🚇', label: '교통', value: '마라바 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Art Centre Väinölä': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '6~8월 화~일 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Varkaus, Finland' }, { icon: '🚇', label: '교통', value: '바르카우스역 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};

async function run() {
    let ok = 0, fail = 0;
    for (const [name, d] of Object.entries(infoByName)) {
        const vi = JSON.stringify(d.vi);
        let r;
        if (d.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, d.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 이름 불일치, 남은 미입력: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
