const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // Notable museums from batch 19
    'Ghana Armed Forces Museum': { vi: [{ icon: '🎫', label: '입장료', value: '5 GHS (~$0.40)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Kumasi, Ashanti Region, Ghana' }, { icon: '🚇', label: '교통', value: '쿠마시 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Great Plains Dinosaur Museum and Field Station': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $5' }, { icon: '🕐', label: '운영시간', value: '5~9월 화~토 10:00-17:00' }, { icon: '📍', label: '위치', value: '405 North 1st Street East, Malta, MT, USA' }, { icon: '🚇', label: '교통', value: '글래쉬어 카운트리 인근. 브라키로포사우루스 화석' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Geoscience Hall, Chelungpu Fault Preservation Park': { vi: [{ icon: '🎫', label: '입장료', value: '50 TWD (~$1.60)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jhushan Township, Nantou, Taiwan' }, { icon: '🚇', label: '교통', value: '타이중에서 차량 45분. 1999 지진 단층 보존' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Goulandris Natural History Museum of Thessaloniki': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-14:00' }, { icon: '📍', label: '위치', value: 'Thermi, Thessaloniki, Greece' }, { icon: '🚇', label: '교통', value: '테살로니키 교외 테르미' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geological Museum of University of Łódź': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-15:00' }, { icon: '📍', label: '위치', value: 'Śródmieście-Wschód, Łódź, Poland' }, { icon: '🚇', label: '교통', value: '우치 시내. 대학 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Geologisches Freilichtmuseum Blockheide': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '항시 개방' }, { icon: '📍', label: '위치', value: 'Gmünd, Niederösterreich, Austria' }, { icon: '🚇', label: '교통', value: '빈에서 차량 2시간. 화강암 거석 야외 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'GEOMuseum Radein': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '5~10월 화·금 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Aldein, South Tyrol, Italy' }, { icon: '🚇', label: '교통', value: '볼차노에서 차량 30분. 페르미안 화석' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Göttingen Museum of Zoology': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Berliner Straße 28, Göttingen, Germany' }, { icon: '🚇', label: '교통', value: '괴팅겐역 도보 10분. 대학 자연사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Goldfuß-Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-16:00. 주말 사전 예약' }, { icon: '📍', label: '위치', value: 'Nussallee 8, Bonn, Germany' }, { icon: '🚇', label: '교통', value: '본 대학 캠퍼스. 고생물학 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Giacomo Ciamician Chemistry Collection': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Via F. Selmi 2, Bologna, Italy' }, { icon: '🚇', label: '교통', value: '볼로냐 대학교 캠퍼스 내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Grauerort Fortress': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '4~10월 토·일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Stade, Lower Saxony, Germany' }, { icon: '🚇', label: '교통', value: '스타데에서 차량 20분. 엘베강 요새' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Brittany American Cemetery and Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Saint-James, Normandy, France' }, { icon: '🚇', label: '교통', value: '렌에서 차량 1시간. 미군 2차대전 묘지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bristol Train of Artillery Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토 09:00-12:00 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Providence, RI, USA' }, { icon: '🚇', label: '교통', value: '프로비던스 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Collezioni di Palazzo Nerucci': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '토·일 10:00-13:00, 15:00-18:00' }, { icon: '📍', label: '위치', value: 'Castel del Piano, Grosseto, Tuscany, Italy' }, { icon: '🚇', label: '교통', value: '그로세토에서 차량 40분. 아미아타산 기슭' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Engineer Cervino Maritime Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: '부에노스아이레스 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Engineers Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Kouvola, Finland' }, { icon: '🚇', label: '교통', value: '코우볼라역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Eräjärven kivimuseo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '6~8월 매일 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Orivesi, Finland' }, { icon: '🚇', label: '교통', value: '탐페레에서 차량 30분. 돌·광물 박물관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Espace Karim Francis': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-20:00' }, { icon: '📍', label: '위치', value: '1 Sherif Street, Downtown Cairo, Egypt' }, { icon: '🚇', label: '교통', value: '카이로 다운타운. 이집트 현대미술 갤러리' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Doctor Benjamin Apthorp Gould National Meteorological Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-15:00' }, { icon: '📍', label: '위치', value: 'Barrio Observatorio, Córdoba, Argentina' }, { icon: '🚇', label: '교통', value: '코르도바 천문대 지역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Entomology Museum of La Bollène-Vésubie': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '7~8월 화~일 14:00-18:00' }, { icon: '📍', label: '위치', value: 'La Bollène-Vésubie, Nice, France' }, { icon: '🚇', label: '교통', value: '니스에서 차량 1시간. 알프스 곤충학' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Forestry Museum „Little Wooden House"': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '4~10월 화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Feldberger Seenlandschaft, Mecklenburg, Germany' }, { icon: '🚇', label: '교통', value: '베를린에서 차량 2시간. 산림 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Femöre Coastal Artillery Battery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '6~8월 토·일 11:00-16:00' }, { icon: '📍', label: '위치', value: 'Oxelösund, Sweden' }, { icon: '🚇', label: '교통', value: '뉘셰핑에서 차량 20분. 해안 포대' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Finnish Reserve officer school museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-15:00 (사전 예약)' }, { icon: '📍', label: '위치', value: 'Hamina, Finland' }, { icon: '🚇', label: '교통', value: '코우볼라에서 버스 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Friedrichshain Photo Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 14:00-19:00' }, { icon: '📍', label: '위치', value: 'Helsingforser Platz, Berlin-Friedrichshain, Germany' }, { icon: '🚇', label: '교통', value: 'S/U Frankfurter Allee역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Grafschaftsmuseum Wertheim': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-12:00, 14:30-16:30, 토·일 14:30-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Rathausgasse 6, Wertheim, Germany' }, { icon: '🚇', label: '교통', value: '베르트하임 시내. 프랑켄 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galeria Pierre Verger': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Salvador, Bahia, Brazil' }, { icon: '🚇', label: '교통', value: '살바도르 시내. 피에르 베르제 사진' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galería Patricia Ready': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-19:00, 토 11:00-14:00' }, { icon: '📍', label: '위치', value: 'Espoz 3125, Vitacura, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '산티아고 비타쿠라. 칠레 현대미술' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Geographical Museum Professor Miguel Ángel Fernández': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: '부에노스아이레스 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
