const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'Royal Ontario Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $23 CAD, 학생 $18. 매주 화 18시 이후 무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:30 (금 ~20:30)' }, { icon: '📍', label: '위치', value: '100 Queens Park, Toronto, ON, Canada' }, { icon: '🚇', label: '교통', value: 'TTC Museum역 도보 1분. 다니엘 리베스킨드 크리스탈 건축' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Royal Tyrrell Museum of Palaeontology': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $21 CAD' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (하계 09:00-21:00)' }, { icon: '📍', label: '위치', value: 'Midland Provincial Park, Drumheller, AB, Canada' }, { icon: '🚇', label: '교통', value: '캘거리에서 차량 1.5시간. 세계 최대 공룡 화석 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Royal Academy of Arts': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (상설전). 기획전 유료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (금 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Burlington House, Piccadilly, London, UK' }, { icon: '🚇', label: '교통', value: 'Tube Piccadilly Circus/Green Park역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Royal Museums of Fine Arts of Belgium': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€, 학생 무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Rue de la Régence 3, Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '메트로 1/5 Gare Centrale역 도보 5분. 브뤼겔·마그리트 소장' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Rembrandt House Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 17.50€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Jodenbreestraat 4, Amsterdam, Netherlands' }, { icon: '🚇', label: '교통', value: '메트로 M51/M53/M54 Waterlooplein역 도보 1분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Russian Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 550 RUB (~$6), 학생 250 RUB' }, { icon: '🕐', label: '운영시간', value: '월 10:00-20:00, 수·금~일 10:00-18:00, 목 13:00-21:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Inzhenernaya St. 4, St. Petersburg, Russia' }, { icon: '🚇', label: '교통', value: '메트로 Nevsky Prospekt역 도보 5분. 러시아 미술 최대 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Pinacoteca Vaticana': { vi: [{ icon: '🎫', label: '입장료', value: '바티칸 미술관 입장 17€ 포함' }, { icon: '🕐', label: '운영시간', value: '월~토 08:00-19:00 (입장 ~17:00). 일 휴관 (매월 마지막 일 무료 09:00-14:00)' }, { icon: '📍', label: '위치', value: 'Viale Vaticano, Vatican City' }, { icon: '🚇', label: '교통', value: '메트로 A Ottaviano역 도보 10분. 라파엘로·카라바조' }, { icon: '⏱️', label: '관람시간', value: '바티칸 전체 3-4시간 중 일부' }] },
    'Pinakothek der Moderne': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€. 일 1€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (목 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Barer Str. 40, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U2 Theresienstraße역 도보 5분. 현대미술·디자인·건축·판화' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'PinchukArtCentre': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 12:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1/3-2 Velyka Vasylkivska & Baseina, Kyiv, Ukraine' }, { icon: '🚇', label: '교통', value: '메트로 Ploshcha Lva Tolstoho역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Pirelli HangarBicocca': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '목~일 10:00-22:00. 월~수 휴관' }, { icon: '📍', label: '위치', value: 'Via Chiese 2, Milan, Italy' }, { icon: '🚇', label: '교통', value: '메트로 M5 Ponale역 도보 5분. 안젤름 키퍼 탑 설치' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Power Station of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '200 Huayuangang Road, Shanghai, China' }, { icon: '🚇', label: '교통', value: '지하철 4호선 Xizang South Road역. 상하이 비엔날레 본부' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Salvador Dalí Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $29' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00 (목 ~20:00)' }, { icon: '📍', label: '위치', value: 'One Dali Blvd, St. Petersburg, FL, USA' }, { icon: '🚇', label: '교통', value: '세인트피터즈버그 시내. 야히오 건축' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Saint Louis Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00 (금 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '1 Fine Arts Dr, Forest Park, St. Louis, MO, USA' }, { icon: '🚇', label: '교통', value: 'MetroLink Forest Park역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Salzburg Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Mozartplatz 1, Salzburg, Austria' }, { icon: '🚇', label: '교통', value: '잘츠부르크 구시가지 모차르트광장' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Salar Jung Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 ₹50 (~$0.60)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00. 금 휴관' }, { icon: '📍', label: '위치', value: 'Salar Jung Rd, Darulshifa, Hyderabad, India' }, { icon: '🚇', label: '교통', value: 'MMTS 니잠팔리역 도보 10분. 인도 3대 국립초대 박물관' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Rosengart Collection': { vi: [{ icon: '🎫', label: '입장료', value: 'CHF 20 (~$22)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (11~3월 11:00-17:00)' }, { icon: '📍', label: '위치', value: 'Pilatusstrasse 10, Lucerne, Switzerland' }, { icon: '🚇', label: '교통', value: '루체른역 도보 3분. 피카소·클레 전문' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Ricardo Brennand Institute': { vi: [{ icon: '🎫', label: '입장료', value: '성인 R$30 (~$6)' }, { icon: '🕐', label: '운영시간', value: '화~일 13:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Alameda Antônio Brennand, Várzea, Recife, Brazil' }, { icon: '🚇', label: '교통', value: '레시페 시내에서 차량 30분. 중세 무기·네덜란드 회화' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Pointe-à-Callière Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $26 CAD' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '350 Place Royale, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 Place-d\'Armes역 도보 5분. 몬트리올 고고학' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Prague Castle Picture Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '350 CZK (~$15) 프라하성 통합 포함' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00 (동절기 ~16:00)' }, { icon: '📍', label: '위치', value: 'Prague Castle, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 A Malostranská역 + 트램 22. 루돌프 2세 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '프라하성 전체 3시간 중 일부' }] },
    'Royal Museum for Central Africa': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Leuvensesteenweg 13, Tervuren, Belgium' }, { icon: '🚇', label: '교통', value: '메트로 1 Montgomery역+트램 44' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Royal Museum of the Armed Forces and Military History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:00, 토·일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Jubelpark 3, Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '메트로 1/5 Merode역 도보 3분. 쥐벨파크' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Royal Palace of Naples': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '목~화 09:00-20:00. 수 휴관' }, { icon: '📍', label: '위치', value: 'Piazza del Plebiscito, Naples, Italy' }, { icon: '🚇', label: '교통', value: '메트로 1 T. San Ferdinando역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Racławice Panorama': { vi: [{ icon: '🎫', label: '입장료', value: '성인 30 PLN (~$7.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Jan Ewangelista Purkyniego 11, Wrocław, Poland' }, { icon: '🚇', label: '교통', value: '브로츠와프역 트램 2/10. 라츠와비체 전투 파노라마 회화' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Redpath Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00, 일 11:00-17:00. 토 휴관' }, { icon: '📍', label: '위치', value: '859 Rue Sherbrooke O, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 McGill역 도보 5분. 맥길 대학교' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Sam Noble Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $7' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00. 일 휴관' }, { icon: '📍', label: '위치', value: '2401 Chautauqua Ave, Norman, OK, USA' }, { icon: '🚇', label: '교통', value: '오클라호마 대학교 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Sakıp Sabancı Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 50 TRY (~$1.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Sakıp Sabancı Caddesi 42, Emirgan, Istanbul, Turkey' }, { icon: '🚇', label: '교통', value: '이스탄불 에미르간 보스포러스 해협변' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Pinacoteca Nazionale di Bologna': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via delle Belle Arti 56, Bologna, Italy' }, { icon: '🚇', label: '교통', value: '볼로냐역 버스 C. 볼로냐파 회화 - 라파엘로·구이도 레니' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Potteries Museum & Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00, 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Bethesda St, Hanley, Stoke-on-Trent, UK' }, { icon: '🚇', label: '교통', value: '스톡온트렌트역 도보 15분. 스태퍼드셔 도자기' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Plovdiv Regional History Museum': { vi: [{ icon: '🎫', label: '입장료', value: '6 BGN (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: '1 Tsanko Lavrenov Str, Old Plovdiv, Bulgaria' }, { icon: '🚇', label: '교통', value: '플로브디프 올드타운. 유럽 문화수도 2019' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Royal Danish Naval Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Overgaden oven Vandet 58, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: '메트로 M3 Christianshavn역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'RiesCraterMuseum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Eugene-Shoemaker-Platz 1, Nördlingen, Germany' }, { icon: '🚇', label: '교통', value: '뇌르들링겐역 도보 5분. 운석 충돌 크레이터' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Sammlung Goetz': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (사전 예약)' }, { icon: '🕐', label: '운영시간', value: '목·금 14:00-18:00' }, { icon: '📍', label: '위치', value: 'Oberföhringer Str. 103, Munich, Germany' }, { icon: '🚇', label: '교통', value: 'U4 Arabellapark역. 헤르조그 & 드뫼롱 건축' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Samudrika Naval Marine Museum': { vi: [{ icon: '🎫', label: '입장료', value: '₹50 (~$0.60)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-12:30, 14:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Port Blair, Andaman & Nicobar Islands, India' }, { icon: '🚇', label: '교통', value: '포트블레어 시내. 인도양 해양생물' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
