const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★★★ World-class
    'Palais de Tokyo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 13€' }, { icon: '🕐', label: '운영시간', value: '수~월 12:00-21:00. 화 휴관' }, { icon: '📍', label: '위치', value: '13 Avenue du Président Wilson, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 9 Iéna역 도보 3분. 유럽 최대 현대미술 센터' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Palazzo Vecchio': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12.50€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-19:00 (목 ~14:00)' }, { icon: '📍', label: '위치', value: 'Piazza della Signoria, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 시뇨리아 광장. 500인의 방 미켈란젤로·바사리' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Palace of Caserta': { vi: [{ icon: '🎫', label: '입장료', value: '성인 14€ (궁전+정원)' }, { icon: '🕐', label: '운영시간', value: '수~월 08:30-19:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Viale Douhet 2a, Caserta, Italy' }, { icon: '🚇', label: '교통', value: '카세르타역 도보 5분. UNESCO 세계유산. 이탈리아 베르사유' }, { icon: '⏱️', label: '관람시간', value: '3시간' }] },
    'Palace Museum in Wilanów': { vi: [{ icon: '🎫', label: '입장료', value: '성인 25 PLN (~$6.25)' }, { icon: '🕐', label: '운영시간', value: '월·수·토 09:30-16:00, 목·금 09:30-18:00, 일 10:30-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'ul. Stanisława Kostki Potockiego 10/16, Warsaw, Poland' }, { icon: '🚇', label: '교통', value: '바르샤바 시내 버스 180/522' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Oxford University Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Parks Road, Oxford, UK' }, { icon: '🚇', label: '교통', value: '옥스포드역 버스. 빅토리아 네오고딕 건축 + 도도 표본' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Ozeaneum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 17€' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-18:00 (하계 ~20:00)' }, { icon: '📍', label: '위치', value: 'Hafenstraße 11, Stralsund, Germany' }, { icon: '🚇', label: '교통', value: '슈트랄준트역 도보 10분. 발트해 해양 수족관. 유럽 올해의 박물관 2010' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Museo Dolores Olmedo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 100 MXN (~$5.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. México 5843, Xochimilco, Mexico City, Mexico' }, { icon: '🚇', label: '교통', value: '트렌 리헤로 La Noria역. 프리다 칼로·디에고 리베라 최대 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Museo Fortuny': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-18:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Campo San Beneto, San Marco, Venice, Italy' }, { icon: '🚇', label: '교통', value: '바포레토 Sant\'Angelo역. 마리아노 포르투니 아틀리에' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Museo di Storia Naturale': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~금 09:00-17:00, 토·일 14:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lungadige Porta Vittoria 9, Verona, Italy' }, { icon: '🚇', label: '교통', value: '베로나 아디제강변' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo di Storia Naturale di Venezia': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (뮤지엄패스 포함)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Fondaco dei Turchi, Santa Croce, Venice, Italy' }, { icon: '🚇', label: '교통', value: '바포레토 San Stae역. 13세기 터키 상관' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Osaka Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '성인 300엔' }, { icon: '🕐', label: '운영시간', value: '화~일 09:30-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Nagai Park, Osaka, Japan' }, { icon: '🚇', label: '교통', value: 'Midosuji Line Nagai역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'PalaisPopulaire': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '수~월 11:00-18:00 (목 ~21:00). 화 휴관' }, { icon: '📍', label: '위치', value: 'Unter den Linden 5, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S/U Brandenburger Tor역 도보 5분. 도이치뱅크 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Omaha Beach Memorial Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8.90€' }, { icon: '🕐', label: '운영시간', value: '3~11월 매일 09:30-18:00' }, { icon: '📍', label: '위치', value: 'Avenue de la Libération, Saint-Laurent-sur-Mer, France' }, { icon: '🚇', label: '교통', value: '바이외에서 차량 15분. D-Day 오마하 해변' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Palais des Papes': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:30 (하계 ~20:00)' }, { icon: '📍', label: '위치', value: 'Place du Palais, Avignon, France' }, { icon: '🚇', label: '교통', value: '아비뇽 TGV역 셔틀. UNESCO 세계유산. 14세기 교황청' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Palaeontological Museum of the University of Zurich': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 08:00-17:00, 토·일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Karl Schmid-Str. 4, Zurich, Switzerland' }, { icon: '🚇', label: '교통', value: '취리히 대학교 캠퍼스' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Palazzo Davanzati': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '매일 08:15-13:50. 매월 2·4 일 및 1·3·5 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Porta Rossa 13, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 시내. 14세기 중세 저택' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Palazzo Chiericati Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€ (뮤지엄카드 포함)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Matteotti 37/39, Vicenza, Italy' }, { icon: '🚇', label: '교통', value: '비첸차역 도보 10분. 팔라디오 건축 UNESCO' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Ouidah Museum of History': { vi: [{ icon: '🎫', label: '입장료', value: '1,500 CFA (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Ouidah, Benin' }, { icon: '🚇', label: '교통', value: '코토누에서 차량 40분. 노예무역 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Oldmasters Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토·일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Rue de la Régence 3, Brussels, Belgium' }, { icon: '🚇', label: '교통', value: '왕립미술관 구관. 브뤼겔·루벤스·반 데이크' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Osthaus-Museum Hagen': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Museumsquartier Hagen, Germany' }, { icon: '🚇', label: '교통', value: '하겐역 도보 10분. 앙리 반 데 벨데 건축' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Geologico Giovanni Capellini': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-13:00 (일부 오후 개관). 토·일 사전 예약' }, { icon: '📍', label: '위치', value: 'Via Zamboni 63, Bologna, Italy' }, { icon: '🚇', label: '교통', value: '볼로냐 대학교 지구' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo di storia naturale dell\'Accademia dei Fisiocritici': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-14:00. 토·일 사전 예약' }, { icon: '📍', label: '위치', value: 'Piazzetta Silvio Gigli 2, Siena, Italy' }, { icon: '🚇', label: '교통', value: '시에나 시내. 1691년 설립' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Museo di Storia Naturale del Mediterraneo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Roma 234, Livorno, Italy' }, { icon: '🚇', label: '교통', value: '리보르노역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Naval Museum of Iquique': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Iquique, Chile' }, { icon: '🚇', label: '교통', value: '이키게 해안가. 태평양 전쟁' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Naval Museum of Punta Arenas': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 09:30-12:30, 14:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Pedro Montt 981, Punta Arenas, Chile' }, { icon: '🚇', label: '교통', value: '푼타아레나스 시내. 마젤란 해협 해양사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Nikkei Internment Memorial Centre': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $10 CAD' }, { icon: '🕐', label: '운영시간', value: '5~9월 매일 09:30-17:00' }, { icon: '📍', label: '위치', value: 'New Denver, BC, Canada' }, { icon: '🚇', label: '교통', value: '밴쿠버에서 차량 8시간. 일본계 캐나다인 억류 역사' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Pakistan Museum of Natural History': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Shakarparian, Islamabad, Pakistan' }, { icon: '🚇', label: '교통', value: '이슬라마바드 샤카르파리안 언덕' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Naturkundemuseum Potsdam': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Breite Str. 13, Potsdam, Germany' }, { icon: '🚇', label: '교통', value: '포츠담역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Overgaden': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 12:00-17:00, 토·일 12:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Overgaden Neden Vandet 17, Copenhagen, Denmark' }, { icon: '🚇', label: '교통', value: '메트로 M3 Christianshavn역. 현대미술' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Palazzo Mansi National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~토 08:30-19:30. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'Via Galli Tassi 43, Lucca, Italy' }, { icon: '🚇', label: '교통', value: '루카 성벽 안. 17세기 귀족 저택' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Museo Diocesano of Palermo': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:30. 일 09:00-13:30' }, { icon: '📍', label: '위치', value: 'Via Matteo Bonello 2, Palermo, Italy' }, { icon: '🚇', label: '교통', value: '팔레르모 대성당 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Palazzo Ducale': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-13:15, 15:00-17:30' }, { icon: '📍', label: '위치', value: 'Piazza della Signoria 1, Gubbio, Italy' }, { icon: '🚇', label: '교통', value: '구비오 시내. 르네상스 공작 궁전' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Natural History Museum, Thailand': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Technopolis, Pathum Thani, Thailand' }, { icon: '🚇', label: '교통', value: '방콕에서 차량 40분. 태국 국립과학센터' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
