const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const d = {
    // ★ World-class museums
    "Galleria Borghese": { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€ + 2€ 예약 필수' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관. 2시간 단위 입장' }, { icon: '📍', label: '위치', value: 'Piazzale Scipione Borghese 5, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 A Spagna역 도보 15분 / 버스 910' }, { icon: '⏱️', label: '관람시간', value: '2시간 (시간제)' }] },
    "Galleria dell'Accademia": { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€. 매월 첫째 일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 08:15-18:50. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Ricasoli 58-60, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 SMN역 도보 10분. 미켈란젤로 다비드상' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    "Gallerie dell'Accademia": { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '월 08:15-14:00, 화~일 08:15-19:15' }, { icon: '📍', label: '위치', value: 'Campo della Carità 1050, Venice, Italy' }, { icon: '🚇', label: '교통', value: '바포레토 1/2번 Accademia 정류장. 베네치아 회화 최대 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    "Gemäldegalerie Berlin": { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€, 학생 5€. 18세 이하 무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-18:00 (목 ~20:00), 토·일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Matthäikirchplatz, Berlin, Germany' }, { icon: '🚇', label: '교통', value: 'S/U Potsdamer Platz역 도보 5분. 쿨투어포룸' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    "Galleria Nazionale d'Arte Moderna e Contemporanea di Roma": { vi: [{ icon: '🎫', label: '입장료', value: '성인 10€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Viale delle Belle Arti 131, Rome, Italy' }, { icon: '🚇', label: '교통', value: '트램 19 / 버스 490. 보르게세 공원 인근' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    "Galleria Nazionale d'Arte Antica": { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Palazzo Barberini, Via delle Quattro Fontane 13, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 A Barberini역 도보 2분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Gansong Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '전시별 상이 (기획전 유료)' }, { icon: '🕐', label: '운영시간', value: '기획전 기간 중 운영 (상시 개관 아님)' }, { icon: '📍', label: '위치', value: '서울 성북구 성북로 102-11' }, { icon: '🚇', label: '교통', value: '지하철 4호선 한성대입구역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'GAM Centro Cultural Gabriela Mistral': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Av. Libertador Bernardo O\'Higgins 227, Santiago, Chile' }, { icon: '🚇', label: '교통', value: '메트로 1호선 Universidad Católica역 도보 2분' }, { icon: '⏱️', label: '관람시간', value: '1-2시간' }] },
    // Major Italian galleries
    'Galleria Estense': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~토 08:30-19:30, 일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Largo Porta Sant\'Agostino 337, Modena, Italy' }, { icon: '🚇', label: '교통', value: '모데나역 도보 15분. 에스테 가문 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    "Galleria Giorgio Franchetti alla Ca' d'Oro": { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~토 08:15-19:15, 일·월 10:00-18:00' }, { icon: '📍', label: '위치', value: "Ca' d'Oro, Strada Nova, Venice, Italy" }, { icon: '🚇', label: '교통', value: "바포레토 1번 Ca' d'Oro 정류장" }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galleria Nazionale delle Marche': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 08:30-19:15. 월 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Rinascimento 13, Palazzo Ducale, Urbino, Italy' }, { icon: '🚇', label: '교통', value: '페사로에서 버스 1시간. 라파엘로 고향' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Galleria Sabauda': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€ (왕궁 복합 포함)' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via XX Settembre 86, Turin, Italy' }, { icon: '🚇', label: '교통', value: '메트로 Porta Nuova역 도보 10분. 사보이 왕가 컬렉션' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Galleria Spada': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '수~월 08:30-19:30. 화 휴관' }, { icon: '📍', label: '위치', value: 'Piazza Capo di Ferro 13, Rome, Italy' }, { icon: '🚇', label: '교통', value: '캄포 데 피오리 도보 5분. 보로미니 투시 복도' }, { icon: '⏱️', label: '관람시간', value: '45분' }] },
    'Garibaldi Museum in Caprera': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Isola di Caprera, La Maddalena, Sardinia, Italy' }, { icon: '🚇', label: '교통', value: '올비아에서 차량+페리. 가리발디의 마지막 저택' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Galleria nazionale della Puglia': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Rogadeo, Bitonto, Bari, Italy' }, { icon: '🚇', label: '교통', value: '바리에서 기차 Bitonto역 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galleria nazionale di Cosenza': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Palazzo Arnone, Cosenza, Calabria, Italy' }, { icon: '🚇', label: '교통', value: '코센차역 도보 20분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fondazione Scienza e Tecnica': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Via Giusti 29, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 산타크로체 인근' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // German galleries
    "Gemäldegalerie der Akademie der bildenden Künste Wien": { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€, 학생 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Schillerplatz 3, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U1/U2/U4 Karlsplatz역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galerie Neue Meister': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€ (알테 마이스터 포함)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Theaterplatz 1, Albertinum, Dresden, Germany' }, { icon: '🚇', label: '교통', value: '드레스덴 중앙역 트램 4/8/9번 Theaterplatz' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Gelsenkirchen Art Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 4€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Horster Straße 5-7, Gelsenkirchen, Germany' }, { icon: '🚇', label: '교통', value: '겔젠키르헨역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Notable international galleries
    'Galerie nationale du Jeu de Paume': { vi: [{ icon: '🎫', label: '입장료', value: '성인 12€' }, { icon: '🕐', label: '운영시간', value: '화 11:00-21:00, 수~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: '1 Place de la Concorde, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 1/8/12 Concorde역. 튀일리 정원 내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galerie Maeght': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00 (7~8월 ~19:00)' }, { icon: '📍', label: '위치', value: '623 Chemin des Gardettes, Saint-Paul-de-Vence, France' }, { icon: '🚇', label: '교통', value: '니스에서 차량 30분. 미로·자코메티·칼더 작품' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Galerie Perrotin': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-19:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '76 Rue de Turenne, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 8 Saint-Sébastien-Froissart역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galerie Thaddaeus Ropac': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-19:00' }, { icon: '📍', label: '위치', value: 'Pantin (Paris) + Salzburg + London' }, { icon: '🚇', label: '교통', value: '파리 Pantin: 메트로 5 Porte de Pantin역' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Galerie Krinzinger': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 12:00-18:00, 토 11:00-16:00' }, { icon: '📍', label: '위치', value: 'Seilerstätte 16, Vienna, Austria' }, { icon: '🚇', label: '교통', value: 'U3 Stubentor역 도보 3분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galerie de l\'UQAM': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 12:00-18:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: 'UQAM, Rue Sainte-Catherine, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 Berri-UQAM역' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Galerie nationale d\'art textile Beauvais': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-12:30, 14:00-18:00' }, { icon: '📍', label: '위치', value: '24 Rue Henri Brispot, Beauvais, France' }, { icon: '🚇', label: '교통', value: '파리 북역에서 기차 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Czech galleries
    'Galerie Jaroslava Fragnera': { vi: [{ icon: '🎫', label: '입장료', value: '80 CZK (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Betlémské náměstí, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 B Národní třída역 도보 5분. 건축 갤러리' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Gallery of Steel Figures': { vi: [{ icon: '🎫', label: '입장료', value: '성인 290 CZK (~$13)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-21:00' }, { icon: '📍', label: '위치', value: 'Husova 7, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 A/B Staroměstská역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Japanese
    'Fukui Prefectural Varve Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 200엔' }, { icon: '🕐', label: '운영시간', value: '수~일 09:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Wakasa, Fukui, Japan' }, { icon: '🚇', label: '교통', value: '와카사역에서 버스. 연층 퇴적물 전시' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gamagōri Museum of Earth, Life and the Sea': { vi: [{ icon: '🎫', label: '입장료', value: '성인 500엔' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Gamagōri, Aichi, Japan' }, { icon: '🚇', label: '교통', value: '가마고리역에서 버스 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Genbudō Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Toyooka, Hyogo, Japan' }, { icon: '🚇', label: '교통', value: '기노사키 온천역에서 차량 10분. 현무암 천연기념물' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Geological Museum of China': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-16:30. 월 휴관' }, { icon: '📍', label: '위치', value: '15 Yangrou Hutong, Xicheng, Beijing, China' }, { icon: '🚇', label: '교통', value: '지하철 4호선 Xisi역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    // Others
    'Gayer-Anderson Museum': { vi: [{ icon: '🎫', label: '입장료', value: '80 EGP (~$2.50)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-16:00' }, { icon: '📍', label: '위치', value: 'Ahmad Ibn Tulun Sq, Cairo, Egypt' }, { icon: '🚇', label: '교통', value: '이븐 툴룬 모스크 인근. 제임스 본드 촬영지' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Fotografiska Stockholm': { vi: [{ icon: '🎫', label: '입장료', value: '성인 220 SEK (~$21)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-23:00 (금~일 ~01:00)' }, { icon: '📍', label: '위치', value: 'Stadsgårdshamnen 22, Stockholm, Sweden' }, { icon: '🚇', label: '교통', value: 'T-bana Slussen역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Fort Amiel Museum': { vi: [{ icon: '🎫', label: '입장료', value: '20 ZAR (~$1)' }, { icon: '🕐', label: '운영시간', value: '월~금 08:00-16:00' }, { icon: '📍', label: '위치', value: 'Scott Street, Newcastle, KwaZulu-Natal, South Africa' }, { icon: '🚇', label: '교통', value: '뉴캐슬 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gass Forest Museum': { vi: [{ icon: '🎫', label: '입장료', value: '10 INR (~$0.12)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:30' }, { icon: '📍', label: '위치', value: 'Coimbatore, Tamil Nadu, India' }, { icon: '🚇', label: '교통', value: '코임바토르 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Gargoti Museum': { vi: [{ icon: '🎫', label: '입장료', value: '200 INR (~$2.40)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Sinnar, Nashik, Maharashtra, India' }, { icon: '🚇', label: '교통', value: '나시크에서 차량 30분. 광물 결정 박물관' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Gallery of Maps': { vi: [{ icon: '🎫', label: '입장료', value: '바티칸 박물관 입장 17€ 포함' }, { icon: '🕐', label: '운영시간', value: '월~토 08:00-19:00 (마지막 입장 17:00). 매월 마지막 일 무료' }, { icon: '📍', label: '위치', value: 'Vatican Museums, Vatican City' }, { icon: '🚇', label: '교통', value: '메트로 A Ottaviano역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '바티칸 전체 3-4시간 중 일부' }] },
    'Gallery Oldham': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~토 10:00-17:00. 일 휴관' }, { icon: '📍', label: '위치', value: 'Greaves Street, Oldham, Greater Manchester, UK' }, { icon: '🚇', label: '교통', value: '올덤역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galería de la Historia de Concepción': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-13:00, 14:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lincoyan esquina Larenas, Concepción, Chile' }, { icon: '🚇', label: '교통', value: '콘셉시온 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galerie des Batailles': { vi: [{ icon: '🎫', label: '입장료', value: '베르사유궁 입장 21€ 포함' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-18:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Palace of Versailles, Versailles, France' }, { icon: '🚇', label: '교통', value: 'RER C Versailles-Château Rive Gauche역' }, { icon: '⏱️', label: '관람시간', value: '베르사유 전체 3-5시간 중 일부' }] },
    'Garderhøj Fort': { vi: [{ icon: '🎫', label: '입장료', value: '성인 50 DKK (~$7.50)' }, { icon: '🕐', label: '운영시간', value: '5~10월 토·일 11:00-16:00' }, { icon: '📍', label: '위치', value: 'Jægersborg Allé 220, Gentofte, Denmark' }, { icon: '🚇', label: '교통', value: '코펜하겐에서 S-tog Jægersborg역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geological Museum of Budapest': { vi: [{ icon: '🎫', label: '입장료', value: '성인 1,200 HUF (~$3.50)' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-16:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: 'Stefánia út 14, Budapest, Hungary' }, { icon: '🚇', label: '교통', value: '메트로 M2 Pillangó utca역. 아르누보 건물' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geological Museum of the Dolomites': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Piazza SS. Filippo e Giacomo 1, Predazzo, Trentino, Italy' }, { icon: '🚇', label: '교통', value: '트렌토에서 차량 50분. 돌로미테 지질학' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geological Museum of the Republic of Kazakhstan': { vi: [{ icon: '🎫', label: '입장료', value: '500 KZT (~$1)' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-18:00' }, { icon: '📍', label: '위치', value: 'Almaty, Kazakhstan' }, { icon: '🚇', label: '교통', value: '알마티 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Geological Museum after H. Karapetyan': { vi: [{ icon: '🎫', label: '입장료', value: '500 AMD (~$1.30)' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00. 일·월 휴관' }, { icon: '📍', label: '위치', value: '2 Aram Street, Yerevan, Armenia' }, { icon: '🚇', label: '교통', value: '예레반 공화국 광장 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galerija Miroslav Kraljević (G-MK)': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 12:00-20:00, 토 10:00-14:00' }, { icon: '📍', label: '위치', value: 'Šubićeva 29, Zagreb (Donji grad), Croatia' }, { icon: '🚇', label: '교통', value: '자그레브 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galerie Lelong': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:30-18:00' }, { icon: '📍', label: '위치', value: '13 Rue de Téhéran, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 2/3 Villiers역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Fonderie Darling': { vi: [{ icon: '🎫', label: '입장료', value: '무료~10 CAD' }, { icon: '🕐', label: '운영시간', value: '수~일 12:00-19:00' }, { icon: '📍', label: '위치', value: '745 Rue Ottawa, Montreal, QC, Canada' }, { icon: '🚇', label: '교통', value: '메트로 Square-Victoria역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Galerie Patrick Seguin': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-19:00' }, { icon: '📍', label: '위치', value: '5 Rue des Taillandiers, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 8 Ledru-Rollin역. 장 프루베/샬로트 페리앙 가구 전문' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galerie Mennour': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-19:00' }, { icon: '📍', label: '위치', value: '47 Rue Saint-André des Arts, Paris, France' }, { icon: '🚇', label: '교통', value: '메트로 4/10 Odéon역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Galerie Villa Pellé': { vi: [{ icon: '🎫', label: '입장료', value: '100 CZK (~$4.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Pelléova 10, Prague 6, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 A Hradčanská역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Galerie SVU Mánes': { vi: [{ icon: '🎫', label: '입장료', value: '100 CZK (~$4.50)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Masarykovo nábřeží 250, Prague, Czech Republic' }, { icon: '🚇', label: '교통', value: '메트로 B Karlovo náměstí역 도보 3분. 블타바 강변' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Gallery Galschiøt': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00, 토 10:00-14:00' }, { icon: '📍', label: '위치', value: 'Banevej 22, Odense, Denmark' }, { icon: '🚇', label: '교통', value: '오덴세에서 버스. 옌스 갈쉬외트 조각 작업실' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    // Fort continued
    'Fort d\'Uxegney': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€' }, { icon: '🕐', label: '운영시간', value: '4~10월 일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Uxegney, Vosges, France' }, { icon: '🚇', label: '교통', value: '에피날에서 차량 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Fort de Battice': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€' }, { icon: '🕐', label: '운영시간', value: '3~11월 일 13:00-17:00' }, { icon: '📍', label: '위치', value: 'Herve, Liège, Belgium' }, { icon: '🚇', label: '교통', value: '리에주에서 차량 25분. 마지노선 벨기에 요새' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Galeriehaus Max Hetzler': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-18:00' }, { icon: '📍', label: '위치', value: 'Köln (Cologne), Germany' }, { icon: '🚇', label: '교통', value: '쾰른 시내' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'General Hernan Pujato Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Buenos Aires, Argentina' }, { icon: '🚇', label: '교통', value: '부에노스아이레스 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};
async function run() {
    let ok = 0, fail = 0;
    for (const [name, info] of Object.entries(d)) {
        const vi = JSON.stringify(info.vi);
        const r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 불일치, 남은: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
