const { Pool } = require('pg'); require('dotenv').config();
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

const infoByName = {
    '13th/18th Royal Hussars Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Barnsley, South Yorkshire, UK' }, { icon: '🚇', label: '교통', value: '반슬리역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    '1862 Battle of Harpers Ferry Museum': { vi: [{ icon: '🎫', label: '입장료', value: '$20 (국립공원 입장료)' }, { icon: '🕐', label: '운영시간', value: '매일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Harpers Ferry, WV, USA' }, { icon: '🚇', label: '교통', value: '워싱턴DC에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Archaeological Museum of Lamezia Terme': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-19:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Lamezia Terme, Catanzaro, Italy' }, { icon: '🚇', label: '교통', value: '라메지아 테르메역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Army Heritage Museum, Shimla': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-14:00, 15:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'The Mall, Shimla, Himachal Pradesh, India' }, { icon: '🚇', label: '교통', value: '심라 시내 도보' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Asia Culture Center': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (수·토 ~21:00). 월 휴관' }, { icon: '📍', label: '위치', value: '광주광역시 동구 문화전당로 38' }, { icon: '🚇', label: '교통', value: '광주 지하철 문화전당역 직결' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'ASTRA National Museum Complex': { vi: [{ icon: '🎫', label: '입장료', value: '성인 30 RON (~$7)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00 (동절기 ~16:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Calea Rășinarilor 12, Sibiu, Romania' }, { icon: '🚇', label: '교통', value: '시비우 시내에서 버스 1번' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Athens War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 6€' }, { icon: '🕐', label: '운영시간', value: '월~토 09:00-19:00, 일 09:30-17:00' }, { icon: '📍', label: '위치', value: '2 Rizari Street, Athens, Greece' }, { icon: '🚇', label: '교통', value: '메트로 Evangelismos역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Auckland Art Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (특별전 별도)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Cnr Kitchener & Wellesley Streets, Auckland, NZ' }, { icon: '🚇', label: '교통', value: '브리토마트역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Auckland War Memorial Museum Tāmaki Paenga Hira': { vi: [{ icon: '🎫', label: '입장료', value: '오클랜드 주민 무료, 타 지역 성인 NZ$28' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Auckland Domain, Parnell, Auckland, NZ' }, { icon: '🚇', label: '교통', value: '시내에서 버스 / Auckland Domain 내' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'August Kestner Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€. 금요일 무료' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00 (수 ~20:00). 월 휴관' }, { icon: '📍', label: '위치', value: 'Trammplatz 3, Hannover, Germany' }, { icon: '🚇', label: '교통', value: '하노버 중앙역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Augustiner Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 7€, 학생 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Augustinerplatz, Freiburg im Breisgau, Germany' }, { icon: '🚇', label: '교통', value: '프라이부르크 중앙역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Australian Armour and Artillery Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD$25, 어린이 $12' }, { icon: '🕐', label: '운영시간', value: '매일 09:30-16:00' }, { icon: '📍', label: '위치', value: 'Smithfield, Cairns, QLD, Australia' }, { icon: '🚇', label: '교통', value: '케언즈에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Australian Centre for Contemporary Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~금 10:00-17:00, 토~일 11:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: '111 Sturt Street, Southbank, Melbourne, Australia' }, { icon: '🚇', label: '교통', value: 'South Melbourne 트램' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Australian War Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Treloar Crescent, Campbell, Canberra, Australia' }, { icon: '🚇', label: '교통', value: '캔버라 시내에서 버스 / 무료 주차' }, { icon: '⏱️', label: '관람시간', value: '3-4시간' }] },
    'Averoff Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '수~월 10:00-16:00. 화 휴관' }, { icon: '📍', label: '위치', value: 'Metsovo, Ioannina, Greece' }, { icon: '🚇', label: '교통', value: '이오안니나에서 버스 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Aviation Heritage Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 AUD$15' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Bull Creek Drive, Bull Creek, Perth, Australia' }, { icon: '🚇', label: '교통', value: '퍼스에서 차량 20분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Bahrain National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 1 BHD (~$2.60)' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-20:00' }, { icon: '📍', label: '위치', value: 'Al Fatih Highway, Manama, Bahrain' }, { icon: '🚇', label: '교통', value: '마나마 시내 택시 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Balhousie Castle': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 10:00-15:30. 토·일 휴관' }, { icon: '📍', label: '위치', value: 'Hay Street, Perth, Scotland, UK' }, { icon: '🚇', label: '교통', value: '퍼스역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Baltimore Museum of Art': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '수~일 10:00-17:00. 월·화 휴관' }, { icon: '📍', label: '위치', value: '10 Art Museum Drive, Baltimore, MD, USA' }, { icon: '🚇', label: '교통', value: '볼티모어 시내 버스 3, 11번' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Bangkok Art and Culture Centre': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-21:00. 월 휴관' }, { icon: '📍', label: '위치', value: '939 Rama I Road, Pathumwan, Bangkok, Thailand' }, { icon: '🚇', label: '교통', value: 'BTS National Stadium역 직결' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Bangladesh National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '20 BDT (~$0.20)' }, { icon: '🕐', label: '운영시간', value: '토~수 09:30-16:30, 금 15:00-20:00. 목 휴관' }, { icon: '📍', label: '위치', value: 'Shahbag, Dhaka, Bangladesh' }, { icon: '🚇', label: '교통', value: '다카 Shahbag 사거리' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Baratti and Populonia Archeological Park': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€' }, { icon: '🕐', label: '운영시간', value: '3~10월 매일 10:00-19:00. 동절기 토·일만' }, { icon: '📍', label: '위치', value: 'Piombino, Livorno, Italy' }, { icon: '🚇', label: '교통', value: '피옴비노에서 차량 15분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Barbican Centre': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (갤러리: 성인 £18)' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-21:00 (일 ~20:00)' }, { icon: '📍', label: '위치', value: 'Silk Street, Barbican, London, UK' }, { icon: '🚇', label: '교통', value: 'Barbican역 도보 3분 / Moorgate역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '2시간' }] },
    'Bargello National Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 9€. 매월 첫째 일요일 무료' }, { icon: '🕐', label: '운영시간', value: '월~일 08:15-14:00 (폐관 시간 변동). 매월 첫째·셋째 월요일 휴관' }, { icon: '📍', label: '위치', value: 'Via del Proconsolo 4, Florence, Italy' }, { icon: '🚇', label: '교통', value: '피렌체 산타마리아 노벨라역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Barry War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (기부 환영)' }, { icon: '🕐', label: '운영시간', value: '토 10:00-16:00' }, { icon: '📍', label: '위치', value: 'Barry, Vale of Glamorgan, Wales, UK' }, { icon: '🚇', label: '교통', value: '배리역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Base Borden Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '월~금 09:00-16:00' }, { icon: '📍', label: '위치', value: 'CFB Borden, Ontario, Canada' }, { icon: '🚇', label: '교통', value: '토론토에서 차량 1.5시간' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Basilica of Sant\'Apollinare in Classe': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '월~토 08:30-19:30, 일 13:00-19:30' }, { icon: '📍', label: '위치', value: 'Via Romea Sud 224, Classe, Ravenna, Italy' }, { icon: '🚇', label: '교통', value: '라벤나역에서 버스 4번 15분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Bastogne War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 15€, 어린이 9€' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Colline du Mardasson 5, Bastogne, Belgium' }, { icon: '🚇', label: '교통', value: '브뤼셀에서 차량 2시간 / 바스토뉴 시내' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }], website: 'https://www.bastognewarmuseum.be/' },
    'Baths of Caracalla': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-일몰 1시간 전. 월 휴관' }, { icon: '📍', label: '위치', value: 'Viale delle Terme di Caracalla, Rome, Italy' }, { icon: '🚇', label: '교통', value: '메트로 B선 Circo Massimo역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Battle of Britain Bunker': { vi: [{ icon: '🎫', label: '입장료', value: '성인 £8, 어린이 £4' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'St Andrew\'s Road, Uxbridge, London, UK' }, { icon: '🚇', label: '교통', value: 'Piccadilly Line Uxbridge역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Battleship Memorial Park': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $15, 어린이 $6' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-17:00' }, { icon: '📍', label: '위치', value: '2703 Battleship Pkwy, Mobile, AL, USA' }, { icon: '🚇', label: '교통', value: '모빌 시내에서 차량 10분. 무료 주차' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Battleship New Jersey Museum and Memorial': { vi: [{ icon: '🎫', label: '입장료', value: '성인 $27.95, 어린이 $21.95' }, { icon: '🕐', label: '운영시간', value: '매일 10:00-17:00' }, { icon: '📍', label: '위치', value: '100 Clinton St, Camden, NJ, USA' }, { icon: '🚇', label: '교통', value: '필라델피아에서 PATCO 기차 City Hall역' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Bauhaus Center Tel Aviv': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (투어 별도)' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-19:30, 금 10:00-14:30. 토 휴관' }, { icon: '📍', label: '위치', value: '77 Dizengoff St, Tel Aviv, Israel' }, { icon: '🚇', label: '교통', value: '텔아비브 시내 중심' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bavarian Army Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3.50€' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:30. 월 휴관' }, { icon: '📍', label: '위치', value: 'Paradeplatz 4, Ingolstadt, Germany' }, { icon: '🚇', label: '교통', value: '잉골슈타트역 도보 15분' }, { icon: '⏱️', label: '관람시간', value: '1.5-2시간' }] },
    'Beelden aan Zee': { vi: [{ icon: '🎫', label: '입장료', value: '성인 16€, 학생 8€' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-17:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Harteveltstraat 1, Scheveningen, Netherlands' }, { icon: '🚇', label: '교통', value: '덴하그 중앙에서 트램 1번 종점' }, { icon: '⏱️', label: '관람시간', value: '1-1.5시간' }] },
    'Beit Avi Chai': { vi: [{ icon: '🎫', label: '입장료', value: '무료~50 ILS (행사별 상이)' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-22:00, 금 09:00-14:00. 토 휴관' }, { icon: '📍', label: '위치', value: '44 King George Street, Jerusalem, Israel' }, { icon: '🚇', label: '교통', value: '예루살렘 트램 King George역' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Belarusian Great Patriotic War Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 10 BYN (~$3)' }, { icon: '🕐', label: '운영시간', value: '화~일 10:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Prospect Pobeditelej 8, Minsk, Belarus' }, { icon: '🚇', label: '교통', value: '민스크 메트로 Niamiha역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '2-3시간' }] },
    'Backwoods Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~토 11:00-17:00' }, { icon: '📍', label: '위치', value: 'Melbourne, Victoria, Australia' }, { icon: '🚇', label: '교통', value: '멜버른 CBD 내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Barbur Gallery': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '일~목 10:00-18:00' }, { icon: '📍', label: '위치', value: 'Jerusalem, Israel' }, { icon: '🚇', label: '교통', value: '예루살렘 시내' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Basilio Cascella Civic Museum': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-13:00, 16:00-19:00' }, { icon: '📍', label: '위치', value: 'Viale Gabriele D\'Annunzio, Pescara, Italy' }, { icon: '🚇', label: '교통', value: '페스카라역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Basilica Church of Santa Maria Maggiore': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '매일 08:00-18:00' }, { icon: '📍', label: '위치', value: 'Tuscania, Viterbo, Italy' }, { icon: '🚇', label: '교통', value: '비테르보에서 차량 30분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Basilica of San Saturnino': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-13:00' }, { icon: '📍', label: '위치', value: 'Piazza San Cosimo, Cagliari, Italy' }, { icon: '🚇', label: '교통', value: '칼리아리역 도보 10분' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Auswanderermuseum – Josef Reichl Museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 5€' }, { icon: '🕐', label: '운영시간', value: '5~10월 화~일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Güssing, Burgenland, Austria' }, { icon: '🚇', label: '교통', value: '빈에서 차량 2시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bajuwarenhof Kirchheim': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '야외 전시, 항시 개방' }, { icon: '📍', label: '위치', value: 'Kirchheim bei München, Germany' }, { icon: '🚇', label: '교통', value: '뮌헨에서 S2 Kirchheim역' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Bad Bergzaben tin figure museum': { vi: [{ icon: '🎫', label: '입장료', value: '성인 3€' }, { icon: '🕐', label: '운영시간', value: '수·토·일 14:00-17:00' }, { icon: '📍', label: '위치', value: 'Bad Bergzabern, Rhineland-Palatinate, Germany' }, { icon: '🚇', label: '교통', value: '카를스루에에서 기차 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Beatty Street Drill Hall': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: '620 Beatty St, Vancouver, BC, Canada' }, { icon: '🚇', label: '교통', value: 'Stadium-Chinatown역 도보 5분' }, { icon: '⏱️', label: '관람시간', value: '30분-1시간' }] },
    'Art Collections Chemnitz': { vi: [{ icon: '🎫', label: '입장료', value: '성인 8€, 학생 5€' }, { icon: '🕐', label: '운영시간', value: '화~일 11:00-18:00. 월 휴관' }, { icon: '📍', label: '위치', value: 'Theaterplatz 1, Chemnitz, Germany' }, { icon: '🚇', label: '교통', value: '켐니츠 중앙역 트램 5분' }, { icon: '⏱️', label: '관람시간', value: '1.5시간' }] },
    'Aviation Education Exhibition Hall': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '화~일 09:00-17:00' }, { icon: '📍', label: '위치', value: 'Xiehe Village, Taiwan' }, { icon: '🚇', label: '교통', value: '타이중에서 차량' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bangladesh Military Museum': { vi: [{ icon: '🎫', label: '입장료', value: '10 BDT' }, { icon: '🕐', label: '운영시간', value: '토~목 10:00-17:00. 금 휴관' }, { icon: '📍', label: '위치', value: 'Bijoy Sarani, Dhaka, Bangladesh' }, { icon: '🚇', label: '교통', value: '다카 시내' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Bandjoun Station': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '예약제' }, { icon: '📍', label: '위치', value: 'Bandjoun, West Region, Cameroon' }, { icon: '🚇', label: '교통', value: '두알라에서 차량 4시간' }, { icon: '⏱️', label: '관람시간', value: '1-2시간' }] },
    'Battalion Park': { vi: [{ icon: '🎫', label: '입장료', value: '무료 (야외)' }, { icon: '🕐', label: '운영시간', value: '매일 일출~일몰' }, { icon: '📍', label: '위치', value: 'Calgary, Alberta, Canada' }, { icon: '🚇', label: '교통', value: '캘거리 시내 버스' }, { icon: '⏱️', label: '관람시간', value: '30분' }] },
    'Battle of the Windmill National Historic Site': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Prescott, Ontario, Canada' }, { icon: '🚇', label: '교통', value: '오타와에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
    'Battle of the Châteauguay National Historic Site': { vi: [{ icon: '🎫', label: '입장료', value: '무료' }, { icon: '🕐', label: '운영시간', value: '6~9월 매일 10:00-17:00' }, { icon: '📍', label: '위치', value: 'Très-Saint-Sacrement, Quebec, Canada' }, { icon: '🚇', label: '교통', value: '몬트리올에서 차량 1시간' }, { icon: '⏱️', label: '관람시간', value: '1시간' }] },
};

async function run() {
    let ok = 0, fail = 0;
    for (const [name, d] of Object.entries(infoByName)) {
        const vi = JSON.stringify(d.vi);
        let r;
        if (d.website) {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1, website=$2 WHERE name=$3 AND "visitorInfo" IS NULL RETURNING id', [vi, d.website, name]);
        } else {
            r = await pool.query('UPDATE "Museum" SET "visitorInfo"=$1 WHERE name=$2 AND "visitorInfo" IS NULL RETURNING id', [vi, name]);
        }
        if (r.rowCount > 0) ok += r.rowCount; else fail++;
    }
    const { rows: [c] } = await pool.query('SELECT count(*) as c FROM "Museum" WHERE "visitorInfo" IS NULL');
    console.log(`✅ ${ok}개 업데이트, ❌ ${fail}개 이름 불일치, 남은 미입력: ${c.c}개`);
    pool.end();
}
run().catch(e => { console.error(e); pool.end(); });
